(ns lcert.formal.ri-conversion
  "Generic copy of lcert.formal.conversion over an R-interpretation ri : RInt (rint.clj;
  Theorem 4.6 design note §3), generated by formal/tools/gen_ri.py: the
  constants that depend on the model carry the suffix _ri and take ri after
  encTy.  Hand edits at the R-specific steps are marked `;; RI:`.  The
  standard namespace's documentation follows, with the same renaming.

  F3m — conversion invariance (R4-metatheory.md §1.5, §3.2 Lemma 3.2,
  §3.3 Lemma 3.3's conversion clause) and the Conv case of the fundamental
  lemma (Lemma 3.6).

  The paper: if t ≡ t′ (both skeleton-typed) then ⟦t⟧ⁿη = ⟦t′⟧ⁿη
  (Lemma 3.2), and if A ≡ B then Vⁿₖ(A)η = Vⁿₖ(B)η (Lemma 3.3).  Conversion
  (conv.clj, Cv) is a chain of single steps (Step: a head step Hd at a
  path), taken in either direction, every element of which is a
  skeleton-well-formed type (SkJ Bool.true) satisfying nbr.

  DEVIATION (forced; conv_skj_counterexample_ri is the kernel-checked witness).  Over
  skeleton typing alone the conversion clause is FALSE for this
  denotation, for the reason substitution.clj §5 found for Lemma 3.1: a
  branch list (bnil / bcons) is skeleton-typed at Lbl → s, but skOf gives it
  no skeleton, so ⟦f u⟧ defaults when u is a branch list.  A β-step that
  moves a branch list out of argument position changes the denotation:
      b  = (λ(y : Π(l:Lbl).Bool). caseL Bool 0 y) (bcons tt bnil)
      b′ = caseL Bool 0 (bcons tt bnil)   (b ⇝ b′ by β)
  ⟦b⟧ = ff (the application defaults) but ⟦b′⟧ = tt, so the old Cv related T(b′) and T(b), both
  skeleton-well-formed, but V_ri(T b′) = {⋆} and V_ri(T b) = ∅.  The paper's
  syntax has no branch lists as terms (caseLbl's branches are part of its
  syntax); the encoding's bnil / bcons are first-class Exp terms only for
  structural recursion (syntax.clj).  Steps that read an argument through
  skOf (β, and the ι-steps that substitute or apply) therefore assume nbr
  (§1): a branch list may occur only as the branch list of a caseL, or as
  the tail of a branch list. Cv now requires nbr of each element,
  excluding this counterexample throughout a conversion chain.  Real (Rt/Tl) terms type branch lists only at the pseudo-type
  tBrs, which no binder or argument has.

  Contents.
  §1  skOf_complete (nbrF is defined in conv.clj): on a skeleton-typed term with no stray
      branch list, skOf returns the typed skeleton.
  §2  Inversion of skeleton typing (InvSkJ / skj_inv / inv_<ctor>).
  §3  EquivAt_ri, and the head steps proved so far (Lemma 3.2 for Hd).
      ι that only selects a branch (ite, elimB, recN at zero) and print
      preserve the denotation with no nbr hypothesis.  β preserves it
      when the redex is nbr (den_beta_ri, via den_subst1_ri and skOf_complete).
      conv_skj_counterexample_ri is the kernel-checked failure of β over
      SkJ alone.  itR on a leaf (den_itRL_nbr_ri) needs nbr so the label has an skOf.  T(tt) and T(ff) preserve V_ri (hd_tTT_ri, hd_tTF_ri).
  β for let (den_betaLet_ri) is the same pattern.  §4 proves the remaining head steps: recNS, recSL, recSN, caseLb, itR on a node, and δ (a canonical code term denotes its code, snode included).  §5 packages them: hd_den_ri is Lemma 3.2 at the root, and den_step_nil_ri is the empty-path case of position congruence.  A step under a constructor, the chain for V_ri, and F_conv_ri are not in this file yet.

  Equivalence at a position.  EquivAt_ri w G s a b says a may replace b at a
  position of mode w, context G and skeleton s:
    w = false (a term):  ⟦a⟧ G s η = ⟦b⟧ G s η for every η, and
                         skOf G a = skOf G b (application and let read the
                         skeleton of their argument through skOf);
    w = true (a type):   skel a = skel b, and
                         Vⁿₖ(a) G η = Vⁿₖ(b) G η at the skeleton skel b.
  Only the source of a step need be typed (and nbrF): the target's
  denotation, skOf and V_ri are computed from the source's."
  (:require [lcert.formal.rint] [lcert.formal.ri-den] [lcert.formal.ri-sem] [lcert.formal.ri-model] [lcert.formal.ri-subst] [lcert.formal.ri-unfold] [lcert.formal.ri-substitution] [lcert.formal.ri-fundamental]
            [ansatz.core :as a]
            [clojure.walk :as walk]
            [lcert.formal.base :refer [thm kdef lv]]
            [lcert.formal.usage :refer :all]
            [lcert.formal.syntax :refer :all]
            [lcert.formal.skel :refer :all]
            [lcert.formal.conv :refer :all]
            [lcert.formal.judgment :refer :all]
            [lcert.formal.carrier :refer :all]
            [lcert.formal.den :refer :all]
            [lcert.formal.sem :refer :all]
            [lcert.formal.model :refer :all]
            [lcert.formal.subst :refer :all]
            [lcert.formal.unfold :refer :all]
            [lcert.formal.substitution :refer :all]
            [lcert.formal.skeletons :refer :all]
            [lcert.formal.skof :refer :all]
            [lcert.formal.fundamental :refer :all]))

(def ^:private exp-fields @#'lcert.formal.syntactic/exp-fields)
(def ^:private skj-rules @#'lcert.formal.substitution/skj-rules)
(def ^:private cong @#'lcert.formal.substitution/cong)

;; ===========================================================================
;; §1  Branch lists in branch-list position; skOf is complete there
;; ===========================================================================

;; nbrF and nbr now live in conv.clj, before Cv. Their definitions are
;; unchanged; conversion explicitly records the condition at every element.

;; The rules whose conclusion is a formation judgment (w = true).
(def ^:private formation-rules '#{wEmpty wUnit wBool wNat wLbl wSyn wDia wR wT wPi wSig})

;; skOf_complete: G ⊢ e : s (a term) with no stray branch list ⟹
;; skOf G e = some s.  (skOf_typed, substitution.clj, shows skOf is none or
;; s on any typed term; none arises only from a branch list at the end of
;; skOf's spine, which nbrF excludes.)  Induction on the derivation, one
;; explicit tactic list per rule (in SkJ's constructor order, skj-rules):
;; formation rules are refuted by w = false; bnil / bcons by nbrF.
(defn- skc-case [rule]
  (cons '(intro hw hn)
        (cond
          (formation-rules rule) '[(exact (Bool.noConfusion hw))]
          :else
          (case rule
            sVar '[(exact h)]
            sIte '[(exact (ih_ht rfl (band_left ((nbrF t) false) ((nbrF e) false)
                                        (band_right ((nbrF b) false) (Bool.and ((nbrF t) false) ((nbrF e) false)) hn))))]
            sLam '[(exact (skOf_lam G r A t s (ih_ht rfl (band_right ((nbrF A) false) ((nbrF t) false) hn))))]
            sApp '[(exact (skOf_app G f u (Sk.arr s t) (ih_hf rfl (band_left ((nbrF f) false) ((nbrF u) false) hn))))]
            sBnil '[(exact (Bool.noConfusion hn))]
            sBcons '[(exact (Bool.noConfusion hn))]
            '[(rfl)]))))

;; (skOf_complete: the standard constant is used)

;; The term form: a typed term with no stray branch list.
;; (skOf_ok: the standard constant is used)

;; ===========================================================================
;; §2  Inversion of skeleton typing
;; ===========================================================================
;; InvSkJ w G e s: the premises of the (unique) SkJ rule for e's
;; constructor, with the conclusion's indices as equations.  skj_inv proves
;; SkJ w G e s → InvSkJ w G e s by induction on the derivation, and
;; inv_<ctor> restates it at each constructor with the clause spelled out.
;; (Ansatz has no inversion tactic; `cases` on an indexed family with
;; non-variable indices is unreliable.)

(defn- ands [xs] (reduce (fn [acc x] (list 'And x acc)) (last xs) (reverse (butlast xs))))
(defn- sj [w G e s] (list 'SkJ w G e s))
(def ^:private WF '(Eq Bool w0 Bool.false))
(def ^:private WT '(Eq Bool w0 Bool.true))
(defn- s= [x] (list 'Eq 'Sk 's0 x))
(defn- ex [v ty body] (list 'Exists (list 'fn [v ':- ty] body)))
(defn- cons-sk [s G] (list 'List.cons 'Sk s G))
(defn- HT [q] (list 'Sk.arr 'Sk.dia (list 'Sk.arr 'Sk.lbl (list 'Sk.arr q (list 'Sk.arr q q)))))

(def ^:private inv-clause
  (merge
   (zipmap '[tEmpty tUnit tBool tNat tLbl tSyn tDia tR] (repeat (ands [WT (s= 'Sk.unit)])))
   {'tT (ands [WT (s= 'Sk.unit) (sj 'Bool.false 'G0 'b 'Sk.bool)])
    'tPi (ands [WT (s= 'Sk.unit) (sj 'Bool.true 'G0 'A 'Sk.unit) (sj 'Bool.true (cons-sk '(skel A) 'G0) 'B 'Sk.unit)])
    'tSig (ands [WT (s= 'Sk.unit) (sj 'Bool.true 'G0 'A 'Sk.unit) (sj 'Bool.true (cons-sk '(skel A) 'G0) 'B 'Sk.unit)])
    'var (ands [WF '(Eq (Option Sk) (nthS G0 i) (Option.some Sk s0))])
    'star (ands [WF (s= 'Sk.unit)])
    'abort (ands [WF (s= '(skel A)) (sj 'Bool.true 'G0 'A 'Sk.unit) (sj 'Bool.false 'G0 't 'Sk.unit)])
    'tt (ands [WF (s= 'Sk.bool)])
    'ff (ands [WF (s= 'Sk.bool)])
    'ite (ands [WF (sj 'Bool.false 'G0 'b 'Sk.bool) (sj 'Bool.false 'G0 't 's0) (sj 'Bool.false 'G0 'e 's0)])
    'elimB (ands [WF (s= '(skel P)) (sj 'Bool.true (cons-sk 'Sk.bool 'G0) 'P 'Sk.unit) (sj 'Bool.false 'G0 'b 'Sk.bool)
                  (sj 'Bool.false 'G0 't '(skel P)) (sj 'Bool.false 'G0 'e '(skel P))])
    'zero (ands [WF (s= 'Sk.nat)])
    'succ (ands [WF (s= 'Sk.nat) (sj 'Bool.false 'G0 'n 'Sk.nat)])
    'recN (ands [WF (s= '(skel P)) (sj 'Bool.true (cons-sk 'Sk.nat 'G0) 'P 'Sk.unit) (sj 'Bool.false 'G0 'z '(skel P))
                 (sj 'Bool.false '(sk2 (skel P) Sk.nat G0) 's '(skel P)) (sj 'Bool.false 'G0 'n 'Sk.nat)])
    'lbl (ands [WF (s= 'Sk.lbl)])
    'caseL (ands [WF (s= '(skel P)) (sj 'Bool.true (cons-sk 'Sk.lbl 'G0) 'P 'Sk.unit) (sj 'Bool.false 'G0 'a 'Sk.lbl)
                  (sj 'Bool.false 'G0 'bs '(Sk.arr Sk.lbl (skel P)))])
    'bnil (ands [WF (ex 's1 'Sk (s= '(Sk.arr Sk.lbl s1)))])
    'bcons (ands [WF (ex 's1 'Sk (ands [(s= '(Sk.arr Sk.lbl s1)) (sj 'Bool.false 'G0 'h 's1) (sj 'Bool.false 'G0 't '(Sk.arr Sk.lbl s1))]))])
    'sleaf (ands [WF (s= 'Sk.syn) (sj 'Bool.false 'G0 'a 'Sk.lbl)])
    'snode (ands [WF (s= 'Sk.syn) (sj 'Bool.false 'G0 'a 'Sk.lbl) (sj 'Bool.false 'G0 'c1 'Sk.syn) (sj 'Bool.false 'G0 'c2 'Sk.syn)])
    'recS (ands [WF (s= '(skel P)) (sj 'Bool.true (cons-sk 'Sk.syn 'G0) 'P 'Sk.unit)
                 (sj 'Bool.false (cons-sk 'Sk.lbl 'G0) 'tl '(skel P))
                 (sj 'Bool.false '(sk2 (skel P) (skel P) (sk2 Sk.syn Sk.syn (List.cons Sk Sk.lbl G0))) 'tn '(skel P))
                 (sj 'Bool.false 'G0 'c 'Sk.syn)])
    'leaf (ands [WF (s= 'Sk.cert) (sj 'Bool.false 'G0 'a 'Sk.lbl)])
    'node (ands [WF (s= 'Sk.cert) (sj 'Bool.false 'G0 'd 'Sk.dia) (sj 'Bool.false 'G0 'a 'Sk.lbl)
                 (sj 'Bool.false 'G0 'r1 'Sk.cert) (sj 'Bool.false 'G0 'r2 'Sk.cert)])
    'itR (ands [WF (s= '(skel X)) (sj 'Bool.true 'G0 'X 'Sk.unit) (sj 'Bool.false 'G0 'g '(Sk.arr Sk.lbl (skel X)))
                (sj 'Bool.false 'G0 'h (HT '(skel X))) (sj 'Bool.false 'G0 'r 'Sk.cert)])
    'prn (ands [WF (s= 'Sk.syn) (sj 'Bool.false 'G0 'r 'Sk.cert)])
    'lam (ands [WF (ex 's1 'Sk (ands [(s= '(Sk.arr (skel A) s1)) (sj 'Bool.true 'G0 'A 'Sk.unit)
                                      (sj 'Bool.false (cons-sk '(skel A) 'G0) 't 's1)]))])
    'app (ands [WF (ex 's1 'Sk (ands [(sj 'Bool.false 'G0 'f '(Sk.arr s1 s0)) (sj 'Bool.false 'G0 'u 's1)]))])
    'pair (ands [WF (ex 'rr 'U (ex 'AA 'Exp (ex 'BB 'Exp
                  (ands ['(Eq Exp S (Exp.tSig rr AA BB)) (s= '(Sk.prod (skel AA) (skel BB)))
                         (sj 'Bool.true 'G0 'S 'Sk.unit) (sj 'Bool.false 'G0 'a '(skel AA)) (sj 'Bool.false 'G0 'b '(skel BB))]))))])
    'letp (ands [WF (s= '(skel C)) (ex 's1 'Sk (ex 's2 'Sk
                  (ands [(sj 'Bool.true 'G0 'C 'Sk.unit) (sj 'Bool.false 'G0 'p '(Sk.prod s1 s2))
                         (sj 'Bool.false '(sk2 s2 s1 G0) 't '(skel C))])))])
    'chk (ands [WF (s= 'Sk.bool) (sj 'Bool.false 'G0 'c 'Sk.syn) (sj 'Bool.false 'G0 'd 'Sk.syn)])
    'h1 (ands [WF (s= 'Sk.unit) (sj 'Bool.false 'G0 'r 'Sk.cert) (sj 'Bool.false 'G0 's 'Sk.cert) (sj 'Bool.false 'G0 'c 'Sk.syn)
               (sj 'Bool.false 'G0 'e1 'Sk.unit) (sj 'Bool.false 'G0 'e2 'Sk.unit)])
    'refl (ands [WF (s= '(skel D)) (sj 'Bool.true 'G0 'D 'Sk.unit) '(Eq Bool (isBaseTy D) Bool.true)
                 (sj 'Bool.false 'G0 'r 'Sk.cert) (sj 'Bool.false 'G0 'e 'Sk.unit)])
    'insp (ands [WF (s= '(skel X)) (sj 'Bool.true 'G0 'X 'Sk.unit) (sj 'Bool.false 'G0 'r 'Sk.cert) (sj 'Bool.false 'G0 'c 'Sk.syn)
                 (sj 'Bool.false '(sk2 Sk.unit Sk.cert G0) 't1 '(skel X)) (sj 'Bool.false '(sk2 Sk.unit Sk.cert G0) 't2 '(skel X))])
    'tBrs 'False}))

;; InvSkJ by Exp.rec into Prop-valued clauses (the recursive results are
;; unused).
(eval
 (list 'kdef 'InvSkJ '(=> Bool (List Sk) Exp Sk Prop)
       (list 'fn '[w0 :- Bool, G0 :- (List Sk), e0 :- Exp, s0 :- Sk]
             (concat (list 'Exp.rec$1 '(fn [_ :- Exp] Prop))
                     (for [[ctor fields] exp-fields]
                       (let [bs (vec (concat (mapcat (fn [[f ty]] [f :- ty]) fields)
                                             (mapcat (fn [[f ty]] (when (= ty 'Exp) [(symbol (str "i_" f)) :- 'Prop])) fields)))]
                         (if (seq bs) (list 'fn bs (inv-clause ctor)) (inv-clause ctor))))
                     ['e0]))))

;; Each SkJ rule: its constructor, conclusion (w, s), the conclusion's
;; constructor fields, and the proof of the clause from the rule's premises
;; (field names as `induction` binds them; A = And.intro, E = Exists.intro).
(def ^:private skj-concl
  (merge
   (zipmap '[wEmpty wUnit wBool wNat wLbl wSyn wDia wR]
           (map (fn [c] [c 'Bool.true 'Sk.unit [] '(A rfl rfl)]) '[tEmpty tUnit tBool tNat tLbl tSyn tDia tR]))
   '{wT [tT Bool.true Sk.unit [b] (A rfl (A rfl hb))]
     wPi [tPi Bool.true Sk.unit [r A B] (A rfl (A rfl (A hA hB)))]
     wSig [tSig Bool.true Sk.unit [r A B] (A rfl (A rfl (A hA hB)))]
     sVar [var Bool.false s [i] (A rfl h)]
     sStar [star Bool.false Sk.unit [] (A rfl rfl)]
     sAbort [abort Bool.false (skel A) [A t] (A rfl (A rfl (A hA ht)))]
     sTT [tt Bool.false Sk.bool [] (A rfl rfl)]
     sFF [ff Bool.false Sk.bool [] (A rfl rfl)]
     sIte [ite Bool.false s [b t e] (A rfl (A hb (A ht he)))]
     sElimB [elimB Bool.false (skel P) [P b t e] (A rfl (A rfl (A hP (A hb (A ht he)))))]
     sZero [zero Bool.false Sk.nat [] (A rfl rfl)]
     sSucc [succ Bool.false Sk.nat [n] (A rfl (A rfl h))]
     sRecN [recN Bool.false (skel P) [P z st n] (A rfl (A rfl (A hP (A hz (A hs hn)))))]
     sLbl [lbl Bool.false Sk.lbl [l] (A rfl rfl)]
     sCaseL [caseL Bool.false (skel P) [P x bs] (A rfl (A rfl (A hP (A hx hb))))]
     sBnil [bnil Bool.false (Sk.arr Sk.lbl s) [] (A rfl (E s rfl))]
     sBcons [bcons Bool.false (Sk.arr Sk.lbl s) [h t] (A rfl (E s (A rfl (A hh ht))))]
     sSleaf [sleaf Bool.false Sk.syn [x] (A rfl (A rfl h))]
     sSnode [snode Bool.false Sk.syn [x c1 c2] (A rfl (A rfl (A hx (A h1 h2))))]
     sRecS [recS Bool.false (skel P) [P tl tn c] (A rfl (A rfl (A hP (A hl (A hn hc)))))]
     sLeaf [leaf Bool.false Sk.cert [x] (A rfl (A rfl h))]
     sNode [node Bool.false Sk.cert [d x r1 r2] (A rfl (A rfl (A hd (A hx (A h1 h2)))))]
     sItR [itR Bool.false (skel X) [X g h r] (A rfl (A rfl (A hX (A hg (A hh hr)))))]
     sPrn [prn Bool.false Sk.syn [r] (A rfl (A rfl h))]
     sLam [lam Bool.false (Sk.arr (skel A) s) [r A t] (A rfl (E s (A rfl (A hA ht))))]
     sApp [app Bool.false t [f u] (A rfl (E s (A hf hu)))]
     sPair [pair Bool.false (Sk.prod (skel A) (skel B)) [(Exp.tSig r A B) x y] (A rfl (E r (E A (E B (A rfl (A rfl (A hS (A hx hy))))))))]
     sLetp [letp Bool.false (skel C) [C p t] (A rfl (A rfl (E s1 (E s2 (A hC (A hp ht))))))]
     sChk [chk Bool.false Sk.bool [c d] (A rfl (A rfl (A hc hd)))]
     sH1 [h1 Bool.false Sk.unit [r s c e1 e2] (A rfl (A rfl (A hr (A hs (A hc (A h1 h2))))))]
     sRefl [refl Bool.false (skel D) [D r e] (A rfl (A rfl (A hD (A hb (A hr he)))))]
     sInsp [insp Bool.false (skel X) [X r c t1 t2] (A rfl (A rfl (A hX (A hr (A hc (A h1 h2))))))]}))

(def ^:private field-names (into {} (for [[c fs] exp-fields] [c (mapv first fs)])))

;; The clause of `ctor` at w, G, s and the given field values.
(defn- clause-at [ctor w G s vals]
  (walk/postwalk-replace (merge {'w0 w 'G0 G 's0 s} (zipmap (field-names ctor) vals)) (inv-clause ctor)))

;; A proof term: A/E expanded along the clause's shape (Exists.intro is
;; given its predicate explicitly, read off the clause).
(defn- build [pf clause]
  (cond
    (and (seq? pf) (= 'A (first pf)))
    (list 'And.intro (build (second pf) (second clause)) (build (nth pf 2) (nth clause 2)))
    (and (seq? pf) (= 'E (first pf)))
    (let [[_ [_ [v _ ty] body]] clause
          w (second pf)]
      (list 'AT_Exists.intro ty (list 'fn [v ':- ty] body) w
            (build (nth pf 2) (walk/postwalk-replace {v w} body))))
    :else pf))

(defn- inv-case [rule]
  (let [[ctor w s vals pf] (skj-concl rule)
        cl (clause-at ctor w 'G s vals)]
    [(list 'change cl) (list 'exact (build pf cl))]))

;; (skj_inv: the standard constant is used)

;; inv_<ctor> w G fields… sk hj : the clause, spelled out (by skj_inv; the
;; kernel unfolds InvSkJ at the constructor).
(defn- ctor-term [ctor vals] (if (seq vals) (apply list (symbol (str "Exp." ctor)) vals) (symbol (str "Exp." ctor))))

(doseq [[ctor fields] exp-fields :when (not= ctor 'tBrs)]
  (let [fs (map first fields)
        e (ctor-term ctor fs)]
    (a/prove-theorem (symbol (str "inv_" ctor))
      (lv (vec (concat '[w :- Bool, G :- (List Sk)] (mapcat (fn [[f ty]] [f :- ty]) fields)
                       ['sk :- 'Sk 'hj :- (list 'SkJ 'w 'G e 'sk)])))
      (lv (clause-at ctor 'w 'G 'sk fs))
      (lv [(list 'exact (list 'skj_inv 'w 'G e 'sk 'hj))]))))

;; ===========================================================================
;; §3  Equivalence at a position; head steps
;; ===========================================================================

(kdef EquivAt_ri
  (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code) ri RInt]
    (=> Nat Bool (List Sk) Sk Exp Exp Prop))))
  (fn [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt,
       n :- Nat, w :- Bool, G :- (List Sk), s :- Sk, a :- Exp, b :- Exp]
    (And (=> (Eq Bool w Bool.false)
             (And (forall [en (HEnv G)] (Eq (Car s) (den_ri chkf dec encTy ri n a G s en) (den_ri chkf dec encTy ri n b G s en)))
                  (Eq (Option Sk) (skOf G a) (skOf G b))))
         (=> (Eq Bool w Bool.true)
             (And (Eq Sk (skel a) (skel b))
                  (forall [en (HEnv G)] (forall [k Nat] (forall [v (Car (skel b))]
                    (Eq Prop (V_ri chkf dec encTy ri n a G en k (skel b) v) (V_ri chkf dec encTy ri n b G en k (skel b) v))))))))))

(def ^:private P4 '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat])
(defn- dn [e G s en] (list 'den_ri 'chkf 'dec 'encTy 'ri 'n e G s en))
(defn- Vn [A G en k s v] (list 'V_ri 'chkf 'dec 'encTy 'ri 'n A G en k s v))
(defn- EQ [w G s a b] (list 'EquivAt_ri 'chkf 'dec 'encTy 'ri 'n w G s a b))
(defmacro ^:private pthm [nm params prop & tactics]
  `(a/prove-theorem '~nm (lv (into P4 '~params)) (lv '~prop) (lv '~(vec tactics))))

;; Building and reading EquivAt.
(pthm mk_eqv_t_ri [w :- Bool, G :- (List Sk), s :- Sk, a :- Exp, b :- Exp, hw :- (Eq Bool w Bool.false),
                hd :- (forall [en (HEnv G)] (Eq (Car s) (den_ri chkf dec encTy ri n a G s en) (den_ri chkf dec encTy ri n b G s en))),
                hk :- (Eq (Option Sk) (skOf G a) (skOf G b))]
  (EquivAt_ri chkf dec encTy ri n w G s a b)
  (subst hw)
  (unfold EquivAt_ri)
  (apply And.intro)
  (intro hf)
  (exact (And.intro hd hk))
  (intro ht)
  (exact (Bool.noConfusion ht)))

(pthm mk_eqv_ty_ri [w :- Bool, G :- (List Sk), s :- Sk, a :- Exp, b :- Exp, hw :- (Eq Bool w Bool.true),
                 hs :- (Eq Sk (skel a) (skel b)),
                 hv :- (forall [en (HEnv G)] (forall [k Nat] (forall [v (Car (skel b))]
                         (Eq Prop (V_ri chkf dec encTy ri n a G en k (skel b) v) (V_ri chkf dec encTy ri n b G en k (skel b) v)))))]
  (EquivAt_ri chkf dec encTy ri n w G s a b)
  (subst hw)
  (unfold EquivAt_ri)
  (apply And.intro)
  (intro hf)
  (exact (Bool.noConfusion hf))
  (intro ht)
  (exact (And.intro hs hv)))

(pthm eqv_den_ri [G :- (List Sk), s :- Sk, a :- Exp, b :- Exp, h :- (EquivAt_ri chkf dec encTy ri n Bool.false G s a b), en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n a G s en) (den_ri chkf dec encTy ri n b G s en))
  (unfold EquivAt_ri at h)
  (exact (And.left ((And.left h) rfl) en)))

(pthm eqv_sko_ri [G :- (List Sk), s :- Sk, a :- Exp, b :- Exp, h :- (EquivAt_ri chkf dec encTy ri n Bool.false G s a b)]
  (Eq (Option Sk) (skOf G a) (skOf G b))
  (unfold EquivAt_ri at h)
  (exact (And.right ((And.left h) rfl))))

(pthm eqv_skel_ri [G :- (List Sk), s :- Sk, a :- Exp, b :- Exp, h :- (EquivAt_ri chkf dec encTy ri n Bool.true G s a b)]
  (Eq Sk (skel a) (skel b))
  (unfold EquivAt_ri at h)
  (exact (And.left ((And.right h) rfl))))

(pthm eqv_V_ri [G :- (List Sk), s :- Sk, a :- Exp, b :- Exp, h :- (EquivAt_ri chkf dec encTy ri n Bool.true G s a b),
             en :- (HEnv G), k :- Nat, v :- (Car (skel b))]
  (Eq Prop (V_ri chkf dec encTy ri n a G en k (skel b) v) (V_ri chkf dec encTy ri n b G en k (skel b) v))
  (unfold EquivAt_ri at h)
  (exact (And.right ((And.right h) rfl) en k v)))

;; --- ι steps that select a branch (Lemma 3.2; no nbr hypothesis) -----------
;;
;; skOf of ite follows the then-branch, ignoring the scrutinee (carrier.clj).
;; So ite tt t e and t agree on skOf by computation.  ite ff agrees with the
;; else-branch only once both branches have the same skOf (both typed at s
;; and nbr, via skOf_ok); that packaging is not here yet.  elimB and recN
;; report skel of the motive, which need not be skOf of the selected branch.

;; Lemma 3.2 for Hd.iteT, packaged as EquivAt.  inv_ite gives w = false, so
;; the type side of EquivAt is vacuous.  The last rewrite closes both the
;; denotation (Bool.rec at tt) and skOf (definitional).  Do not add a trailing
;; rfl: rw already closes by reflexivity, and a further rfl aborts the proof.
(pthm hd_iteT_ri [t :- Exp, e :- Exp, w :- Bool, G :- (List Sk), s :- Sk, hj :- (SkJ w G (Exp.ite Exp.tt t e) s)]
  (EquivAt_ri chkf dec encTy ri n w G s t (Exp.ite Exp.tt t e))
  (apply mk_eqv_t_ri)
  (exact (And.left (inv_ite w G Exp.tt t e s hj)))
  (intro en)
  (rw [(den_ite_at_ri chkf dec encTy ri n Exp.tt t e G s en)])
  (change (Eq (Car s) (den_ri chkf dec encTy ri n t G s en)
              (Bool.rec$1 (fn [_ :- Bool] (Car s)) (den_ri chkf dec encTy ri n e G s en) (den_ri chkf dec encTy ri n t G s en)
                          (den_ri chkf dec encTy ri n Exp.tt G Sk.bool en))))
  (rw [(den_tt_bool_ri chkf dec encTy ri n G en)]))

;; (skof_ite: the standard constant is used)

;; ⟦ite tt t e⟧ = ⟦t⟧.  Bool.rec's arguments are else, then, scrutinee.
(thm den_iteT_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
               t :- Exp, e :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n t G s en) (den_ri chkf dec encTy ri n (Exp.ite Exp.tt t e) G s en))
  (rw [(den_ite_at_ri chkf dec encTy ri n Exp.tt t e G s en)])
  (change (Eq (Car s) (den_ri chkf dec encTy ri n t G s en)
              (Bool.rec$1 (fn [_ :- Bool] (Car s)) (den_ri chkf dec encTy ri n e G s en) (den_ri chkf dec encTy ri n t G s en)
                          (den_ri chkf dec encTy ri n Exp.tt G Sk.bool en))))
  (rw [(den_tt_bool_ri chkf dec encTy ri n G en)]))

(thm den_iteF_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
               t :- Exp, e :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n e G s en) (den_ri chkf dec encTy ri n (Exp.ite Exp.ff t e) G s en))
  (rw [(den_ite_at_ri chkf dec encTy ri n Exp.ff t e G s en)])
  (change (Eq (Car s) (den_ri chkf dec encTy ri n e G s en)
              (Bool.rec$1 (fn [_ :- Bool] (Car s)) (den_ri chkf dec encTy ri n e G s en) (den_ri chkf dec encTy ri n t G s en)
                          (den_ri chkf dec encTy ri n Exp.ff G Sk.bool en))))
  (rw [(den_ff_bool_ri chkf dec encTy ri n G en)]))

(thm den_elimT_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                P :- Exp, t :- Exp, e :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n t G s en) (den_ri chkf dec encTy ri n (Exp.elimB P Exp.tt t e) G s en))
  (rw [(den_elimB_at_ri chkf dec encTy ri n P Exp.tt t e G s en)])
  (change (Eq (Car s) (den_ri chkf dec encTy ri n t G s en)
              (Bool.rec$1 (fn [_ :- Bool] (Car s)) (den_ri chkf dec encTy ri n e G s en) (den_ri chkf dec encTy ri n t G s en)
                          (den_ri chkf dec encTy ri n Exp.tt G Sk.bool en))))
  (rw [(den_tt_bool_ri chkf dec encTy ri n G en)]))

(thm den_elimF_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                P :- Exp, t :- Exp, e :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n e G s en) (den_ri chkf dec encTy ri n (Exp.elimB P Exp.ff t e) G s en))
  (rw [(den_elimB_at_ri chkf dec encTy ri n P Exp.ff t e G s en)])
  (change (Eq (Car s) (den_ri chkf dec encTy ri n e G s en)
              (Bool.rec$1 (fn [_ :- Bool] (Car s)) (den_ri chkf dec encTy ri n e G s en) (den_ri chkf dec encTy ri n t G s en)
                          (den_ri chkf dec encTy ri n Exp.ff G Sk.bool en))))
  (rw [(den_ff_bool_ri chkf dec encTy ri n G en)]))

;; ⟦recN P z st zero⟧ = ⟦z⟧.  Nat.rec at zero is the base; den_zero_at
;; reduces the scrutinee and closes the goal by computation.
(thm den_recNZ_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                P :- Exp, z :- Exp, st :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n z G s en) (den_ri chkf dec encTy ri n (Exp.recN P z st Exp.zero) G s en))
  (rw [(den_recN_at_ri chkf dec encTy ri n P z st Exp.zero G s en)])
  (change (Eq (Car s) (den_ri chkf dec encTy ri n z G s en)
              (Nat.rec$1 (fn [_ :- Nat] (Car s)) (den_ri chkf dec encTy ri n z G s en)
                (fn [k :- Nat, acc :- (Car s)] (den_ri chkf dec encTy ri n st (sk2 s Sk.nat G) s (Prod.mk acc (Prod.mk k en))))
                (den_ri chkf dec encTy ri n Exp.zero G Sk.nat en))))
  (rw [(den_zero_at_ri chkf dec encTy ri n G Sk.nat en)]))

;; Print.  ⟦prn (leaf x)⟧ = ⟦sleaf x⟧ and ⟦prn (node d x r1 r2)⟧ =
;; ⟦snode x (prn r1) (prn r2)⟧.  The node token d is not in the code.
(thm den_prnL_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
               x :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n (Exp.sleaf x) G s en) (den_ri chkf dec encTy ri n (Exp.prn (Exp.leaf x)) G s en))
  (rw [(den_prn_at_ri chkf dec encTy ri n (Exp.leaf x) G s en)])
  (rw [(den_sleaf_at_ri chkf dec encTy ri n x G s en)])
  (change (Eq (Car s)
              (coe Sk.syn s (Code.sl (den_ri chkf dec encTy ri n x G Sk.lbl en)))
              (coe Sk.syn s (riPr ri (den_ri chkf dec encTy ri n (Exp.leaf x) G Sk.cert en)))))
  (rw [(den_leaf_at_ri chkf dec encTy ri n x G Sk.cert en)])
  ;; RI: print (leaf x) is sl x by L1
  (exact (congrArg (fn [c :- Code] (coe Sk.syn s c)) (Eq.symm (ri_leaf ri (den_ri chkf dec encTy ri n x G Sk.lbl en))))))

(thm den_prnN_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
               d :- Exp, x :- Exp, r1 :- Exp, r2 :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s)
      (den_ri chkf dec encTy ri n (Exp.snode x (Exp.prn r1) (Exp.prn r2)) G s en)
      (den_ri chkf dec encTy ri n (Exp.prn (Exp.node d x r1 r2)) G s en))
  (rw [(den_prn_at_ri chkf dec encTy ri n (Exp.node d x r1 r2) G s en)])
  (rw [(den_snode_at_ri chkf dec encTy ri n x (Exp.prn r1) (Exp.prn r2) G s en)])
  (change (Eq (Car s)
              (coe Sk.syn s (Code.sn (den_ri chkf dec encTy ri n x G Sk.lbl en)
                                     (den_ri chkf dec encTy ri n (Exp.prn r1) G Sk.syn en)
                                     (den_ri chkf dec encTy ri n (Exp.prn r2) G Sk.syn en)))
              (coe Sk.syn s (riPr ri (den_ri chkf dec encTy ri n (Exp.node d x r1 r2) G Sk.cert en)))))
  (rw [(den_node_at_ri chkf dec encTy ri n d x r1 r2 G Sk.cert en)])
  (rw [(den_prn_at_ri chkf dec encTy ri n r1 G Sk.syn en)])
  (rw [(den_prn_at_ri chkf dec encTy ri n r2 G Sk.syn en)])
  ;; RI: print of a node is the node of the prints, by L2
  (exact (congrArg (fn [c :- Code] (coe Sk.syn s c))
           (Eq.symm (ri_node ri (den_ri chkf dec encTy ri n x G Sk.lbl en) (den_ri chkf dec encTy ri n r1 G Sk.cert en) (den_ri chkf dec encTy ri n r2 G Sk.cert en))))))

;; boolExp b denotes the Boolean b, coerced into the skeleton s.  cases on
;; Bool focuses the false goal first (do not trust (peek)'s numbering).
(thm den_boolExp_ff_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                     G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n (boolExp Bool.false) G s en) (coe Sk.bool s Bool.false))
  (rw [(den_ff_at_ri chkf dec encTy ri n G s en)]))

(thm den_boolExp_tt_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                     G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n (boolExp Bool.true) G s en) (coe Sk.bool s Bool.true))
  (rw [(den_tt_at_ri chkf dec encTy ri n G s en)]))

(thm den_boolExp_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                  b :- Bool, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n (boolExp b) G s en) (coe Sk.bool s b))
  (cases b)
  (exact (den_boolExp_ff_ri chkf dec encTy ri n G s en))
  (exact (den_boolExp_tt_ri chkf dec encTy ri n G s en)))

;; --- δ's coding of canonical syntax (partial) --------------------------------
;; codeOf succeeds only for sleaf (lbl l) and snode of the same (skel.clj).
;; none ≠ some for Code; cases on that equation is accepted by the kernel
;; (unlike Option in general, which needs some_inj / none_ne_someE).
;; Named code_none_ne_some: derivations.clj already declares none_ne_someC,
;; and the suite loads these namespaces in either order.

;; (code_none_ne_some: the standard constant is used)

;; ⟦sleaf (lbl l)⟧ at Syn is the leaf code Code.sl l.
(thm den_sleaf_code_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                     l :- Nat, G :- (List Sk), en :- (HEnv G)]
  (Eq Code (den_ri chkf dec encTy ri n (Exp.sleaf (Exp.lbl l)) G Sk.syn en) (Code.sl l))
  (rw [(den_sleaf_at_ri chkf dec encTy ri n (Exp.lbl l) G Sk.syn en)])
  (change (Eq Code (coe Sk.syn Sk.syn (Code.sl (den_ri chkf dec encTy ri n (Exp.lbl l) G Sk.lbl en))) (Code.sl l)))
  (rw [(den_lbl_at_ri chkf dec encTy ri n l G Sk.lbl en)]))

;; codeOf (sleaf x) = some c0 ⇒ x is a label and c0 is its leaf code.
;; One False.elim per non-label constructor: first/exact would accept the
;; eliminator on the label goal and the kernel would then reject the theorem.
(let [ctors (mapv first exp-fields)
      idx (.indexOf ctors 'lbl)
      n (count ctors)
      refute '(exact (False.elim$0 (code_none_ne_some c0 hc)))
      lbl ['(have he (Eq Code (Code.sl l) c0) (Option.some.inj hc))
           '(apply Exists.intro)
           '(exact l)
           '(exact (And.intro (Eq.refl$1 (Exp.lbl l)) (Eq.symm he)))]
      tacs (vec (concat ['(cases x)] (repeat idx refute) lbl (repeat (- n idx 1) refute)))]
  (when (neg? idx) (throw (ex-info "lbl is not an Exp constructor" {})))
  (a/prove-theorem 'codeOf_sleaf_inv
    (lv '[x :- Exp, c0 :- Code, hc :- (Eq (Option Code) (codeOf (Exp.sleaf x)) (Option.some Code c0))])
    (lv '(Exists (fn [l :- Nat] (And (Eq Exp x (Exp.lbl l)) (Eq Code c0 (Code.sl l))))))
    (lv tacs)))

;; --- β (Lemma 3.2), under nbr ------------------------------------------------
;; Arrow injectivity.  cases on an equality of arrows is accepted (the
;; some/none pitfall is special to Option).
;; (arr_inj: the standard constant is used)

;; Exists-elimination for a skeleton witness.  The motive is the predicate
;; P; the witness and its proof are the fields cases binds (w and h).
;; (exSk: the standard constant is used)

;; ⟦λ(r:A). t⟧ at Arr (skel A) sb, applied to v, is ⟦t⟧ at (v, η).
;; One unfolding of den_lam; arrCase at an arrow reduces to the body.
(thm den_lam_arr_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                  r :- U, A :- Exp, t :- Exp, G :- (List Sk), sb :- Sk, en :- (HEnv G), v :- (Car (skel A))]
  (Eq (Car sb) ((den_ri chkf dec encTy ri n (Exp.lam r A t) G (Sk.arr (skel A) sb) en) v)
               (den_ri chkf dec encTy ri n t (List.cons Sk (skel A) G) sb (Prod.mk v en)))
  (rw [(den_lam_at_ri chkf dec encTy ri n r A t G (Sk.arr (skel A) sb) en)]))

;; The unpacked β equation.  harr identifies the application skeleton with
;; the λ skeleton; ht types the body in (skel A :: G); hu types the argument
;; at the domain; hn is nbr of the redex, which gives skOf of the argument
;; via skOf_ok (a branch list in argument position is exactly what hn rules
;; out — see conv_skj_counterexample).
(thm den_beta_core_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                    r :- U, A :- Exp, t :- Exp, u :- Exp, G :- (List Sk), s :- Sk, s1 :- Sk, sb :- Sk,
                    harr :- (Eq Sk (Sk.arr s1 s) (Sk.arr (skel A) sb)),
                    ht :- (SkJ Bool.false (List.cons Sk (skel A) G) t sb),
                    hu :- (SkJ Bool.false G u s1),
                    hn :- (Eq Bool (nbr (Exp.app (Exp.lam r A t) u)) Bool.true),
                    en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n (subst1 u t) G s en) (den_ri chkf dec encTy ri n (Exp.app (Exp.lam r A t) u) G s en))
  (have hai (And (Eq Sk s1 (skel A)) (Eq Sk s sb)) (arr_inj s1 s (skel A) sb harr))
  (have h1 (Eq Sk s1 (skel A)) (And.left hai))
  (have h2 (Eq Sk s sb) (And.right hai))
  (have hnu (Eq Bool ((nbrF u) false) Bool.true)
        (band_right ((nbrF (Exp.lam r A t)) false) ((nbrF u) false) hn))
  (have hku (Eq (Option Sk) (skOf G u) (Option.some Sk s1)) (skOf_ok G u s1 hu hnu))
  (subst h1)
  (subst h2)
  (rw [(den_app_some_ri chkf dec encTy ri n (Exp.lam r A t) u G (skel A) sb en hku)])
  (rw [(den_lam_arr_ri chkf dec encTy ri n r A t G sb en (den_ri chkf dec encTy ri n u G (skel A) en))])
  (exact (den_subst1_ri chkf dec encTy ri n Bool.false G (skel A) t sb ht u hu hku en)))

;; Lemma 3.2 for Hd.beta, under nbr of the redex.  Inversion of the
;; application and of the λ supply the skeletons den_beta_core needs.
(thm den_beta_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
               r :- U, A :- Exp, t :- Exp, u :- Exp, G :- (List Sk), s :- Sk,
               hj :- (SkJ Bool.false G (Exp.app (Exp.lam r A t) u) s),
               hn :- (Eq Bool (nbr (Exp.app (Exp.lam r A t) u)) Bool.true),
               en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n (subst1 u t) G s en) (den_ri chkf dec encTy ri n (Exp.app (Exp.lam r A t) u) G s en))
  (have happ (And (Eq Bool Bool.false Bool.false)
                  (Exists (fn [s1 :- Sk]
                    (And (SkJ Bool.false G (Exp.lam r A t) (Sk.arr s1 s))
                         (SkJ Bool.false G u s1)))))
        (inv_app Bool.false G (Exp.lam r A t) u s hj))
  (exact (exSk (fn [s1 :- Sk] (And (SkJ Bool.false G (Exp.lam r A t) (Sk.arr s1 s)) (SkJ Bool.false G u s1)))
               (Eq (Car s) (den_ri chkf dec encTy ri n (subst1 u t) G s en) (den_ri chkf dec encTy ri n (Exp.app (Exp.lam r A t) u) G s en))
               (And.right happ)
               (fn [s1 :- Sk, hs1 :- (And (SkJ Bool.false G (Exp.lam r A t) (Sk.arr s1 s)) (SkJ Bool.false G u s1))]
                 (exSk (fn [sb :- Sk] (And (Eq Sk (Sk.arr s1 s) (Sk.arr (skel A) sb))
                                           (And (SkJ Bool.true G A Sk.unit)
                                                (SkJ Bool.false (List.cons Sk (skel A) G) t sb))))
                       (Eq (Car s) (den_ri chkf dec encTy ri n (subst1 u t) G s en) (den_ri chkf dec encTy ri n (Exp.app (Exp.lam r A t) u) G s en))
                       (And.right (inv_lam Bool.false G r A t (Sk.arr s1 s) (And.left hs1)))
                       (fn [sb :- Sk, hsb :- (And (Eq Sk (Sk.arr s1 s) (Sk.arr (skel A) sb))
                                                  (And (SkJ Bool.true G A Sk.unit)
                                                       (SkJ Bool.false (List.cons Sk (skel A) G) t sb)))]
                         (den_beta_core_ri chkf dec encTy ri n r A t u G s s1 sb
                           (And.left hsb) (And.right (And.right hsb)) (And.right hs1) hn en)))))))

;; --- the failure of β over SkJ alone -----------------------------------------
;;
;; redex     = (λ(y : Π(l:Lbl).Bool). caseL Bool 0 y) (bcons tt bnil)
;; contractum = caseL Bool 0 (bcons tt bnil)
;;             = subst1 (bcons tt bnil) (caseL Bool 0 (var 0))
;;
;; Both the redex and the step are well-formed (SkJ at Bool, Hd.beta), but
;; nbr of the redex is false: the branch list stands in argument position.
;; ⟦redex⟧ at Bool is ff (den_app defaults when skOf of the argument is none)
;; and ⟦contractum⟧ is tt (caseL computes).  This is why den_beta assumes nbr.
;; Wrapping either side in T makes V differ (V(T tt) is inhabited, V(T ff)
;; is empty). Cv now excludes this redex by requiring nbr of every element.

;; (cex_red_eq: the standard constant is used)

(thm cex_den_redex_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt]
  (Eq Bool (den_ri chkf dec encTy ri 0
                (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tBool) (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.var 0)))
                         (Exp.bcons Exp.tt Exp.bnil))
                (List.nil Sk) Sk.bool Unit.unit)
          Bool.false)
  (rfl))

(thm cex_den_contr_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt]
  (Eq Bool (den_ri chkf dec encTy ri 0
                (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.bcons Exp.tt Exp.bnil))
                (List.nil Sk) Sk.bool Unit.unit)
          Bool.true)
  (rfl))

;; (cex_nbr_ff: the standard constant is used)

;; (cex_redex_typed: the standard constant is used)

(thm cex_den_ne_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt]
  (Not (Eq Bool
           (den_ri chkf dec encTy ri 0
                (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tBool) (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.var 0)))
                         (Exp.bcons Exp.tt Exp.bnil))
                (List.nil Sk) Sk.bool Unit.unit)
           (den_ri chkf dec encTy ri 0
                (subst1 (Exp.bcons Exp.tt Exp.bnil) (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.var 0)))
                (List.nil Sk) Sk.bool Unit.unit)))
  (intro heq)
  (exact (Bool.noConfusion
           (Eq.trans (Eq.symm (cex_den_redex_ri chkf dec encTy ri))
             (Eq.trans heq
               (Eq.trans
                 (congrArg (fn [e :- Exp] (den_ri chkf dec encTy ri 0 e (List.nil Sk) Sk.bool Unit.unit)) cex_red_eq)
                 (cex_den_contr_ri chkf dec encTy ri)))))))

;; The counterexample, as one statement: a head β step, the redex
;; skeleton-typed at Bool, nbr false, and the two denotations unequal.
(thm conv_skj_counterexample_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt]
  (And (Hd chkf
           (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tBool) (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.var 0)))
                    (Exp.bcons Exp.tt Exp.bnil))
           (subst1 (Exp.bcons Exp.tt Exp.bnil) (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.var 0))))
       (And (SkJ Bool.false (List.nil Sk)
                 (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tBool) (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.var 0)))
                          (Exp.bcons Exp.tt Exp.bnil))
                 Sk.bool)
            (And (Eq Bool (nbr (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tBool) (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.var 0)))
                                        (Exp.bcons Exp.tt Exp.bnil)))
                     Bool.false)
                 (Not (Eq Bool
                          (den_ri chkf dec encTy ri 0
                               (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tBool) (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.var 0)))
                                        (Exp.bcons Exp.tt Exp.bnil))
                               (List.nil Sk) Sk.bool Unit.unit)
                          (den_ri chkf dec encTy ri 0
                               (subst1 (Exp.bcons Exp.tt Exp.bnil) (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.var 0)))
                               (List.nil Sk) Sk.bool Unit.unit))))))
  (exact (And.intro (Hd.beta chkf U.uw (Exp.tPi U.uw Exp.tLbl Exp.tBool) (Exp.caseL Exp.tBool (Exp.lbl 0) (Exp.var 0)) (Exp.bcons Exp.tt Exp.bnil))
                    (And.intro cex_redex_typed (And.intro cex_nbr_ff (cex_den_ne_ri chkf dec encTy ri))))))

;; --- β for let (Lemma 3.2), under nbr ---------------------------------------
;; Hd.betaLet sends letp C (pair S x y) t to substL [y, x] t.  skOf of a pair
;; is some (skel S), read off the type annotation, so the let's denotation
;; splits the pair rather than defaulting — provided the pair is not a branch
;; list, which nbr of the redex gives for x and y (den_substL2 needs their
;; skOf).  The environment order is the let's: (⟦y⟧, ⟦x⟧, η).

;; (prod_inj: the standard constant is used)

;; (exU: the standard constant is used)

;; exExpC, not exExp: derivations.clj declares exExp for the same elimination.
;; (exExpC: the standard constant is used)

;; (skof_pair: the standard constant is used)

;; ⟦pair S x y⟧ at a product skeleton is the pair of the components' denotations.
(thm den_pair_prod_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                    S :- Exp, x :- Exp, y :- Exp, G :- (List Sk), sa :- Sk, sb :- Sk, en :- (HEnv G)]
  (Eq (Prod (Car sa) (Car sb))
      (den_ri chkf dec encTy ri n (Exp.pair S x y) G (Sk.prod sa sb) en)
      (Prod.mk (den_ri chkf dec encTy ri n x G sa en) (den_ri chkf dec encTy ri n y G sb en)))
  (rw [(den_pair_at_ri chkf dec encTy ri n S x y G (Sk.prod sa sb) en)]))

(lcert.formal.base/thm den_betaLet_at_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  C :- Exp, S :- Exp, x :- Exp, y :- Exp, t :- Exp, G :- (List Sk), s :- Sk, s1 :- Sk, s2 :- Sk,
  rr :- U, AA :- Exp, BB :- Exp,
  hs :- (Eq Sk s (skel C)),
  hp :- (SkJ Bool.false G (Exp.pair S x y) (Sk.prod s1 s2)),
  ht :- (SkJ Bool.false (sk2 s2 s1 G) t (skel C)),
  hn :- (Eq Bool (nbr (Exp.letp C (Exp.pair S x y) t)) Bool.true),
  en :- (HEnv G),
  hBB :- (And (Eq Exp S (Exp.tSig rr AA BB))
           (And (Eq Sk (Sk.prod s1 s2) (Sk.prod (skel AA) (skel BB)))
             (And (SkJ Bool.true G S Sk.unit)
               (And (SkJ Bool.false G x (skel AA))
                 (SkJ Bool.false G y (skel BB))))))]
  (Eq (Car s)
      (den_ri chkf dec encTy ri n (substL (List.cons Exp y (List.cons Exp x (List.nil Exp))) t) G s en)
      (den_ri chkf dec encTy ri n (Exp.letp C (Exp.pair S x y) t) G s en))
  (have hS (Eq Exp S (Exp.tSig rr AA BB)) (And.left hBB))
  (have hsk (Eq Sk (Sk.prod s1 s2) (Sk.prod (skel AA) (skel BB))) (And.left (And.right hBB)))
  (have hx (SkJ Bool.false G x (skel AA)) (And.left (And.right (And.right (And.right hBB)))))
  (have hy (SkJ Bool.false G y (skel BB)) (And.right (And.right (And.right (And.right hBB)))))
  (have hpi (And (Eq Sk s1 (skel AA)) (Eq Sk s2 (skel BB))) (prod_inj s1 s2 (skel AA) (skel BB) hsk))
  (have h1 (Eq Sk s1 (skel AA)) (And.left hpi))
  (have h2 (Eq Sk s2 (skel BB)) (And.right hpi))
  (have hrest (Eq Bool (Bool.and ((nbrF (Exp.pair S x y)) false) ((nbrF t) false)) Bool.true)
        (band_right ((nbrF C) false) (Bool.and ((nbrF (Exp.pair S x y)) false) ((nbrF t) false)) hn))
  (have hpn (Eq Bool ((nbrF (Exp.pair S x y)) false) Bool.true)
        (band_left ((nbrF (Exp.pair S x y)) false) ((nbrF t) false) hrest))
  (have hxy (Eq Bool (Bool.and ((nbrF x) false) ((nbrF y) false)) Bool.true)
        (band_right ((nbrF S) false) (Bool.and ((nbrF x) false) ((nbrF y) false)) hpn))
  (have hnx (Eq Bool ((nbrF x) false) Bool.true) (band_left ((nbrF x) false) ((nbrF y) false) hxy))
  (have hny (Eq Bool ((nbrF y) false) Bool.true) (band_right ((nbrF x) false) ((nbrF y) false) hxy))
  (have hkx (Eq (Option Sk) (skOf G x) (Option.some Sk (skel AA))) (skOf_ok G x (skel AA) hx hnx))
  (have hky (Eq (Option Sk) (skOf G y) (Option.some Sk (skel BB))) (skOf_ok G y (skel BB) hy hny))
  (subst h1)
  (subst h2)
  (subst hs)
  (have hkp (Eq (Option Sk) (skOf G (Exp.pair S x y)) (Option.some Sk (Sk.prod (skel AA) (skel BB))))
        (Eq.trans (skof_pair S x y G) (congrArg (fn [E :- Exp] (Option.some Sk (skel E))) hS)))
  (rw [(den_letp_some_ri chkf dec encTy ri n C (Exp.pair S x y) t G (skel AA) (skel BB) (skel C) en hkp)])
  (rw [(den_pair_prod_ri chkf dec encTy ri n S x y G (skel AA) (skel BB) en)])
  (exact (den_substL2_ri chkf dec encTy ri n G x (skel AA) y (skel BB) hx hkx hy hky Bool.false t (skel C) ht en)))

(lcert.formal.base/thm den_betaLet_core_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  C :- Exp, S :- Exp, x :- Exp, y :- Exp, t :- Exp, G :- (List Sk), s :- Sk, s1 :- Sk, s2 :- Sk,
  hs :- (Eq Sk s (skel C)),
  hp :- (SkJ Bool.false G (Exp.pair S x y) (Sk.prod s1 s2)),
  ht :- (SkJ Bool.false (sk2 s2 s1 G) t (skel C)),
  hn :- (Eq Bool (nbr (Exp.letp C (Exp.pair S x y) t)) Bool.true),
  en :- (HEnv G)]
  (Eq (Car s)
      (den_ri chkf dec encTy ri n (substL (List.cons Exp y (List.cons Exp x (List.nil Exp))) t) G s en)
      (den_ri chkf dec encTy ri n (Exp.letp C (Exp.pair S x y) t) G s en))
  (have hpair (And (Eq Bool Bool.false Bool.false)
                   (Exists (fn [rr :- U]
                     (Exists (fn [AA :- Exp]
                       (Exists (fn [BB :- Exp]
                         (And (Eq Exp S (Exp.tSig rr AA BB))
                           (And (Eq Sk (Sk.prod s1 s2) (Sk.prod (skel AA) (skel BB)))
                             (And (SkJ Bool.true G S Sk.unit)
                               (And (SkJ Bool.false G x (skel AA))
                                 (SkJ Bool.false G y (skel BB)))))))))))))
        (inv_pair Bool.false G S x y (Sk.prod s1 s2) hp))
  (exact (exU (fn [rr :- U] (Exists (fn [AA :- Exp] (Exists (fn [BB :- Exp]
                   (And (Eq Exp S (Exp.tSig rr AA BB))
                     (And (Eq Sk (Sk.prod s1 s2) (Sk.prod (skel AA) (skel BB)))
                       (And (SkJ Bool.true G S Sk.unit)
                         (And (SkJ Bool.false G x (skel AA))
                           (SkJ Bool.false G y (skel BB)))))))))))
               (Eq (Car s)
                   (den_ri chkf dec encTy ri n (substL (List.cons Exp y (List.cons Exp x (List.nil Exp))) t) G s en)
                   (den_ri chkf dec encTy ri n (Exp.letp C (Exp.pair S x y) t) G s en))
               (And.right hpair)
               (fn [rr :- U, hrr :- (Exists (fn [AA :- Exp] (Exists (fn [BB :- Exp]
                      (And (Eq Exp S (Exp.tSig rr AA BB))
                        (And (Eq Sk (Sk.prod s1 s2) (Sk.prod (skel AA) (skel BB)))
                          (And (SkJ Bool.true G S Sk.unit)
                            (And (SkJ Bool.false G x (skel AA))
                              (SkJ Bool.false G y (skel BB))))))))))]
                 (exExpC (fn [AA :- Exp] (Exists (fn [BB :- Exp]
                          (And (Eq Exp S (Exp.tSig rr AA BB))
                            (And (Eq Sk (Sk.prod s1 s2) (Sk.prod (skel AA) (skel BB)))
                              (And (SkJ Bool.true G S Sk.unit)
                                (And (SkJ Bool.false G x (skel AA))
                                  (SkJ Bool.false G y (skel BB)))))))))
                       (Eq (Car s)
                           (den_ri chkf dec encTy ri n (substL (List.cons Exp y (List.cons Exp x (List.nil Exp))) t) G s en)
                           (den_ri chkf dec encTy ri n (Exp.letp C (Exp.pair S x y) t) G s en))
                       hrr
                       (fn [AA :- Exp, hAA :- (Exists (fn [BB :- Exp]
                              (And (Eq Exp S (Exp.tSig rr AA BB))
                                (And (Eq Sk (Sk.prod s1 s2) (Sk.prod (skel AA) (skel BB)))
                                  (And (SkJ Bool.true G S Sk.unit)
                                    (And (SkJ Bool.false G x (skel AA))
                                      (SkJ Bool.false G y (skel BB))))))))]
                         (exExpC (fn [BB :- Exp]
                                 (And (Eq Exp S (Exp.tSig rr AA BB))
                                   (And (Eq Sk (Sk.prod s1 s2) (Sk.prod (skel AA) (skel BB)))
                                     (And (SkJ Bool.true G S Sk.unit)
                                       (And (SkJ Bool.false G x (skel AA))
                                         (SkJ Bool.false G y (skel BB)))))))
                               (Eq (Car s)
                                   (den_ri chkf dec encTy ri n (substL (List.cons Exp y (List.cons Exp x (List.nil Exp))) t) G s en)
                                   (den_ri chkf dec encTy ri n (Exp.letp C (Exp.pair S x y) t) G s en))
                               hAA
                               (fn [BB :- Exp, hBB :- (And (Eq Exp S (Exp.tSig rr AA BB))
                                                      (And (Eq Sk (Sk.prod s1 s2) (Sk.prod (skel AA) (skel BB)))
                                                        (And (SkJ Bool.true G S Sk.unit)
                                                          (And (SkJ Bool.false G x (skel AA))
                                                            (SkJ Bool.false G y (skel BB))))))]
                                 (den_betaLet_at_ri chkf dec encTy ri n C S x y t G s s1 s2 rr AA BB hs hp ht hn en hBB)))))))))
(lcert.formal.base/thm den_betaLet_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  C :- Exp, S :- Exp, x :- Exp, y :- Exp, t :- Exp, G :- (List Sk), s :- Sk,
  hj :- (SkJ Bool.false G (Exp.letp C (Exp.pair S x y) t) s),
  hn :- (Eq Bool (nbr (Exp.letp C (Exp.pair S x y) t)) Bool.true),
  en :- (HEnv G)]
  (Eq (Car s)
      (den_ri chkf dec encTy ri n (substL (List.cons Exp y (List.cons Exp x (List.nil Exp))) t) G s en)
      (den_ri chkf dec encTy ri n (Exp.letp C (Exp.pair S x y) t) G s en))
  (have hlet (And (Eq Bool Bool.false Bool.false)
                  (And (Eq Sk s (skel C))
                    (Exists (fn [s1 :- Sk]
                      (Exists (fn [s2 :- Sk]
                        (And (SkJ Bool.true G C Sk.unit)
                          (And (SkJ Bool.false G (Exp.pair S x y) (Sk.prod s1 s2))
                            (SkJ Bool.false (sk2 s2 s1 G) t (skel C))))))))))
        (inv_letp Bool.false G C (Exp.pair S x y) t s hj))
  (have hs (Eq Sk s (skel C)) (And.left (And.right hlet)))
  (exact (exSk (fn [s1 :- Sk] (Exists (fn [s2 :- Sk]
                   (And (SkJ Bool.true G C Sk.unit)
                     (And (SkJ Bool.false G (Exp.pair S x y) (Sk.prod s1 s2))
                       (SkJ Bool.false (sk2 s2 s1 G) t (skel C)))))))
               (Eq (Car s)
                   (den_ri chkf dec encTy ri n (substL (List.cons Exp y (List.cons Exp x (List.nil Exp))) t) G s en)
                   (den_ri chkf dec encTy ri n (Exp.letp C (Exp.pair S x y) t) G s en))
               (And.right (And.right hlet))
               (fn [s1 :- Sk, hs1 :- (Exists (fn [s2 :- Sk]
                      (And (SkJ Bool.true G C Sk.unit)
                        (And (SkJ Bool.false G (Exp.pair S x y) (Sk.prod s1 s2))
                          (SkJ Bool.false (sk2 s2 s1 G) t (skel C))))))]
                 (exSk (fn [s2 :- Sk]
                         (And (SkJ Bool.true G C Sk.unit)
                           (And (SkJ Bool.false G (Exp.pair S x y) (Sk.prod s1 s2))
                             (SkJ Bool.false (sk2 s2 s1 G) t (skel C)))))
                       (Eq (Car s)
                           (den_ri chkf dec encTy ri n (substL (List.cons Exp y (List.cons Exp x (List.nil Exp))) t) G s en)
                           (den_ri chkf dec encTy ri n (Exp.letp C (Exp.pair S x y) t) G s en))
                       hs1
                       (fn [s2 :- Sk, hs2 :- (And (SkJ Bool.true G C Sk.unit)
                                             (And (SkJ Bool.false G (Exp.pair S x y) (Sk.prod s1 s2))
                                               (SkJ Bool.false (sk2 s2 s1 G) t (skel C))))]
                         (den_betaLet_core_ri chkf dec encTy ri n C S x y t G s s1 s2 hs
                           (And.left (And.right hs2)) (And.right (And.right hs2)) hn en)))))))

;; --- itR on a leaf (Lemma 3.2) ----------------------------------------------
;; Hd.itRL sends itR X g h (leaf x) to app g x.  The certificate denotes a
;; leaf code, so the iterator applies g; the application does the same once
;; skOf x = some Lbl (otherwise it defaults).  den_itRL_nbr gets that skOf
;; from skeleton typing of the redex together with nbr, via skOf_ok.

(lcert.formal.base/thm den_itRL_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  X :- Exp, g :- Exp, h :- Exp, x :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G),
  hk :- (Eq (Option Sk) (skOf G x) (Option.some Sk Sk.lbl))]
  (Eq (Car s) (den_ri chkf dec encTy ri n (Exp.app g x) G s en) (den_ri chkf dec encTy ri n (Exp.itR X g h (Exp.leaf x)) G s en))
  (rw [(den_app_some_ri chkf dec encTy ri n g x G Sk.lbl s en hk)])
  (rw [(den_itR_at_ri chkf dec encTy ri n X g h (Exp.leaf x) G s en)])
  (change (Eq (Car s) ((den_ri chkf dec encTy ri n g G (Sk.arr Sk.lbl s) en) (den_ri chkf dec encTy ri n x G Sk.lbl en))
              (Code.rec$1 (fn [_ :- Code] (Car s))
                (fn [l :- Nat] ((den_ri chkf dec encTy ri n g G (Sk.arr Sk.lbl s) en) l))
                (fn [l :- Nat, a :- Code, b :- Code, ya :- (Car s), yb :- (Car s)]
                  ((den_ri chkf dec encTy ri n h G (Sk.arr Sk.dia (Sk.arr Sk.lbl (Sk.arr s (Sk.arr s s)))) en) Unit.unit l ya yb))
                (den_ri chkf dec encTy ri n (Exp.leaf x) G Sk.cert en))))
  (rw [(den_leaf_at_ri chkf dec encTy ri n x G Sk.cert en)])
  ;; RI: itR passes riIt ri (riLf ri x) = x for the tree leaf x builds (L1)
  (exact (congrArg (den_ri chkf dec encTy ri n g G (Sk.arr Sk.lbl s) en) (Eq.symm (ri_itleaf ri (den_ri chkf dec encTy ri n x G Sk.lbl en))))))

(lcert.formal.base/thm den_itRL_nbr_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  X :- Exp, g :- Exp, h :- Exp, x :- Exp, G :- (List Sk), s :- Sk,
  hj :- (SkJ Bool.false G (Exp.itR X g h (Exp.leaf x)) s),
  hn :- (Eq Bool (nbr (Exp.itR X g h (Exp.leaf x))) Bool.true),
  en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n (Exp.app g x) G s en) (den_ri chkf dec encTy ri n (Exp.itR X g h (Exp.leaf x)) G s en))
  (have hit (And (Eq Bool Bool.false Bool.false)
                 (And (Eq Sk s (skel X))
                   (And (SkJ Bool.true G X Sk.unit)
                     (And (SkJ Bool.false G g (Sk.arr Sk.lbl (skel X)))
                       (And (SkJ Bool.false G h (Sk.arr Sk.dia (Sk.arr Sk.lbl (Sk.arr (skel X) (Sk.arr (skel X) (skel X))))))
                         (SkJ Bool.false G (Exp.leaf x) Sk.cert))))))
        (inv_itR Bool.false G X g h (Exp.leaf x) s hj))
  (have hleaf (And (Eq Bool Bool.false Bool.false)
                   (And (Eq Sk Sk.cert Sk.cert)
                     (SkJ Bool.false G x Sk.lbl)))
        (inv_leaf Bool.false G x Sk.cert (And.right (And.right (And.right (And.right (And.right hit)))))))
  (have h1 (Eq Bool (Bool.and ((nbrF g) false) (Bool.and ((nbrF h) false) ((nbrF (Exp.leaf x)) false))) Bool.true)
        (band_right ((nbrF X) false)
                    (Bool.and ((nbrF g) false) (Bool.and ((nbrF h) false) ((nbrF (Exp.leaf x)) false))) hn))
  (have h2 (Eq Bool (Bool.and ((nbrF h) false) ((nbrF (Exp.leaf x)) false)) Bool.true)
        (band_right ((nbrF g) false) (Bool.and ((nbrF h) false) ((nbrF (Exp.leaf x)) false)) h1))
  (have h3 (Eq Bool ((nbrF (Exp.leaf x)) false) Bool.true)
        (band_right ((nbrF h) false) ((nbrF (Exp.leaf x)) false) h2))
  (have hk (Eq (Option Sk) (skOf G x) (Option.some Sk Sk.lbl))
        (skOf_ok G x Sk.lbl (And.right (And.right hleaf)) h3))
  (exact (den_itRL_ri chkf dec encTy ri n X g h x G s en hk)))

;; --- T steps (Lemma 3.3's conversion, at a head step) -----------------------
;; V(T(tt)) = V(1) and V(T(ff)) = V(0).  Both types have skeleton Unit, so
;; EquivAt's type side is the V equation (hd_tTT, hd_tTF).  unfold V exposes
;; the clause; propext identifies (tt = tt) with True and (ff = tt) with False.

(lcert.formal.base/thm V_tTT_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  G :- (List Sk), en :- (HEnv G), k :- Nat, v :- (Car Sk.unit)]
  (Eq Prop (V_ri chkf dec encTy ri n (Exp.tT Exp.tt) G en k Sk.unit v)
          (V_ri chkf dec encTy ri n Exp.tUnit G en k Sk.unit v))
  (unfold V_ri)
  (rw [(den_tt_bool_ri chkf dec encTy ri n G en)])
  (exact (propext (Iff.intro (fn [_ :- (Eq Bool Bool.true Bool.true)] True.intro) (fn [_ :- True] (Eq.refl$1 Bool.true))))))

;; The same equation at skel(T(tt)), which is the skeleton EquivAt quantifies over.
(lcert.formal.base/thm V_tTT_at_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  G :- (List Sk), en :- (HEnv G), k :- Nat, v :- (Car (skel (Exp.tT Exp.tt)))]
  (Eq Prop (V_ri chkf dec encTy ri n Exp.tUnit G en k (skel (Exp.tT Exp.tt)) v)
          (V_ri chkf dec encTy ri n (Exp.tT Exp.tt) G en k (skel (Exp.tT Exp.tt)) v))
  (unfold V_ri)
  (rw [(den_tt_bool_ri chkf dec encTy ri n G en)])
  (exact (propext (Iff.intro (fn [_ :- True] (Eq.refl$1 Bool.true)) (fn [_ :- (Eq Bool Bool.true Bool.true)] True.intro)))))

(lcert.formal.base/thm V_tTF_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  G :- (List Sk), en :- (HEnv G), k :- Nat, v :- (Car Sk.unit)]
  (Eq Prop (V_ri chkf dec encTy ri n (Exp.tT Exp.ff) G en k Sk.unit v)
          (V_ri chkf dec encTy ri n Exp.tEmpty G en k Sk.unit v))
  (unfold V_ri)
  (rw [(den_ff_bool_ri chkf dec encTy ri n G en)])
  (exact (propext (Iff.intro (fn [h :- (Eq Bool Bool.false Bool.true)] (Bool.noConfusion h))
                             (fn [h :- False] (False.elim$0 h))))))

(lcert.formal.base/thm V_tTF_at_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  G :- (List Sk), en :- (HEnv G), k :- Nat, v :- (Car (skel (Exp.tT Exp.ff)))]
  (Eq Prop (V_ri chkf dec encTy ri n Exp.tEmpty G en k (skel (Exp.tT Exp.ff)) v)
          (V_ri chkf dec encTy ri n (Exp.tT Exp.ff) G en k (skel (Exp.tT Exp.ff)) v))
  (unfold V_ri)
  (rw [(den_ff_bool_ri chkf dec encTy ri n G en)])
  (exact (propext (Iff.intro (fn [h :- False] (False.elim$0 h))
                             (fn [h :- (Eq Bool Bool.false Bool.true)] (Bool.noConfusion h))))))
(lcert.formal.base/thm hd_tTT_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  w :- Bool, G :- (List Sk), s :- Sk, hj :- (SkJ w G (Exp.tT Exp.tt) s)]
  (EquivAt_ri chkf dec encTy ri n w G s Exp.tUnit (Exp.tT Exp.tt))
  (exact (mk_eqv_ty_ri chkf dec encTy ri n w G s Exp.tUnit (Exp.tT Exp.tt)
            (And.left (inv_tT w G Exp.tt s hj))
            (Eq.refl$1 Sk.unit)
            (fn [en :- (HEnv G), k :- Nat, v :- (Car (skel (Exp.tT Exp.tt)))]
              (V_tTT_at_ri chkf dec encTy ri n G en k v)))))
(lcert.formal.base/thm hd_tTF_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
  w :- Bool, G :- (List Sk), s :- Sk, hj :- (SkJ w G (Exp.tT Exp.ff) s)]
  (EquivAt_ri chkf dec encTy ri n w G s Exp.tEmpty (Exp.tT Exp.ff))
  (exact (mk_eqv_ty_ri chkf dec encTy ri n w G s Exp.tEmpty (Exp.tT Exp.ff)
            (And.left (inv_tT w G Exp.ff s hj))
            (Eq.refl$1 Sk.unit)
            (fn [en :- (HEnv G), k :- Nat, v :- (Car (skel (Exp.tT Exp.ff)))]
              (V_tTF_at_ri chkf dec encTy ri n G en k v)))))

;; ---------------------------------------------------------------------------
;; §4  The remaining head steps of Lemma 3.2 (R4-metatheory.md §3.2).
;;
;; recNS, recSL and recSN substitute the recursive result (and the
;; predecessor or the node's components) into the step.  den_subst1 /
;; den_substL apply only when each substituted term is skOf-faithful;
;; nbr of the redex supplies that for the components, and the recursive
;; result is faithful by the same skeleton annotation as the redex.
;; caseLb is lookup: the denotation of a branch list is the function
;; nthB reads.  delta reduces chk of two canonical code terms to the
;; boolean chkf returns, because a canonical syntax term denotes the
;; Code that codeOf accepts (den_codeOf), including snode at any depth.
;; itRN applies the node step to the token, the label, and the two
;; recursive results.  The token's carrier is the unit type, so the
;; syntactic token argument and the denotation's Unit.unit are
;; definitionally the same value; the last rewrite closes by rfl.
;; cex_no_cv is the kernel-checked fact that the strengthened Cv refuses
;; the branch-list counterexample at either end of a chain.
;; ---------------------------------------------------------------------------

;; Field projections of nbrF. The flag changes only at caseL.bs and
;; bcons.t. These lemmas keep the folded application in each statement,
;; which is essential for rewriting generated denotation clauses.
(defn- nbr-flag [ctor f]
  (if (or (and (= ctor 'caseL) (= f 'bs)) (and (= ctor 'bcons) (= f 't))) 'true 'false))
(defn- band-chain [xs]
  (if (= 1 (count xs)) (first xs) (list 'Bool.and (first xs) (band-chain (rest xs)))))
(defn- band-project [xs i h]
  (if (= 1 (count xs)) h
    (if (zero? i) (list 'band_left (first xs) (band-chain (rest xs)) h)
      (band-project (rest xs) (dec i) (list 'band_right (first xs) (band-chain (rest xs)) h)))))
(doseq [[ctor fields] exp-fields
        :let [fs (filter #(= 'Exp (second %)) fields)
              es (map (fn [[f]] (list (list 'nbrF f) (nbr-flag ctor f))) fs)
              es (if (= ctor 'bcons) (cons 'fl es) es)
              term (apply list (symbol (str "Exp." ctor)) (map first fields))]
        [idx [f]] (map-indexed vector fs)]
  (a/prove-theorem (symbol (str "nbr_" ctor "_" f))
    (lv (vec (concat (mapcat (fn [[v ty]] [v ':- ty]) fields)
                    ['fl ':- 'Bool 'hn ':- (list 'Eq 'Bool (list (list 'nbrF term) 'fl) 'Bool.true)])))
    (lv (list 'Eq 'Bool (list (list 'nbrF f) (nbr-flag ctor f)) 'Bool.true))
    (lv [(list 'exact (band-project es (+ idx (if (= ctor 'bcons) 1 0)) 'hn))])))

;; Unfolding at a natural successor, before using substitution. This
;; equation itself holds at any output skeleton, without typing premises.
(pthm den_recNS_eval_ri [P :- Exp, z :- Exp, st :- Exp, m :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s)
    (den_ri chkf dec encTy ri n (Exp.recN P z st (Exp.succ m)) G s en)
    (den_ri chkf dec encTy ri n st (sk2 s Sk.nat G) s
      (Prod.mk (den_ri chkf dec encTy ri n (Exp.recN P z st m) G s en)
               (Prod.mk (den_ri chkf dec encTy ri n m G Sk.nat en) en))))
  (rw [(den_recN_at_ri chkf dec encTy ri n P z st (Exp.succ m) G s en)])
  (change (Eq (Car s)
    (Nat.rec$1 (fn [_ :- Nat] (Car s)) (den_ri chkf dec encTy ri n z G s en)
      (fn [j :- Nat, acc :- (Car s)] (den_ri chkf dec encTy ri n st (sk2 s Sk.nat G) s (Prod.mk acc (Prod.mk j en))))
      (den_ri chkf dec encTy ri n (Exp.succ m) G Sk.nat en))
    (den_ri chkf dec encTy ri n st (sk2 s Sk.nat G) s
      (Prod.mk (den_ri chkf dec encTy ri n (Exp.recN P z st m) G s en)
               (Prod.mk (den_ri chkf dec encTy ri n m G Sk.nat en) en)))))
  (rw [(den_succ_at_ri chkf dec encTy ri n m G Sk.nat en)])
  (rw [(den_recN_at_ri chkf dec encTy ri n P z st m G s en)]))

;; Lemma 3.2, Hd.recNS. The recursive result is skOf-faithful by its
;; annotation; nbr supplies faithfulness of the predecessor m.
(pthm den_recNS_ri [P :- Exp, z :- Exp, st :- Exp, m :- Exp, G :- (List Sk), s :- Sk,
  hj :- (SkJ Bool.false G (Exp.recN P z st (Exp.succ m)) s),
  hn :- (Eq Bool (nbr (Exp.recN P z st (Exp.succ m))) Bool.true), en :- (HEnv G)]
  (Eq (Car s)
    (den_ri chkf dec encTy ri n (substL (List.cons Exp (Exp.recN P z st m) (List.cons Exp m (List.nil Exp))) st) G s en)
    (den_ri chkf dec encTy ri n (Exp.recN P z st (Exp.succ m)) G s en))
  (have hi (InvSkJ Bool.false G (Exp.recN P z st (Exp.succ m)) s)
    (inv_recN Bool.false G P z st (Exp.succ m) s hj))
  (have he (Eq Sk s (skel P)) (And.left (And.right hi)))
  (have hm (SkJ Bool.false G m Sk.nat)
    (And.right (And.right (inv_succ Bool.false G m Sk.nat (And.right (And.right (And.right (And.right (And.right hi)))))))))
  (have hkm (Eq (Option Sk) (skOf G m) (Option.some Sk Sk.nat))
    (skOf_ok G m Sk.nat hm (nbr_recN_n P z st (Exp.succ m) Bool.false hn)))
  (have hr (SkJ Bool.false G (Exp.recN P z st m) (skel P))
    (SkJ.sRecN G P z st m (And.left (And.right (And.right hi)))
      (And.left (And.right (And.right (And.right hi))))
      (And.left (And.right (And.right (And.right (And.right hi))))) hm))
  (subst he)
  (exact (Eq.trans
    (den_substL2_ri chkf dec encTy ri n G m Sk.nat (Exp.recN P z st m) (skel P)
      hm hkm hr rfl Bool.false st (skel P)
      (And.left (And.right (And.right (And.right (And.right hi))))) en)
    (Eq.symm (den_recNS_eval_ri chkf dec encTy ri n P z st m G (skel P) en)))))

;; Lookup is positional, including beyond a prefix: nthB's generated
;; equations are needed because it recurses on both list and index.
(a/prove-theorem 'den_nthB_ri
  (lv (into (walk/postwalk-replace '{n budget} P4) '[G :- (List Sk), outsk :- Sk, en :- (HEnv G), bs :- Exp]))
  (lv '(forall [lq Nat] (forall [bq Exp]
    (=> (Eq (Option Exp) (nthB bs lq) (Option.some Exp bq))
      (Eq (Car outsk) (den_ri chkf dec encTy ri budget bq G outsk en)
        ((den_ri chkf dec encTy ri budget bs G (Sk.arr Sk.lbl outsk) en) lq))))))
  (lv (into ['(induction bs)]
    (mapcat (fn [[idx [ctor fields]]]
      (if (= ctor 'bcons)
        '[(intro lq) (cases lq)
          (intro bq hq)
          (exact (Eq.trans
            (congrArg (fn [v :- Exp] (den_ri chkf dec encTy ri budget v G outsk en))
              (Eq.symm (some_inj h bq (Eq.trans (Eq.symm (nthB.eq_25 h t)) hq))))
            (Eq.symm (bcons_zero_ri chkf dec encTy ri budget h t G outsk en))))
          (intro bq hq)
          (exact (Eq.trans
            (ih_t n bq (Eq.trans (Eq.symm (nthB.eq_26 h t n)) hq))
            (Eq.symm (bcons_succ_ri chkf dec encTy ri budget h t G outsk en n))))]
        (let [eqn (symbol (str "nthB.eq_" (if (< idx 24) (inc idx) (+ idx 2))))]
          ['(intro lq bq hq)
           (list 'exact (list 'False.elim$0
             (list 'none_ne_someE 'bq
               (list 'Eq.trans (list 'Eq.symm (apply list eqn (cons 'lq (map first fields)))) 'hq))))])))
      (map-indexed vector exp-fields)))))

;; Lemma 3.2, Hd.caseLb. The denotation reads the same branch as nthB,
;; without a typing or nbr premise (even though Cv still requires both).
(pthm den_caseLb_ri [P :- Exp, l :- Nat, bs :- Exp, b :- Exp,
  hb :- (Eq (Option Exp) (nthB bs l) (Option.some Exp b)),
  G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n b G s en)
              (den_ri chkf dec encTy ri n (Exp.caseL P (Exp.lbl l) bs) G s en))
  (rw [(den_caseL_at_ri chkf dec encTy ri n P (Exp.lbl l) bs G s en)])
  (change (Eq (Car s) (den_ri chkf dec encTy ri n b G s en)
    ((den_ri chkf dec encTy ri n bs G (Sk.arr Sk.lbl s) en) (den_ri chkf dec encTy ri n (Exp.lbl l) G Sk.lbl en))))
  (rw [(den_lbl_lbl_ri chkf dec encTy ri n G l en)])
  (exact (den_nthB_ri chkf dec encTy ri n G s en bs l b hb)))

(pthm den_recSL_eval_ri [P :- Exp, tl :- Exp, tn :- Exp, x :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s)
    (den_ri chkf dec encTy ri n (Exp.recS P tl tn (Exp.sleaf x)) G s en)
    (den_ri chkf dec encTy ri n tl (List.cons Sk Sk.lbl G) s (Prod.mk (den_ri chkf dec encTy ri n x G Sk.lbl en) en)))
  (rw [(den_recS_at_ri chkf dec encTy ri n P tl tn (Exp.sleaf x) G s en)])
  (change (Eq (Car s)
    (Code.rec$1 (fn [_ :- Code] (Car s))
      (fn [l :- Nat] (den_ri chkf dec encTy ri n tl (List.cons Sk Sk.lbl G) s (Prod.mk l en)))
      (fn [l :- Nat, a :- Code, b :- Code, ya :- (Car s), yb :- (Car s)]
        (den_ri chkf dec encTy ri n tn (sk2 s s (sk2 Sk.syn Sk.syn (List.cons Sk Sk.lbl G))) s
          (Prod.mk yb (Prod.mk ya (Prod.mk b (Prod.mk a (Prod.mk l en)))))))
      (den_ri chkf dec encTy ri n (Exp.sleaf x) G Sk.syn en))
    (den_ri chkf dec encTy ri n tl (List.cons Sk Sk.lbl G) s (Prod.mk (den_ri chkf dec encTy ri n x G Sk.lbl en) en))))
  (rw [(den_sleaf_at_ri chkf dec encTy ri n x G Sk.syn en)]))

;; Lemma 3.2, Hd.recSL. nbr makes the substituted label skOf-faithful.
(pthm den_recSL_ri [P :- Exp, tl :- Exp, tn :- Exp, x :- Exp, G :- (List Sk), s :- Sk,
  hj :- (SkJ Bool.false G (Exp.recS P tl tn (Exp.sleaf x)) s),
  hn :- (Eq Bool (nbr (Exp.recS P tl tn (Exp.sleaf x))) Bool.true), en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n (subst1 x tl) G s en)
              (den_ri chkf dec encTy ri n (Exp.recS P tl tn (Exp.sleaf x)) G s en))
  (have hi (InvSkJ Bool.false G (Exp.recS P tl tn (Exp.sleaf x)) s)
    (inv_recS Bool.false G P tl tn (Exp.sleaf x) s hj))
  (have he (Eq Sk s (skel P)) (And.left (And.right hi)))
  (have hx (SkJ Bool.false G x Sk.lbl)
    (And.right (And.right (inv_sleaf Bool.false G x Sk.syn (And.right (And.right (And.right (And.right (And.right hi)))))))))
  (have hk (Eq (Option Sk) (skOf G x) (Option.some Sk Sk.lbl))
    (skOf_ok G x Sk.lbl hx (nbr_recS_c P tl tn (Exp.sleaf x) Bool.false hn)))
  (subst he)
  (exact (Eq.trans
    (den_subst1_ri chkf dec encTy ri n Bool.false G Sk.lbl tl (skel P)
      (And.left (And.right (And.right (And.right hi)))) x hx hk en)
    (Eq.symm (den_recSL_eval_ri chkf dec encTy ri n P tl tn x G (skel P) en)))))

(pthm den_recSN_eval_ri [P :- Exp, tl :- Exp, tn :- Exp, x :- Exp, c1 :- Exp, c2 :- Exp,
  G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s)
    (den_ri chkf dec encTy ri n (Exp.recS P tl tn (Exp.snode x c1 c2)) G s en)
    (den_ri chkf dec encTy ri n tn (sk2 s s (sk2 Sk.syn Sk.syn (List.cons Sk Sk.lbl G))) s
      (Prod.mk (den_ri chkf dec encTy ri n (Exp.recS P tl tn c2) G s en)
        (Prod.mk (den_ri chkf dec encTy ri n (Exp.recS P tl tn c1) G s en)
          (Prod.mk (den_ri chkf dec encTy ri n c2 G Sk.syn en)
            (Prod.mk (den_ri chkf dec encTy ri n c1 G Sk.syn en)
              (Prod.mk (den_ri chkf dec encTy ri n x G Sk.lbl en) en)))))))
  (rw [(den_recS_at_ri chkf dec encTy ri n P tl tn (Exp.snode x c1 c2) G s en)])
  (change (Eq (Car s)
    (Code.rec$1 (fn [_ :- Code] (Car s))
      (fn [l :- Nat] (den_ri chkf dec encTy ri n tl (List.cons Sk Sk.lbl G) s (Prod.mk l en)))
      (fn [l :- Nat, a :- Code, b :- Code, ya :- (Car s), yb :- (Car s)]
        (den_ri chkf dec encTy ri n tn (sk2 s s (sk2 Sk.syn Sk.syn (List.cons Sk Sk.lbl G))) s
          (Prod.mk yb (Prod.mk ya (Prod.mk b (Prod.mk a (Prod.mk l en)))))))
      (den_ri chkf dec encTy ri n (Exp.snode x c1 c2) G Sk.syn en))
    (den_ri chkf dec encTy ri n tn (sk2 s s (sk2 Sk.syn Sk.syn (List.cons Sk Sk.lbl G))) s
      (Prod.mk (den_ri chkf dec encTy ri n (Exp.recS P tl tn c2) G s en)
        (Prod.mk (den_ri chkf dec encTy ri n (Exp.recS P tl tn c1) G s en)
          (Prod.mk (den_ri chkf dec encTy ri n c2 G Sk.syn en)
            (Prod.mk (den_ri chkf dec encTy ri n c1 G Sk.syn en)
              (Prod.mk (den_ri chkf dec encTy ri n x G Sk.lbl en) en))))))))
  (rw [(den_snode_at_ri chkf dec encTy ri n x c1 c2 G Sk.syn en)])
  (rw [(den_recS_at_ri chkf dec encTy ri n P tl tn c1 G s en)])
  (rw [(den_recS_at_ri chkf dec encTy ri n P tl tn c2 G s en)]))

;; Lemma 3.2, Hd.recSN. The five substituted terms are in de Bruijn order:
;; recursive right result, recursive left result, right code, left code,
;; label. TyL records both typing and skOf faithfulness for each term.
(pthm den_recSN_ri [P :- Exp, tl :- Exp, tn :- Exp, x :- Exp, c1 :- Exp, c2 :- Exp,
  G :- (List Sk), s :- Sk,
  hj :- (SkJ Bool.false G (Exp.recS P tl tn (Exp.snode x c1 c2)) s),
  hn :- (Eq Bool (nbr (Exp.recS P tl tn (Exp.snode x c1 c2))) Bool.true), en :- (HEnv G)]
  (Eq (Car s)
    (den_ri chkf dec encTy ri n
      (substL (List.cons Exp (Exp.recS P tl tn c2) (List.cons Exp (Exp.recS P tl tn c1)
        (List.cons Exp c2 (List.cons Exp c1 (List.cons Exp x (List.nil Exp)))))) tn) G s en)
    (den_ri chkf dec encTy ri n (Exp.recS P tl tn (Exp.snode x c1 c2)) G s en))
  (have hi (InvSkJ Bool.false G (Exp.recS P tl tn (Exp.snode x c1 c2)) s)
    (inv_recS Bool.false G P tl tn (Exp.snode x c1 c2) s hj))
  (have he (Eq Sk s (skel P)) (And.left (And.right hi)))
  (have hc (InvSkJ Bool.false G (Exp.snode x c1 c2) Sk.syn)
    (inv_snode Bool.false G x c1 c2 Sk.syn (And.right (And.right (And.right (And.right (And.right hi)))))))
  (have hnc (Eq Bool (nbr (Exp.snode x c1 c2)) Bool.true)
    (nbr_recS_c P tl tn (Exp.snode x c1 c2) Bool.false hn))
  (have hx (SkJ Bool.false G x Sk.lbl) (And.left (And.right (And.right hc))))
  (have h1 (SkJ Bool.false G c1 Sk.syn) (And.left (And.right (And.right (And.right hc)))))
  (have h2 (SkJ Bool.false G c2 Sk.syn) (And.right (And.right (And.right (And.right hc)))))
  (have hkx (Eq (Option Sk) (skOf G x) (Option.some Sk Sk.lbl))
    (skOf_ok G x Sk.lbl hx (nbr_snode_a x c1 c2 Bool.false hnc)))
  (have hk1 (Eq (Option Sk) (skOf G c1) (Option.some Sk Sk.syn))
    (skOf_ok G c1 Sk.syn h1 (nbr_snode_c1 x c1 c2 Bool.false hnc)))
  (have hk2 (Eq (Option Sk) (skOf G c2) (Option.some Sk Sk.syn))
    (skOf_ok G c2 Sk.syn h2 (nbr_snode_c2 x c1 c2 Bool.false hnc)))
  (have hr1 (SkJ Bool.false G (Exp.recS P tl tn c1) (skel P))
    (SkJ.sRecS G P tl tn c1 (And.left (And.right (And.right hi)))
      (And.left (And.right (And.right (And.right hi))))
      (And.left (And.right (And.right (And.right (And.right hi))))) h1))
  (have hr2 (SkJ Bool.false G (Exp.recS P tl tn c2) (skel P))
    (SkJ.sRecS G P tl tn c2 (And.left (And.right (And.right hi)))
      (And.left (And.right (And.right (And.right hi))))
      (And.left (And.right (And.right (And.right (And.right hi))))) h2))
  (subst he)
  (exact (Eq.trans
    (den_substL_ri chkf dec encTy ri n G
      (List.cons Exp (Exp.recS P tl tn c2) (List.cons Exp (Exp.recS P tl tn c1)
        (List.cons Exp c2 (List.cons Exp c1 (List.cons Exp x (List.nil Exp))))))
      (List.cons Sk (skel P) (List.cons Sk (skel P)
        (List.cons Sk Sk.syn (List.cons Sk Sk.syn (List.cons Sk Sk.lbl (List.nil Sk))))))
      (And.intro hr2 (And.intro rfl (And.intro hr1 (And.intro rfl
        (And.intro h2 (And.intro hk2 (And.intro h1 (And.intro hk1
          (And.intro hx (And.intro hkx (Eq.refl$1 (List.nil Sk))))))))))))
      Bool.false tn (skel P) (And.left (And.right (And.right (And.right (And.right hi))))) en)
    (Eq.symm (den_recSN_eval_ri chkf dec encTy ri n P tl tn x c1 c2 G (skel P) en)))))

;; The Option calculation behind codeOf's snode case. The equations remain
;; premises of the motive while splitting Options; no dependent cases on
;; some = some are used.
;; (canonicalNode: the standard constant is used)

;; (canonicalNode_some: the standard constant is used)

;; (canonicalNode_den: the standard constant is used)

(pthm den_code_sleaf_ri [x :- Exp, G :- (List Sk), en :- (HEnv G)]
  (forall [cc Code] (=> (Eq (Option Code) (codeOf (Exp.sleaf x)) (Option.some Code cc))
                        (Eq Code (den_ri chkf dec encTy ri n (Exp.sleaf x) G Sk.syn en) cc)))
  (intro cc hc)
  (refine' (exN _ _ (codeOf_sleaf_inv x cc hc) _))
  (intro l hh)
  (have hx (Eq Exp x (Exp.lbl l)) (And.left hh))
  (subst hx)
  (exact (Eq.trans (den_sleaf_code_ri chkf dec encTy ri n l G en) (Eq.symm (And.right hh)))))

(pthm den_snode_code_ri [l :- Nat, c1 :- Exp, c2 :- Exp, G :- (List Sk), en :- (HEnv G)]
  (Eq Code (den_ri chkf dec encTy ri n (Exp.snode (Exp.lbl l) c1 c2) G Sk.syn en)
           (Code.sn l (den_ri chkf dec encTy ri n c1 G Sk.syn en) (den_ri chkf dec encTy ri n c2 G Sk.syn en)))
  (rw [(den_snode_at_ri chkf dec encTy ri n (Exp.lbl l) c1 c2 G Sk.syn en)])
  (change (Eq Code
    (Code.sn (den_ri chkf dec encTy ri n (Exp.lbl l) G Sk.lbl en)
             (den_ri chkf dec encTy ri n c1 G Sk.syn en) (den_ri chkf dec encTy ri n c2 G Sk.syn en))
    (Code.sn l (den_ri chkf dec encTy ri n c1 G Sk.syn en) (den_ri chkf dec encTy ri n c2 G Sk.syn en))))
  (rw [(den_lbl_at_ri chkf dec encTy ri n l G Sk.lbl en)]))

(a/prove-theorem 'den_code_snode_ri
  (lv (into P4 '[x :- Exp, c1 :- Exp, c2 :- Exp, G :- (List Sk), en :- (HEnv G),
    ih1 :- (forall [cc Code] (=> (Eq (Option Code) (codeOf c1) (Option.some Code cc))
                                (Eq Code (den_ri chkf dec encTy ri n c1 G Sk.syn en) cc))),
    ih2 :- (forall [cc Code] (=> (Eq (Option Code) (codeOf c2) (Option.some Code cc))
                                (Eq Code (den_ri chkf dec encTy ri n c2 G Sk.syn en) cc)))]))
  (lv '(forall [cc Code] (=> (Eq (Option Code) (codeOf (Exp.snode x c1 c2)) (Option.some Code cc))
                            (Eq Code (den_ri chkf dec encTy ri n (Exp.snode x c1 c2) G Sk.syn en) cc))))
  (lv (into ['(cases x)]
    (mapcat (fn [[ctor _]]
      (concat ['(intro cc hc)]
        (if (= ctor 'lbl)
          '[(exact (Eq.trans (den_snode_code_ri chkf dec encTy ri n l c1 c2 G en)
                    (canonicalNode_den l (den_ri chkf dec encTy ri n c1 G Sk.syn en)
                       (den_ri chkf dec encTy ri n c2 G Sk.syn en) (codeOf c1) (codeOf c2) ih1 ih2 cc hc)))]
          '[(exact (False.elim$0 (code_none_ne_some cc hc)))]))) exp-fields))))

;; Lemma 3.2, delta: every closed canonical syntax term denotes precisely
;; the Code accepted by codeOf. The snode proof covers arbitrary tree depth.
(a/prove-theorem 'den_codeOf_ri
  (lv (into P4 '[G :- (List Sk), en :- (HEnv G), e :- Exp]))
  (lv '(forall [cc Code] (=> (Eq (Option Code) (codeOf e) (Option.some Code cc))
                            (Eq Code (den_ri chkf dec encTy ri n e G Sk.syn en) cc))))
  (lv (into ['(induction e)]
    (mapcat (fn [[ctor _]]
      (case ctor
        sleaf '[(exact (den_code_sleaf_ri chkf dec encTy ri n a G en))]
        snode '[(exact (den_code_snode_ri chkf dec encTy ri n a c1 c2 G en ih_c1 ih_c2))]
        '[(intro cc hc) (exact (False.elim$0 (code_none_ne_some cc hc)))])) exp-fields))))

(pthm den_delta_ri [c :- Exp, d :- Exp, cc :- Code, dc :- Code,
  hc :- (Eq (Option Code) (codeOf c) (Option.some Code cc)),
  hd :- (Eq (Option Code) (codeOf d) (Option.some Code dc)),
  G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n (boolExp (chkf cc dc)) G s en)
              (den_ri chkf dec encTy ri n (Exp.chk c d) G s en))
  (rw [(den_boolExp_ri chkf dec encTy ri n (chkf cc dc) G s en)])
  (rw [(den_chk_at_ri chkf dec encTy ri n c d G s en)])
  (change (Eq (Car s) (coe Sk.bool s (chkf cc dc))
    (coe Sk.bool s (chkf (den_ri chkf dec encTy ri n c G Sk.syn en) (den_ri chkf dec encTy ri n d G Sk.syn en)))))
  (rw [(den_codeOf_ri chkf dec encTy ri n G en c cc hc)])
  (rw [(den_codeOf_ri chkf dec encTy ri n G en d dc hd)]))

;; Tokens have a singleton carrier; itR's node clause supplies that sole
;; value while the operational rule passes the syntactic token argument.
;; (den_dia_unique: the standard constant is used)

(pthm den_itRN_eval_ri [X :- Exp, g :- Exp, h :- Exp, d :- Exp, x :- Exp, r1 :- Exp, r2 :- Exp,
  G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s)
    (den_ri chkf dec encTy ri n (Exp.itR X g h (Exp.node d x r1 r2)) G s en)
    ((den_ri chkf dec encTy ri n h G (Sk.arr Sk.dia (Sk.arr Sk.lbl (Sk.arr s (Sk.arr s s)))) en)
      Unit.unit (den_ri chkf dec encTy ri n x G Sk.lbl en)
      (den_ri chkf dec encTy ri n (Exp.itR X g h r1) G s en)
      (den_ri chkf dec encTy ri n (Exp.itR X g h r2) G s en)))
  (rw [(den_itR_at_ri chkf dec encTy ri n X g h (Exp.node d x r1 r2) G s en)])
  (change (Eq (Car s)
    (Code.rec$1 (fn [_ :- Code] (Car s))
      (fn [l :- Nat] ((den_ri chkf dec encTy ri n g G (Sk.arr Sk.lbl s) en) l))
      (fn [l :- Nat, a :- Code, b :- Code, ya :- (Car s), yb :- (Car s)]
        ((den_ri chkf dec encTy ri n h G (Sk.arr Sk.dia (Sk.arr Sk.lbl (Sk.arr s (Sk.arr s s)))) en) Unit.unit l ya yb))
      (den_ri chkf dec encTy ri n (Exp.node d x r1 r2) G Sk.cert en))
    ((den_ri chkf dec encTy ri n h G (Sk.arr Sk.dia (Sk.arr Sk.lbl (Sk.arr s (Sk.arr s s)))) en)
      Unit.unit (den_ri chkf dec encTy ri n x G Sk.lbl en)
      (den_ri chkf dec encTy ri n (Exp.itR X g h r1) G s en)
      (den_ri chkf dec encTy ri n (Exp.itR X g h r2) G s en))))
  (rw [(den_node_at_ri chkf dec encTy ri n d x r1 r2 G Sk.cert en)])
  (rw [(den_itR_at_ri chkf dec encTy ri n X g h r1 G s en)])
  (rw [(den_itR_at_ri chkf dec encTy ri n X g h r2 G s en)]))

;; Lemma 3.2, Hd.itRN. Only d and x need skOf completeness; the two
;; recursive iterator arguments infer their skeleton from X.
(pthm den_itRN_ri [X :- Exp, g :- Exp, h :- Exp, d :- Exp, x :- Exp, r1 :- Exp, r2 :- Exp,
  G :- (List Sk), s :- Sk,
  hj :- (SkJ Bool.false G (Exp.itR X g h (Exp.node d x r1 r2)) s),
  hn :- (Eq Bool (nbr (Exp.itR X g h (Exp.node d x r1 r2))) Bool.true), en :- (HEnv G)]
  (Eq (Car s)
    (den_ri chkf dec encTy ri n
      (Exp.app (Exp.app (Exp.app (Exp.app h d) x) (Exp.itR X g h r1)) (Exp.itR X g h r2)) G s en)
    (den_ri chkf dec encTy ri n (Exp.itR X g h (Exp.node d x r1 r2)) G s en))
  (have hi (InvSkJ Bool.false G (Exp.itR X g h (Exp.node d x r1 r2)) s)
    (inv_itR Bool.false G X g h (Exp.node d x r1 r2) s hj))
  (have he (Eq Sk s (skel X)) (And.left (And.right hi)))
  (have hc (InvSkJ Bool.false G (Exp.node d x r1 r2) Sk.cert)
    (inv_node Bool.false G d x r1 r2 Sk.cert (And.right (And.right (And.right (And.right (And.right hi)))))))
  (have hnc (Eq Bool (nbr (Exp.node d x r1 r2)) Bool.true)
    (nbr_itR_r X g h (Exp.node d x r1 r2) Bool.false hn))
  (have hkd (Eq (Option Sk) (skOf G d) (Option.some Sk Sk.dia))
    (skOf_ok G d Sk.dia (And.left (And.right (And.right hc))) (nbr_node_d d x r1 r2 Bool.false hnc)))
  (have hkx (Eq (Option Sk) (skOf G x) (Option.some Sk Sk.lbl))
    (skOf_ok G x Sk.lbl (And.left (And.right (And.right (And.right hc))))
      (nbr_node_a d x r1 r2 Bool.false hnc)))
  (subst he)
  (rw [(den_app_some_ri chkf dec encTy ri n
    (Exp.app (Exp.app (Exp.app h d) x) (Exp.itR X g h r1)) (Exp.itR X g h r2) G (skel X) (skel X) en rfl)])
  (rw [(den_app_some_ri chkf dec encTy ri n
    (Exp.app (Exp.app h d) x) (Exp.itR X g h r1) G (skel X) (Sk.arr (skel X) (skel X)) en rfl)])
  (rw [(den_app_some_ri chkf dec encTy ri n
    (Exp.app h d) x G Sk.lbl (Sk.arr (skel X) (Sk.arr (skel X) (skel X))) en hkx)])
  (rw [(den_app_some_ri chkf dec encTy ri n
    h d G Sk.dia (Sk.arr Sk.lbl (Sk.arr (skel X) (Sk.arr (skel X) (skel X)))) en hkd)])
  (rw [(den_itRN_eval_ri chkf dec encTy ri n X g h d x r1 r2 G (skel X) en)]))
;; The strengthened Cv excludes the earlier counterexample at either end.
;; This is a proved negation, not merely a failed proof search.
;; (cex_no_cv: the standard constant is used)

;; ---------------------------------------------------------------------------
;; §5  Lemma 3.2 at the root of a path (R4-metatheory.md §3.2).
;;
;; hd_den is every head step, under nbr and skeleton typing of the redex.
;; The type steps tTT and tTF are not steps of a term (skj_not_tT).
;; den_step_nil is the empty-path case of position congruence: getP of the
;; empty path is the term itself and setP replaces it, so the claim is hd_den.
;; A nonempty path descends into a child (step_skel_path's pattern). That
;; inductive step is not proved here: the child's denotation and skOf have
;; to be carried back out through every constructor, and app / letp read
;; skOf of an argument while β, β-let, recNS, recSL and recSN produce their
;; contractum by substitution. skOf_subst does not apply to those
;; substitutions, because the substituted term's skeleton is the binder's
;; skeleton rather than Unit.
;; den_ite_b and den_abort_ty are the one-child congruences the inductive
;; step uses for ite's scrutinee and for a child the denotation ignores.
;; ---------------------------------------------------------------------------

;; A type former is never a skeleton-typed term. Head steps tTT and tTF
;; are therefore excluded from the term clause of Lemma 3.2.
;; (skj_not_tT: the standard constant is used)

;; (skj_not_tUnit: the standard constant is used)

;; Lemma 3.2 at the root of a path: one head step of an nbr skeleton-typed
;; term preserves the denotation at the typed skeleton. Type steps tTT and
;; tTF are not term steps.
(thm hd_den_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, cap :- Nat,
  re :- Exp, co :- Exp, hder :- (Hd chkf re co),
  ctx :- (List Sk), out :- Sk,
  hty :- (SkJ Bool.false ctx re out),
  hnbr :- (Eq Bool (nbr re) Bool.true),
  env :- (HEnv ctx)]
  (Eq (Car out) (den_ri chkf dec encTy ri cap co ctx out env) (den_ri chkf dec encTy ri cap re ctx out env))
  (cases hder)
  (exact (den_beta_ri chkf dec encTy ri cap r A t u ctx out hty hnbr env))
  (exact (den_betaLet_ri chkf dec encTy ri cap C S x y t ctx out hty hnbr env))
  (exact (den_iteT_ri chkf dec encTy ri cap t e ctx out env))
  (exact (den_iteF_ri chkf dec encTy ri cap t e ctx out env))
  (exact (den_elimT_ri chkf dec encTy ri cap P t e ctx out env))
  (exact (den_elimF_ri chkf dec encTy ri cap P t e ctx out env))
  (exact (den_recNZ_ri chkf dec encTy ri cap P z s ctx out env))
  (exact (den_recNS_ri chkf dec encTy ri cap P z s n ctx out hty hnbr env))
  (exact (den_caseLb_ri chkf dec encTy ri cap P l bs b h ctx out env))
  (exact (den_recSL_ri chkf dec encTy ri cap P tl tn x ctx out hty hnbr env))
  (exact (den_recSN_ri chkf dec encTy ri cap P tl tn x c1 c2 ctx out hty hnbr env))
  (exact (den_itRL_nbr_ri chkf dec encTy ri cap X g h x ctx out hty hnbr env))
  (exact (den_itRN_ri chkf dec encTy ri cap X g h d x r1 r2 ctx out hty hnbr env))
  (exact (den_prnL_ri chkf dec encTy ri cap x ctx out env))
  (exact (den_prnN_ri chkf dec encTy ri cap d x r1 r2 ctx out env))
  (exact (den_delta_ri chkf dec encTy ri cap c d cc dc hc hd ctx out env))
  (exact (False.elim$0 (skj_not_tT Exp.tt ctx out hty)))
  (exact (False.elim$0 (skj_not_tT Exp.ff ctx out hty))))

;; (setP_nil: the standard constant is used)

;; (getP_nil: the standard constant is used)

;; Lemma 3.2 at the empty path: the redex is the whole term.
(thm den_step_nil_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, cap :- Nat,
  e :- Exp, ctx :- (List Sk), out :- Sk,
  hty :- (SkJ Bool.false ctx e out),
  hnbr :- (Eq Bool (nbr e) Bool.true),
  r :- Exp, co :- Exp,
  hg :- (Eq (Option Exp) (getP (List.nil Nat) e) (Option.some Exp r)),
  hder :- (Hd chkf r co),
  env :- (HEnv ctx)]
  (Eq (Car out) (den_ri chkf dec encTy ri cap (setP (List.nil Nat) e co) ctx out env)
                (den_ri chkf dec encTy ri cap e ctx out env))
  (have he (Eq Exp e r) (some_inj e r (Eq.trans (Eq.symm (getP_nil e)) hg)))
  (subst he)
  (rw [(setP_nil r co)])
  (exact (hd_den_ri chkf dec encTy ri cap r co hder ctx out hty hnbr env)))

;; (setKid_ite_0: the standard constant is used)

;; (setKid_ite_1: the standard constant is used)

;; (setKid_ite_2: the standard constant is used)

;; A child den ignores (abort's type) can be replaced without changing ⟦·⟧.
(pthm den_abort_ty_ri [A :- Exp, A2 :- Exp, t :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G)]
  (Eq (Car s) (den_ri chkf dec encTy ri n (Exp.abort A2 t) G s en)
              (den_ri chkf dec encTy ri n (Exp.abort A t) G s en))
  (rw [(den_abort_at_ri chkf dec encTy ri n A2 t G s en)])
  (rw [(den_abort_at_ri chkf dec encTy ri n A t G s en)]))

;; Replacing ite's scrutinee preserves ⟦·⟧ when the scrutinees agree at Bool.
(pthm den_ite_b_ri [b :- Exp, b2 :- Exp, t :- Exp, e :- Exp, G :- (List Sk), s :- Sk, en :- (HEnv G),
  hb :- (Eq (Car Sk.bool) (den_ri chkf dec encTy ri n b2 G Sk.bool en) (den_ri chkf dec encTy ri n b G Sk.bool en))]
  (Eq (Car s) (den_ri chkf dec encTy ri n (Exp.ite b2 t e) G s en)
              (den_ri chkf dec encTy ri n (Exp.ite b t e) G s en))
  (rw [(den_ite_at_ri chkf dec encTy ri n b2 t e G s en)])
  (rw [(den_ite_at_ri chkf dec encTy ri n b t e G s en)])
  (change (Eq (Car s)
    (Bool.rec$1 (fn [_ :- Bool] (Car s))
      (den_ri chkf dec encTy ri n e G s en) (den_ri chkf dec encTy ri n t G s en)
      (den_ri chkf dec encTy ri n b2 G Sk.bool en))
    (Bool.rec$1 (fn [_ :- Bool] (Car s))
      (den_ri chkf dec encTy ri n e G s en) (den_ri chkf dec encTy ri n t G s en)
      (den_ri chkf dec encTy ri n b G Sk.bool en))))
  (exact (congrArg (fn [v :- (Car Sk.bool)]
            (Bool.rec$1 (fn [_ :- Bool] (Car s))
              (den_ri chkf dec encTy ri n e G s en) (den_ri chkf dec encTy ri n t G s en) v)) hb)))
