(ns lcert.formal.ri-den
  "Generic copy of lcert.formal.den over an R-interpretation ri : RInt (rint.clj;
  Theorem 4.6 design note §3), generated by formal/tools/gen_ri.py: the
  constants that depend on the model carry the suffix _ri and take ri after
  encTy.  Hand edits at the R-specific steps are marked `;; RI:`.  The
  standard namespace's documentation follows, with the same renaming.

  F3c — denotation (R4-metatheory.md §3.2).

  ⟦t⟧ is a function of the term, the skeleton context G, the expected
  skeleton sk and an environment en : HEnv G, with values in Car sk.  It is
  parameterized by the checker chkf, a decoding dec of codes into (budget,
  term, type), and a type encoding encTy, which the model's theorems constrain
  through CheckSpec (ADR-0006, trust base).

  The clauses (one kernel definition per constructor, generated into
  den_gen.clj by formal/tools/gen_den.py) follow §3.2:
  - constructors, λ, application, pairs, let and the eliminators have their
    set-theoretic meaning; recN, recSyn and itR iterate over the value of
    their scrutinee; caseLbl's branch list denotes a function of the label;
  - abort and H₁ denote defaults; chk′ is chkf; print forgets tokens (the
    identity on Code); inspect branches on chkf;
  - reflect_D r e, at cap c: if the tree v = ⟦r⟧ has at most c nodes and
    chkf v ⌜D⌝ holds, the program dec v decodes to is run at its own budget m;
    otherwise the default.
  Running the decoded program needs the denotation at a smaller budget, so
  the denotation is built as a table of levels (denT_ri): denAt_ri prev cap gives
  one level, with prev the table below.  den_ri n := denT_ri n n."
  (:require [lcert.formal.rint] 
            [ansatz.core :as a]
            [lcert.formal.base :refer [thm kdef]]
            [lcert.formal.usage :refer :all]
            [lcert.formal.syntax :refer :all]
            [lcert.formal.skel :refer :all]
            [lcert.formal.conv :refer :all]
            [lcert.formal.carrier :refer :all]))

;; (DenFn: the standard constant is used)

;; RI: the clauses over ri (formal/tools/gen_den.py --ri).
(load "ri_den_gen")

;; Fuel 0: running a decoded program is impossible (cap 0 admits no tree that
;; Check accepts, since an accepted tree has at least one node), so prev gives
;; defaults.
;; (den0: the standard constant is used)

;; (DenParams: the standard constant is used)

;; The table of levels.  T n is a DenFn defined for every cap m ≤ n:
;;   T 0 m     = denAt den0 m                     (cap 0: no decoded program runs)
;;   T (n+1) m = T n m                  if m ≤ n
;;             = denAt (T n) m          otherwise
;; So T (n+1) (n+1) runs decoded programs through T n, and T n m = T m m for
;; m ≤ n (denT_stable): reflect at cap c runs its program at exactly its own
;; budget m, as §3.2 says, with no fuel-independence argument over terms.
;; (DenBody: the standard constant is used)

;; pickD b x y: x if b, else y — a named selector, since Ansatz's elaborator
;; rejects a recursor applied to more arguments than its arity.
;; (pickD: the standard constant is used)

(kdef denT_ri
  (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code) ri RInt]
    (=> Nat DenFn))))
  (fn [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat]
    (Nat.rec$1 (fn [_ :- Nat] DenFn)
      (fn [m :- Nat, t :- Exp] (denAt_ri chkf dec encTy ri den0 m t))
      (fn [k :- Nat, prev :- DenFn]
        (fn [m :- Nat, t :- Exp] (pickD (Nat.ble m k) (prev m t) (denAt_ri chkf dec encTy ri prev m t))))
      n)))

;; One level: below the new level, the table is unchanged.
(thm denT_step_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt,
                k :- Nat, m :- Nat, h :- (Nat.le m k), t :- Exp]
  (= (denT_ri chkf dec encTy ri (Nat.succ k) m t) (denT_ri chkf dec encTy ri k m t))
  (have hb (= (Nat.ble m k) Bool.true) (Nat.ble_eq_true_of_le h))
  (change (= (pickD (Nat.ble m k) (denT_ri chkf dec encTy ri k m t) (denAt_ri chkf dec encTy ri (denT_ri chkf dec encTy ri k) m t))
             (denT_ri chkf dec encTy ri k m t)))
  (rw [hb]))

;; (ble_succ_self: the standard constant is used)

;; The top level of the table at n + 1 runs decoded programs through level n.
(thm denT_top_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt,
               k :- Nat, t :- Exp]
  (= (denT_ri chkf dec encTy ri (Nat.succ k) (Nat.succ k) t) (denAt_ri chkf dec encTy ri (denT_ri chkf dec encTy ri k) (Nat.succ k) t))
  (have hb (= (Nat.ble (Nat.succ k) k) Bool.false) (ble_succ_self k))
  (change (= (pickD (Nat.ble (Nat.succ k) k) (denT_ri chkf dec encTy ri k (Nat.succ k) t) (denAt_ri chkf dec encTy ri (denT_ri chkf dec encTy ri k) (Nat.succ k) t))
             (denAt_ri chkf dec encTy ri (denT_ri chkf dec encTy ri k) (Nat.succ k) t)))
  (rw [hb]))

;; Stability: level n of the table agrees with level m at every cap m ≤ n.
;; So the denotation at cap c runs a decoded program of budget m < c at
;; exactly its own level: denT (c−1) m = denT m m, the paper's ⟦t′⟧ᵐ.
;; (A proof of Not P is used through absurd; Ansatz's elaborator does not
;; apply it to an argument directly.)
(thm denT_stable_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt,
                  n :- Nat, t :- Exp]
  (forall [m Nat] (=> (LE.le m n) (= (denT_ri chkf dec encTy ri n m t) (denT_ri chkf dec encTy ri m m t))))
  (induction n)
  (intro m hmn)
  (have hz (= m 0) (Nat.le_antisymm hmn (Nat.zero_le m)))
  (subst hz)
  (rfl)
  (intro m hmn)
  (by_cases (Nat.ble m n))
  (have hnle (Not (LE.le m n)) (fn [hh :- (LE.le m n)] (absurd (Nat.ble_eq_true_of_le hh) (ne_true_of_eq_false hc))))
  (have heq (= m (Nat.succ n)) (Nat.le_antisymm hmn (Nat.succ_le_of_lt (Nat.lt_of_not_le hnle))))
  (subst heq)
  (rfl)
  (rw [(denT_step_ri chkf dec encTy ri n m (Nat.le_of_ble_eq_true hc) t)])
  (exact (ih_n m (Nat.le_of_ble_eq_true hc))))

;; ⟦t⟧ⁿ: the table at level n, cap n.
(kdef den_ri
  (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code) ri RInt]
    (=> Nat Exp (forall [G (List Sk)] (forall [sk Sk] (=> (HEnv G) (Car sk))))))))
  (fn [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat, t :- Exp]
    (denT_ri chkf dec encTy ri n n t)))

;; Sanity: the kernel computes denotations.
(thm den_not_tt_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt]
  (= (den_ri chkf dec encTy ri 0 (Exp.app (Exp.lam U.uw Exp.tBool (Exp.ite (Exp.var 0) Exp.ff Exp.tt)) Exp.tt)
          (List.nil Sk) Sk.bool Unit.unit)
     Bool.false)
  (rfl))

(thm den_recN_double_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt]
  (= (den_ri chkf dec encTy ri 0 (Exp.recN Exp.tNat Exp.zero (Exp.succ (Exp.succ (Exp.var 0))) (Exp.succ (Exp.succ (Exp.succ Exp.zero))))
          (List.nil Sk) Sk.nat Unit.unit)
     6)
  (rfl))
