(ns lcert.formal.ri-lemma36
  "Generic copy of lcert.formal.lemma36 over an R-interpretation ri : RInt (rint.clj;
  Theorem 4.6 design note §3), generated by formal/tools/gen_ri.py: the
  constants that depend on the model carry the suffix _ri and take ri after
  encTy.  Hand edits at the R-specific steps are marked `;; RI:`.  The
  standard namespace's documentation follows, with the same renaming.

  F3n — the fundamental lemma (R4-metatheory.md Lemma 3.6), assembled.

  lemma36_step: at a budget n, given the outer hypothesis OuterIH_ri n (Lemma
  3.6 at every smaller budget, for the all-token contexts Θₘ), every runtime
  derivation D ⊢ t :^us A in a well-formed context is sound:
      WFCtx D ⟹ Sound_ri n D us t A
  (for all η ⊨ₖ (D, us) with k ≤ n, ⟦t⟧ⁿη ∈ Vⁿₖ(A)η).  By induction on the
  derivation; each rule is its case lemma (fundamental.clj, outer.clj).  A
  premise under binders is used at the extended context, whose
  well-formedness the rule's formation premises give (WFCtx is a list of
  formation judgments, one per entry).

  outer_all: OuterIH_ri n for every n, by induction on n — OuterIH_ri (n+1) at
  m = n is lemma36_step_ri at n, at the token environment (tok_sat_ri).  This is
  §3.6's argument that the induction is not circular: a certificate is
  decoded at a budget strictly below the one being proved.

  lemma36: Sound_ri n D us t A for every n and every derivation in a
  well-formed context.

  Then Theorem 1 (consistency), Corollary 3.7 (Check accepts no refutation
  and no contradictory pair) and Theorem 3 (certificate size, and its
  refinement to the free tokens), from Lemma 3.6.

  One rule enters as a hypothesis until its case is proved: Conv (needs
  Lemma 3.2, conversion invariance), stated as exactly what the induction
  needs (ConvCase_ri)."
  (:require [lcert.formal.rint] [lcert.formal.ri-den] [lcert.formal.ri-sem] [lcert.formal.ri-model] [lcert.formal.ri-splitting] [lcert.formal.ri-fundamental] [lcert.formal.ri-outer] [lcert.formal.ri-recsyn]
            [ansatz.core :as a]
            [clojure.string :as str]
            [lcert.formal.base :refer [thm kdef lv]]
            [lcert.formal.usage :refer :all]
            [lcert.formal.syntax :refer :all]
            [lcert.formal.skel :refer :all]
            [lcert.formal.conv :refer :all]
            [lcert.formal.judgment :refer :all]
            [lcert.formal.carrier :refer :all]
            [lcert.formal.den :refer :all]
            [lcert.formal.sem :refer :all]
            [lcert.formal.model :refer :all]
            [lcert.formal.splitting :refer :all]
            [lcert.formal.fundamental :refer :all]
            [lcert.formal.derivations]
            [lcert.formal.skeletons]
            [lcert.formal.outer :refer :all]
            [lcert.formal.recsyn]
            [lcert.formal.strengthen]))

(def ^:private PS "chkf dec encTy ri")

;; The Conv case, as the induction uses it: soundness at A carries over to a
;; formed B convertible with A.
(kdef ConvCase_ri (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code) ri RInt] (=> Nat Prop))))
  (fn [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat]
    (forall [D (List Exp)] (forall [us (List U)] (forall [t Exp] (forall [A Exp] (forall [B Exp]
      (=> (Rt chkf D us t A) (Tl chkf Bool.true D B Exp.tUnit) (Cv chkf (skels D) A B)
          (Sound_ri chkf dec encTy ri n D us t A) (Sound_ri chkf dec encTy ri n D us t B)))))))))

;; A case whose lemma takes no environment hypothesis (V of its type is
;; everything at that value): wrap it as Sound.
(defn- wrap [us body]
  (str "(fn [en :- (HEnv (skels D)), kk :- Nat, hkk :- (Nat.le kk cap), hss :- (EnvSat_ri chkf dec encTy ri cap D " us " en kk)] " body ")"))

;; One proof term per rule of Rt, in constructor order; CAP is the
;; theorem's budget.  hw : WFCtx D; ih_<premise> : WFCtx D′ → Sound … .
(def ^:private case-terms
  (let [C (str PS " cap")
        tR "(And.intro (Tl.fBase chkf D Exp.tR (Eq.refl$1 Bool.true)) hw)"]
    [;; rVar, rConst
     (str "(F_var_ri " C " D us i A r hw hA hu hr)")
     (wrap "us" (str "(F_const_ri " C " D us en kk hkk t A h)"))
     ;; rLam, rApp0, rApp
     (str "(F_lam_ri " C " D us A t B r (ih_ht (And.intro hA hw)))")
     (str "(F_app0_ri " C " D us f u A B hu hA hB (ih_hf hw))")
     (str "(F_app_ri " C " D us1 us2 f u A B hu hA hB r hr (ih_hf hw) (ih_hu hw))")
     ;; rPair0, rPair, rLet
     (str "(F_pair0_ri " C " D us A B x y hA hB hx (ih_hy hw))")
     (str "(F_pair_ri " C " D us1 us2 A B x y hA hB hx r hr (ih_hx hw) (ih_hy hw))")
     (str "(F_let_ri " C " D us1 us2 A B C p t hC hA hB r hp (ih_hp hw) (ih_ht (And.intro hB (And.intro hA hw))))")
     ;; rAbort, rConv
     (str "(F_abort_ri " C " D us A t (ih_ht hw))")
     "(hconv D us t A B ht hB hc (ih_ht hw))"
     ;; rIte, rElimB, rSucc, rRecN
     (str "(F_ite_ri " C " D us1 us1 us2 b t e C (ih_hb hw) (ih_ht hw) (ih_he hw))")
     (str "(F_elimB_ri " C " D us1 us1 us2 P b t e hb hP (ih_ht hw) (ih_he hw))")
     (wrap "us" (str "(F_succ_ri " C " D us n en kk hkk)"))
     (str "(F_recN_ri " C " D us1 us1 us2 us3 P z s n hn hP (ih_hz hw) (ih_hs (And.intro hP (And.intro (Tl.fBase chkf D Exp.tNat (Eq.refl$1 Bool.true)) hw))))")
     ;; rCaseL, rBnil, rBcons
     (str "(F_caseL_ri " C " D us1 us1 us2 P x bs hx hP (ih_hx hw) (ih_hb hw))")
     (wrap "us" (str "(F_bnil_ri " C " D us P en kk hkk)"))
     (str "(F_bcons_ri " C " D us us P k h t hP (ih_hh hw) (ih_ht hw))")
     ;; rSleaf, rSnode, rRecS
     (str "(F_sleaf_ri " C " D us x (ih_h hw))")
     (str "(F_snode_ri " C " D us1 us1 us2 us3 x c1 c2 (ih_hx hw) (ih_h1 hw) (ih_h2 hw))")
     (str "(F_recS_ri " C " D us1 us1 us2 us3 P tl tn c hc hP (ih_hl (And.intro (Tl.fBase chkf D Exp.tLbl (Eq.refl$1 Bool.true)) hw)) "
          "(ih_hn (And.intro hY2 (And.intro hY1 (And.intro (Tl.fBase chkf (consE Exp.tSyn (consE Exp.tLbl D)) Exp.tSyn (Eq.refl$1 Bool.true)) "
          "(And.intro (Tl.fBase chkf (consE Exp.tLbl D) Exp.tSyn (Eq.refl$1 Bool.true)) (And.intro (Tl.fBase chkf D Exp.tLbl (Eq.refl$1 Bool.true)) hw)))))) "
          "(ih_hc hw))")
     ;; rLeaf, rNode, rItR, rPrn
     (str "(F_leaf_ri " C " D us hrl x (ih_h hw))") ;; RI: the cases reading ri take the laws (hrl)
     (str "(F_node_ri " C " D us1 hrl us1 us2 us3 us4 d x r1 r2 (ih_hd hw) (ih_hx hw) (ih_h1 hw) (ih_h2 hw))")
     (str "(F_itR_ri " C " D us1 hrl us1 us2 us3 X g h r hX (ih_hg hw) (ih_hh hw) (ih_hr hw))")
     (str "(F_prn_ri " C " D us r (ih_h hw))")
     ;; rChk, rH1, rRefl, rInsp
     (wrap "(vadd us1 us2)" (str "(F_chk_ri " C " D (vadd us1 us2) c d en kk hkk)"))
     (str "(F_h1_ri " C " D us1 us2 us3 us4 us5 r s c e1 e2 hcs hout hrl hph (ih_hr hw) (ih_hs hw) (ih_h1 hw) (ih_h2 hw))")
     (str "(F_refl_ri " C " D us1 us2 X cd r e hb hcs hout hrl hph (ih_hr hw) (ih_he hw))")
     (str "(F_insp_ri " C " D us1 us0 us2 X r c t1 t2 hc hX (ih_hr hw) (ih_h1 (And.intro hF1 " tR ")) (ih_h2 (And.intro hF2 " tR ")))")]))

(a/prove-theorem 'lemma36_step_ri
  (lv '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, cap :- Nat,
        hcs :- (CheckSpec chkf dec encTy),
        ;; RI: the laws of ri, and Corollary 3.7 for trees with a phantom
        hrl :- (RLaws ri), hph :- (PhCons chkf encTy ri),
        hout :- (OuterIH_ri chkf dec encTy ri cap),
        hconv :- (ConvCase_ri chkf dec encTy ri cap),
        D0 :- (List Exp), us0 :- (List U), t0 :- Exp, A0 :- Exp, der :- (Rt chkf D0 us0 t0 A0)])
  '(=> (WFCtx chkf D0) (Sound_ri chkf dec encTy ri cap D0 us0 t0 A0))
  (lv (into ['(induction der)]
            (mapcat (fn [t] ['(intro hw) (list 'exact (read-string t))]) case-terms))))

;; --- the outer induction on the budget, and Lemma 3.6 ------------------------------------

(def ^:private P3 '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt])
(thm outer_zero_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt]
  (OuterIH_ri chkf dec encTy ri 0)
  (intro m hm) (exact (False.elim (Nat.not_lt_zero m hm))))

;; The trust base (CheckSpec) and, until proved, the Conv case.
;; RI: and the laws of ri, and PhCons.
(def ^:private HYP '[hcs :- (CheckSpec chkf dec encTy), hrl :- (RLaws ri), hph :- (PhCons chkf encTy ri), hconv :- (forall [n Nat] (ConvCase_ri chkf dec encTy ri n))])
;; outer_succ: OuterIH (n+1) from OuterIH n — at m < n by the hypothesis, at
;; m = n by lemma36_step at the token environment.
(eval (list 'lcert.formal.base/thm 'outer_succ_ri (into P3 HYP)
  '(forall [n Nat] (=> (OuterIH_ri chkf dec encTy ri n) (OuterIH_ri chkf dec encTy ri (+ n 1))))
  '(intro n ih m hm t A hd)
  '(have hor (Or (Eq Nat m n) (Nat.lt m n)) (Nat.eq_or_lt_of_le (Nat.le_of_lt_succ hm)))
  '(cases hor)
  '(subst h)
  '(exact (lemma36_step_ri chkf dec encTy ri n hcs hrl hph ih (hconv n) (thetaD n) (thetaU n) t A hd (wf_theta chkf n)
            (tokEnvD n) n (Nat.le_refl n) (tok_sat_ri chkf dec encTy ri n n)))
  '(exact (ih m h t A hd))))
(eval (list 'lcert.formal.base/thm 'outer_all_ri (into P3 HYP) '(forall [n Nat] (OuterIH_ri chkf dec encTy ri n))
  '(intro n) '(induction n)
  '(exact (outer_zero_ri chkf dec encTy ri))
  '(exact (outer_succ_ri chkf dec encTy ri hcs hrl hph hconv n ih_n))))
;; Lemma 3.6.
(eval (list 'lcert.formal.base/thm 'lemma36_ri
  (into (into P3 HYP) '[n :- Nat, D :- (List Exp), us :- (List U), t :- Exp, A :- Exp, der :- (Rt chkf D us t A), hw :- (WFCtx chkf D)])
  '(Sound_ri chkf dec encTy ri n D us t A)
  '(exact (lemma36_step_ri chkf dec encTy ri n hcs hrl hph (outer_all_ri chkf dec encTy ri hcs hrl hph hconv n) (hconv n) D us t A der hw))))

;; RI: Theorems 1 and 3 and Corollary 3.7 are not needed over ri: the generic
;; chain stops at Lemma 3.6 (lemma36_ri).  Theorem 4.6 (theorem46.clj) uses
;; lemma36_ri at the phantom interpretation, and the standard Corollary 3.7
;; for PhCons there (lemma46a.clj).
