(ns lcert.formal.ri-model
  "Generic copy of lcert.formal.model over an R-interpretation ri : RInt (rint.clj;
  Theorem 4.6 design note §3), generated by formal/tools/gen_ri.py: the
  constants that depend on the model carry the suffix _ri and take ri after
  encTy.  Hand edits at the R-specific steps are marked `;; RI:`.  The
  standard namespace's documentation follows, with the same renaming.

  F3e — environments, the checker's specification, and the statements of
  §3's theorems (R4-metatheory.md §§3.4–3.9).

  EnvSat: η ⊨ⁿₖ Γ (§3.4).  An entry of usage 1 has its value in Vⱼ with a
  footprint j; the footprints of all entries sum to at most k.  An entry of
  usage ω has its value in V₀.  An entry of usage 0 is unconstrained.

  CheckSpec chkf dec encTy — the trust base of ADR-0006.  The metatheory uses
  Check only through these properties, which the concrete Check has by
  construction (§1.6; proved for it in phase F7):
  - Lemmas 2.6–2.7: if chkf c d, then c decodes (dec) to a derivable,
    closed-typed judgment Θₘ ⊢ t :¹ A with ⊢ A type, ⌜A⌝ = d and m < nodes(c);
  - the base-type codes used by the rules are the encodings of those types;
  - E5: ⌜A ⊸ 0⌝ = snode arrow₁ ⌜A⌝ ⌜0⌝ for closed A;
  - E1: the encoding is injective on closed types.

  The statements of Lemma 3.6, Theorem 1, Corollary 3.7 and Theorem 3 are
  kernel-checked Prop constants here; their proofs are separate theorems."
  (:require [lcert.formal.rint] [lcert.formal.ri-den] [lcert.formal.ri-sem]
            [ansatz.core :as a]
            [lcert.formal.base :refer [thm kdef]]
            [lcert.formal.usage :refer :all]
            [lcert.formal.syntax :refer :all]
            [lcert.formal.skel :refer :all]
            [lcert.formal.conv :refer :all]
            [lcert.formal.judgment :refer :all]
            [lcert.formal.carrier :refer :all]
            [lcert.formal.den :refer :all]
            [lcert.formal.sem :refer :all]))

;; Every variable index below c: closedness of a type is closedBelow 0.
;; (closedF: the standard constant is used)

;; (closedTy: the standard constant is used)

;; --- environments (§3.4) -------------------------------------------------------

;; The condition on one entry of usage r whose value, at footprint j, satisfies P.
;; (EntryOK: the standard constant is used)

;; EnvSat n D us η k: the environment η satisfies the context (D, us) with
;; total footprint at most k, at cap n.
(kdef EnvSat_ri
  (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code) ri RInt]
    (forall [n Nat] (forall [D (List Exp)] (=> (List U) (HEnv (skels D)) Nat Prop))))))
  (fn [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat, D :- (List Exp)]
    (List.rec$1$0 Exp (fn [D :- (List Exp)] (=> (List U) (HEnv (skels D)) Nat Prop))
      (fn [us :- (List U), en :- Unit, k :- Nat] True)
      (fn [A :- Exp, rest :- (List Exp), ih :- (=> (List U) (HEnv (skels rest)) Nat Prop)]
        (fn [us :- (List U), en :- (HEnv (skels (List.cons Exp A rest))), k :- Nat]
          (List.rec$1$0 U (fn [_ :- (List U)] Prop) False
            (fn [r :- U, us2 :- (List U), _ :- Prop]
              (Exists (fn [j :- Nat] (Exists (fn [k2 :- Nat]
                (And (Nat.le (+ j k2) k)
                  (And (ih us2 (Prod.snd en) k2)
                       (EntryOK r j (fn [jj :- Nat] (V_ri chkf dec encTy ri n A (skels rest) (Prod.snd en) jj (skel A) (Prod.fst en)))))))))))
            us)))
      D)))

;; --- the checker's specification (the trust base) ------------------------------

;; (CheckSpec: the standard constant is used)

;; --- statements (§3) ---------------------------------------------------------------

;; Lemma 3.6 (soundness at budget n), for well-formed contexts (the paper's
;; presupposition; WFCtx, judgment.clj).
;; RI: over an R-interpretation the lemma assumes its laws (RLaws) and
;; Corollary 3.7 for trees with a phantom (PhCons), both trivial at stdRI.
(kdef Lemma_3_6_ri Prop
  (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code) ri RInt]
    (=> (CheckSpec chkf dec encTy) (RLaws ri) (PhCons chkf encTy ri)
      (forall [n Nat] (forall [D (List Exp)] (forall [us (List U)] (forall [t Exp] (forall [A Exp]
        (=> (WFCtx chkf D) (Rt chkf D us t A)
          (forall [en (HEnv (skels D))] (forall [k Nat]
            (=> (Nat.le k n) (EnvSat_ri chkf dec encTy ri n D us en k)
              (V_ri chkf dec encTy ri n A (skels D) en k (skel A) (den_ri chkf dec encTy ri n t (skels D) (skel A) en))))))))))))))))

;; Theorem 1 (consistency): for no n is Θₙ ⊢ t :¹ 0 derivable.
;; (Theorem_1: the standard constant is used)

;; Corollary 3.7: Check accepts no refutation and no contradictory pair.
;; (Corollary_3_7: the standard constant is used)

;; --- Theorem 2 (self-justification): closed inhabitants of H° and H₁° ----------

;; H° = Π(r :₁ R). T(chk′ (print r) c⊥) ⊸ 0.
;; (Hcirc: the standard constant is used)
;; (Hterm: the standard constant is used)

;; ⊢ λ(r :₁ R). λ(e :₁ T(chk′ (print r) c⊥)). H r e :¹ H°, at budget 0.
;; (Theorem_2_H: the standard constant is used)

;; H₁° = Π(r :₁ R). Π(s :₁ R). Π(c :ω Syn). T(chk′ (print r) c) ⊸ T(chk′ (print s) (neg c)) ⊸ 0,
;; inhabited by λr. λs. λc. λe₁. λe₂. H₁ r s c e₁ e₂ (de Bruijn: r = 4, …, e₂ = 0).
;; (H1circ: the standard constant is used)
;; (H1term: the standard constant is used)
;; ⊢ H1term :¹ H₁°, at budget 0: five rLam (formation of each binder type;
;; neg c is snode 25 c c⊥) around rH1, whose premises are the variables, each
;; used once, c at ω (one-hot usage vectors summing to the context's).
;; RI: Theorem 2 (H₁) does not involve the model: the standard Theorem_2_H1 is used.
