(ns lcert.formal.ri-outer
  "Generic copy of lcert.formal.outer over an R-interpretation ri : RInt (rint.clj;
  Theorem 4.6 design note §3), generated by formal/tools/gen_ri.py: the
  constants that depend on the model carry the suffix _ri and take ri after
  encTy.  Hand edits at the R-specific steps are marked `;; RI:`.  The
  standard namespace's documentation follows, with the same renaming.

  F3m — the cases of the fundamental lemma (R4-metatheory.md Lemma 3.6) that
  use the outer induction on the budget: Reflect and H₁ (§3.5, and §3.6: why
  the induction is not circular).

  Both read a certificate through the checker's specification CheckSpec
  (model.clj): an accepted code decodes to a derivation Θₘ ⊢ t :¹ A at a
  budget m below its node count, hence below the footprint that pays for it,
  hence below n.  The outer hypothesis OuterIH_ri n is Lemma 3.6 at every m < n
  for the all-token context Θₘ and environment; the assembly of Lemma 3.6
  (strong induction on n) supplies it.

  - F_refl: ⟦reflect_X r e⟧ ∈ Vⁿₖ(X).
  - F_insp: ⟦inspect_X r c t₁ t₂⟧ ∈ Vⁿₖ(X) (no outer hypothesis; it shares the
    check lemmas).
  - F_h1: the premises of H₁ are unsatisfiable (their composition, Lemma 2.4,
    would put a value in V_ri(0) = ∅ at a smaller budget)."
  (:require [lcert.formal.rint] [lcert.formal.ri-den] [lcert.formal.ri-sem] [lcert.formal.ri-model] [lcert.formal.ri-splitting] [lcert.formal.ri-unfold] [lcert.formal.ri-mono] [lcert.formal.ri-subst] [lcert.formal.ri-substitution] [lcert.formal.ri-fundamental] [lcert.formal.ri-vweaken]
            [ansatz.core :as a]
            [lcert.formal.base :refer [thm kdef lv]]
            [lcert.formal.usage :refer :all]
            [lcert.formal.syntax :refer :all]
            [lcert.formal.skel :refer :all]
            [lcert.formal.conv :refer :all]
            [lcert.formal.judgment :refer :all]
            [lcert.formal.carrier :refer :all]
            [lcert.formal.den :refer :all]
            [lcert.formal.sem :refer :all]
            [lcert.formal.model :refer :all]
            [lcert.formal.splitting :refer :all]
            [lcert.formal.unfold :refer :all]
            [lcert.formal.mono]
            [lcert.formal.skeletons]
            [lcert.formal.subst]
            [lcert.formal.substitution]
            [lcert.formal.fundamental :refer :all]
            [lcert.formal.derivations]
            [lcert.formal.vweaken]))

;; The case-lemma builders, as in fundamental.clj.
(def ^:private P6 '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat, D :- (List Exp)])
(def ^:private ENV '[en :- (HEnv (skels D)), k :- Nat, hk :- (Nat.le k n)])
(defn- concl [A t] (list 'V_ri 'chkf 'dec 'encTy 'ri 'n A '(skels D) 'en 'k (list 'skel A) (list 'den_ri 'chkf 'dec 'encTy 'ri 'n t '(skels D) (list 'skel A) 'en)))
(defn- SND [us t A] (list 'Sound_ri 'chkf 'dec 'encTy 'ri 'n 'D us t A))
(defn- ES [us kk] (list 'EnvSat_ri 'chkf 'dec 'encTy 'ri 'n 'D us 'en kk))
(defn- split-steps [h a b K ka kb hp]
  (let [body (list 'And (list 'Nat.le (list '+ ka kb) K) (list 'And (ES a ka) (ES b kb)))
        ex (list 'Exists (list 'fn [ka :- 'Nat] (list 'Exists (list 'fn [kb :- 'Nat] body))))
        hx (symbol (str hp "_ex")) hq (symbol (str hp "_q")) hr (symbol (str hp "_r"))]
    [(list 'have hx ex (list 'EnvSat_split_ri 'chkf 'dec 'encTy 'ri 'n 'D a b 'en K h))
     (list 'refine' (list 'exN '_ '_ hx '_)) (list 'intro ka hq)
     (list 'refine' (list 'exN '_ '_ hq '_)) (list 'intro kb hr)
     (list 'have hp body hr)]))

;; --- the token environment Θₘ ---------------------------------------------------------

;; tokEnvD m: the all-token environment, typed by the context's skeletons.  The
;; Refl clause of ⟦·⟧ (den_gen.clj) runs decoded programs at (thetaSk m,
;; tokenEnv m) instead; the two are equal as dependent pairs (tok_pair), so
;; any denotation transfers (tok_transfer).  The tokens satisfy Θₘ at
;; footprint m (tok_sat), and Θₘ is well-formed (wf_theta).

;; (tokEnvD: the standard constant is used)
;; (tok_pair: the standard constant is used)
;; (tok_transfer: the standard constant is used)
(thm tok_sat_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, cap :- Nat, m :- Nat]
  (EnvSat_ri chkf dec encTy ri cap (thetaD m) (thetaU m) (tokEnvD m) m)
  (induction m)
  (exact True.intro)
  (constructor) (exact 1) (constructor) (exact n) (constructor)
  (exact (Nat.le_of_eq (Nat.add_comm 1 n))) (constructor) (exact ih_n) (exact (Nat.le_refl 1)))
;; (wf_theta: the standard constant is used)

;; --- base types and their codes ------------------------------------------------------

;; (someC_inj: the standard constant is used)
;; its code term denotes its encoding, under CheckSpec's second clause
(thm den_cleaf_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                  G :- (List Sk), en :- (HEnv G), l :- Nat]
  (Eq Code (den_ri chkf dec encTy ri n (cLeaf l) G Sk.syn en) (Code.sl l))
  (change (Eq Code (den_ri chkf dec encTy ri n (Exp.sleaf (Exp.lbl l)) G Sk.syn en) (Code.sl l)))
  (rw [(den_sleaf_at_ri chkf dec encTy ri n (Exp.lbl l) G Sk.syn en)])
  (rw [(den_lbl_eq_ri chkf dec encTy ri n l)]))
;; a base type (baseCode defined) is a base data type and closed
;; (base_is_base: the standard constant is used)
;; (leafOf: the standard constant is used)
(def ^:private exp-fields @#'lcert.formal.syntactic/exp-fields)
(def ^:private base-label '{tEmpty 15 tUnit 16 tBool 17 tNat 18 tLbl 19 tSyn 20 tR 22})
;; (base_leaf: the standard constant is used)
(thm base_den_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                 hcs :- (forall [D Exp] (forall [cd Exp] (=> (Eq (Option Exp) (baseCode D) (Option.some Exp cd)) (Eq (Option Code) (codeOf cd) (Option.some Code (encTy D)))))),
                 X :- Exp, cd :- Exp, hb :- (Eq (Option Exp) (baseCode X) (Option.some Exp cd)), G :- (List Sk), en :- (HEnv G)]
  (Eq Code (den_ri chkf dec encTy ri n cd G Sk.syn en) (encTy X))
  (have e (Eq Exp cd (cLeaf (leafOf X))) (base_leaf X cd hb))
  (have h3 (Eq (Option Code) (codeOf (cLeaf (leafOf X))) (Option.some Code (encTy X)))
    (Eq.mp (congrArg (fn [c :- Exp] (Eq (Option Code) (codeOf c) (Option.some Code (encTy X)))) e) (hcs X cd hb)))
  (have h4 (Eq Code (Code.sl (leafOf X)) (encTy X)) (someC_inj (Code.sl (leafOf X)) (encTy X) h3))
  (exact (Eq.mpr (congrArg (fn [c :- Exp] (Eq Code (den_ri chkf dec encTy ri n c G Sk.syn en) (encTy X))) e)
                 (Eq.trans (den_cleaf_ri chkf dec encTy ri n G en (leafOf X)) h4))))

;; --- the check, forced by a certificate of chk′ -----------------------------------------

(thm den_chk_val_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                    c :- Exp, d :- Exp, G :- (List Sk), en :- (HEnv G)]
  (Eq Bool (den_ri chkf dec encTy ri n (Exp.chk c d) G Sk.bool en) (chkf (den_ri chkf dec encTy ri n c G Sk.syn en) (den_ri chkf dec encTy ri n d G Sk.syn en)))
  (rw [(den_chk_at_ri chkf dec encTy ri n c d G Sk.bool en)]))
(thm den_prn_val_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                    r :- Exp, G :- (List Sk), en :- (HEnv G)]
  ;; RI: ⟦print r⟧ is riPr ri ⟦r⟧
  (Eq Code (den_ri chkf dec encTy ri n (Exp.prn r) G Sk.syn en) (riPr ri (den_ri chkf dec encTy ri n r G Sk.cert en)))
  (rw [(den_prn_at_ri chkf dec encTy ri n r G Sk.syn en)]))
;; e ∈ V(chkT r cd) forces the check on ⟦r⟧ and ⟦cd⟧
(thm chk_true_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                 G :- (List Sk), en :- (HEnv G), k :- Nat, r :- Exp, cd :- Exp, v :- Unit,
                 h :- (V_ri chkf dec encTy ri n (chkT r cd) G en k Sk.unit v)]
  ;; RI: the check is on the print of ⟦r⟧
  (Eq Bool (chkf (riPr ri (den_ri chkf dec encTy ri n r G Sk.cert en)) (den_ri chkf dec encTy ri n cd G Sk.syn en)) Bool.true)
  (have h1 (Eq Bool (den_ri chkf dec encTy ri n (Exp.chk (Exp.prn r) cd) G Sk.bool en) Bool.true) h)
  (have h2 (Eq Bool (chkf (den_ri chkf dec encTy ri n (Exp.prn r) G Sk.syn en) (den_ri chkf dec encTy ri n cd G Sk.syn en)) Bool.true)
    (Eq.trans (Eq.symm (den_chk_val_ri chkf dec encTy ri n (Exp.prn r) cd G en)) h1))
  (exact (Eq.mp (congrArg (fn [q :- Code] (Eq Bool (chkf q (den_ri chkf dec encTy ri n cd G Sk.syn en)) Bool.true)) (den_prn_val_ri chkf dec encTy ri n r G en)) h2)))

;; --- Reflect -----------------------------------------------------------------------

;; The outer hypothesis (the induction on the budget): Lemma 3.6 at every
;; smaller budget m, for all-token contexts and the token environment.

(def ^:private rv '(den_ri chkf dec encTy ri n r G Sk.cert en))
;; RI: reflect decodes the print of ⟦r⟧ when ⟦r⟧ fits the cap, is phantom-free
;; and its print is accepted; den_refl_none_ri: a tree with a phantom gives the
;; default.
(eval (list 'lcert.formal.base/thm 'den_refl_some_ri
  '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
    X :- Exp, r :- Exp, e :- Exp, G :- (List Sk), sk :- Sk, en :- (HEnv G), m :- Nat, t :- Exp, A :- Exp,
    hc :- (Eq Bool (Bool.and (Nat.ble (cnodes (den_ri chkf dec encTy ri n r G Sk.cert en)) n)
                             (Bool.and (riPf ri (den_ri chkf dec encTy ri n r G Sk.cert en)) (chkf (riPr ri (den_ri chkf dec encTy ri n r G Sk.cert en)) (encTy X)))) Bool.true),
    hd :- (Eq (Option (Prod Nat (Prod Exp Exp))) (dec (riPr ri (den_ri chkf dec encTy ri n r G Sk.cert en))) (Option.some (Prod Nat (Prod Exp Exp)) (Prod.mk m (Prod.mk t A))))]
  '(Eq (Car sk) (den_ri chkf dec encTy ri n (Exp.refl X r e) G sk en)
       (coe (skel X) sk (denPrev_ri chkf dec encTy ri n m t (thetaSk m) (skel X) (tokenEnv m))))
  '(rw [(den_refl_at_ri chkf dec encTy ri n X r e G sk en)])
  (list 'change (list 'Eq '(Car sk)
     (list 'Bool.rec$1 '(fn [_ :- Bool] (Car sk)) '(dflt sk)
       (list 'Option.rec$1$0 '(Prod Nat (Prod Exp Exp)) '(fn [_ :- (Option (Prod Nat (Prod Exp Exp)))] (Car sk)) '(dflt sk)
             '(fn [tr :- (Prod Nat (Prod Exp Exp))] (coe (skel X) sk (denPrev_ri chkf dec encTy ri n (Prod.fst tr) (Prod.fst (Prod.snd tr)) (thetaSk (Prod.fst tr)) (skel X) (tokenEnv (Prod.fst tr)))))
             (list 'dec (list 'riPr 'ri rv)))
       (list 'Bool.and (list 'Nat.ble (list 'cnodes rv) 'n) (list 'Bool.and (list 'riPf 'ri rv) (list 'chkf (list 'riPr 'ri rv) '(encTy X)))))
     '(coe (skel X) sk (denPrev_ri chkf dec encTy ri n m t (thetaSk m) (skel X) (tokenEnv m)))))
  '(rw [hc hd])))
(eval (list 'lcert.formal.base/thm 'den_refl_none_ri
  '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
    X :- Exp, r :- Exp, e :- Exp, G :- (List Sk), sk :- Sk, en :- (HEnv G),
    hf :- (Eq Bool (riPf ri (den_ri chkf dec encTy ri n r G Sk.cert en)) Bool.false)]
  '(Eq (Car sk) (den_ri chkf dec encTy ri n (Exp.refl X r e) G sk en) (dflt sk))
  '(rw [(den_refl_at_ri chkf dec encTy ri n X r e G sk en)])
  (list 'change (list 'Eq '(Car sk)
     (list 'Bool.rec$1 '(fn [_ :- Bool] (Car sk)) '(dflt sk)
       (list 'Option.rec$1$0 '(Prod Nat (Prod Exp Exp)) '(fn [_ :- (Option (Prod Nat (Prod Exp Exp)))] (Car sk)) '(dflt sk)
             '(fn [tr :- (Prod Nat (Prod Exp Exp))] (coe (skel X) sk (denPrev_ri chkf dec encTy ri n (Prod.fst tr) (Prod.fst (Prod.snd tr)) (thetaSk (Prod.fst tr)) (skel X) (tokenEnv (Prod.fst tr)))))
             (list 'dec (list 'riPr 'ri rv)))
       (list 'Bool.and (list 'Nat.ble (list 'cnodes rv) 'n) (list 'Bool.and (list 'riPf 'ri rv) (list 'chkf (list 'riPr 'ri rv) '(encTy X)))))
     '(dflt sk)))
  '(rw [hf])
  (list 'rw [(list 'Bool.false_and (list 'chkf (list 'riPr 'ri rv) '(encTy X)))])
  (list 'rw [(list 'Bool.and_false (list 'Nat.ble (list 'cnodes rv) 'n))])))
;; (exT: the standard constant is used)
(thm denPrev_stable_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt,
                       n :- Nat, m :- Nat, t :- Exp, h :- (LT.lt m n)]
  (Eq DenBody (denPrev_ri chkf dec encTy ri n m t) (den_ri chkf dec encTy ri m t))
  (cases n)
  (exact (absurd h (Nat.not_lt_zero m)))
  (exact (denT_stable_ri chkf dec encTy ri n t m (Nat.le_of_lt_succ h))))
(kdef OuterIH_ri (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code) ri RInt] (=> Nat Prop))))
  (fn [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat]
    (forall [m Nat] (=> (LT.lt m n) (forall [t Exp] (forall [A Exp] (=> (Rt chkf (thetaD m) (thetaU m) t A)
      (V_ri chkf dec encTy ri m A (skels (thetaD m)) (tokEnvD m) m (skel A) (den_ri chkf dec encTy ri m t (skels (thetaD m)) (skel A) (tokEnvD m))))))))))
;; (refl_arith: the standard constant is used)

;; Reflect (the paper's case): e's IH forces chk′ (print ⟦r⟧) ⌜X⌝ = tt; by
;; CheckSpec ⟦r⟧ decodes to Θₘ ⊢ t′ : A′ with ⌜A′⌝ = ⌜X⌝ and m < ‖⟦r⟧‖ ≤ k₁,
;; so A′ = X (E1, both closed) and the cap is met; ⟦refl⟧ is ⟦t′⟧ᵐ at the
;; tokens (denPrev_stable, tok_transfer), in Vᵐₘ(X) by the outer hypothesis
;; at m < n, hence in Vⁿₖ(X) by Lemma 3.4 (m ≤ k).

(def ^:private v1 '(den_ri chkf dec encTy ri n r (skels D) Sk.cert en))
;; RI: the print of ⟦r⟧, which the checker reads
(def ^:private pv1 (list 'riPr 'ri v1))
(def ^:private C1body (fn [mm tt AA] (list 'And (list 'Eq '(Option (Prod Nat (Prod Exp Exp))) (list 'dec pv1) (list 'Option.some '(Prod Nat (Prod Exp Exp)) (list 'Prod.mk mm (list 'Prod.mk tt AA))))
                     (list 'And (list 'Rt 'chkf (list 'thetaD mm) (list 'thetaU mm) tt AA)
                     (list 'And (list 'Tl 'chkf 'Bool.true '(List.nil Exp) AA 'Exp.tUnit)
                     (list 'And (list 'Eq 'Bool (list 'closedTy AA) 'Bool.true)
                     (list 'And (list 'Eq 'Code (list 'encTy AA) '(encTy X)) (list 'Nat.lt mm (list 'cnodes pv1)))))))))
(def ^:private run '(den_ri chkf dec encTy ri mm tt (skels (thetaD mm)) (skel X) (tokEnvD mm)))
;; RI: Reflect over ri.  e's IH forces chk′ (print ⟦r⟧) ⌜X⌝, i.e. the checker
;; accepts riPr ri ⟦r⟧ at encTy X.  If ⟦r⟧ is phantom-free, its print has its
;; node count (L3), and the standard argument runs on the print: CheckSpec
;; decodes it at a budget m < ‖⟦r⟧‖ ≤ k₁, the outer hypothesis types the
;; program at m, and Lemma 3.4 lifts it to n, k.  If ⟦r⟧ has a phantom,
;; ⟦reflect⟧ is the default (den_refl_none_ri): in V(X) for a base type X ≠ 0
;; (V_dflt_ri), and X = 0 is excluded by PhCons (an accepted refutation).
(a/prove-theorem 'V_dflt_ri
  (lv '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, hrl :- (RLaws ri),
        n :- Nat, G :- (List Sk), en :- (HEnv G), k :- Nat, X :- Exp, cd :- Exp])
  (lv '(=> (Eq (Option Exp) (baseCode X) (Option.some Exp cd)) (=> (Eq Exp X Exp.tEmpty) False)
           (V_ri chkf dec encTy ri n X G en k (skel X) (dflt (skel X)))))
  (lv (into ['(cases X)]
        (mapcat (fn [[ctor _]]
                  (into '[(intro hb hne)]
                        (case ctor
                          tEmpty '[(exact (False.elim (hne (Eq.refl$1 Exp.tEmpty))))]
                          (tUnit tBool tNat) '[(exact True.intro)]
                          tLbl '[(exact (Nat.zero_lt_succ 99))]
                          tSyn '[(exact (Eq.refl$1 Bool.true))]
                          tR '[(constructor) (exact (Nat.zero_le k)) (exact (rl_dflt ri hrl))]
                          '[(exact (False.elim$0 (none_ne_someE cd hb)))])))
                exp-fields))))
(thm bool_and3_true [a :- Bool, b :- Bool, c :- Bool, ha :- (Eq Bool a Bool.true), hb :- (Eq Bool b Bool.true), hc :- (Eq Bool c Bool.true)]
  (Eq Bool (Bool.and a (Bool.and b c)) Bool.true) (rw [ha hb hc]))
(thm lt_of_lt_eq [m :- Nat, a :- Nat, b :- Nat, h :- (LT.lt m a), e :- (Eq Nat a b)] (LT.lt m b) (rw [(Eq.symm e)]) (exact h))
;; The phantom-free branch of Reflect: the standard argument, on the print.
(eval (concat (list 'lcert.formal.base/thm 'refl_pf_ri
  (into P6 (into '[X :- Exp, cd :- Exp, r :- Exp, e :- Exp,
                   hb :- (Eq (Option Exp) (baseCode X) (Option.some Exp cd)),
                   hcs :- (CheckSpec chkf dec encTy), hout :- (OuterIH_ri chkf dec encTy ri n), hrl :- (RLaws ri)]
                 (into ENV ['k1 :- 'Nat 'k2 :- 'Nat 'hkk :- '(LE.le (+ k1 k2) k)
                            'vr :- (list 'LE.le (list 'cnodes v1) 'k1)
                            'hchk :- (list 'Eq 'Bool (list 'chkf pv1 '(encTy X)) 'Bool.true)
                            'hpf :- (list 'Eq 'Bool (list 'riPf 'ri v1) 'Bool.true)])))
  (concl 'X '(Exp.refl X r e)))
  ['(have hbase (And (Eq Bool (isBaseTy X) Bool.true) (Eq Bool (closedTy X) Bool.true)) (base_is_base X cd hb))
   (list 'have 'hsz (list 'Eq 'Nat (list 'cnodes pv1) (list 'cnodes v1)) (list 'rl_nodes 'ri 'hrl v1 'hpf))
   (list 'have 'hC1 (list 'Exists (list 'fn '[mm :- Nat] (list 'Exists (list 'fn '[tt :- Exp] (list 'Exists (list 'fn '[AA :- Exp] (C1body 'mm 'tt 'AA)))))))
      (list '(And.left hcs) pv1 '(encTy X) 'hchk))
   '(refine' (exT Nat _ _ hC1 _)) '(intro mm hm) '(refine' (exT Exp _ _ hm _)) '(intro tt htt) '(refine' (exT Exp _ _ htt _)) '(intro AA hAA)
   (list 'have 'q (C1body 'mm 'tt 'AA) 'hAA)
   '(have eA (Eq Exp AA X) ((And.right (And.right (And.right hcs))) AA X (And.left (And.right (And.right (And.right q)))) (And.right hbase)
                            (And.left (And.right (And.right (And.right (And.right q)))))))
   '(have hRtX (Rt chkf (thetaD mm) (thetaU mm) tt X) (Eq.mp (congrArg (fn [Z :- Exp] (Rt chkf (thetaD mm) (thetaU mm) tt Z)) eA) (And.left (And.right q))))
   (list 'have 'hmv (list 'LT.lt 'mm (list 'cnodes v1))
      (list 'lt_of_lt_eq 'mm (list 'cnodes pv1) (list 'cnodes v1) '(And.right (And.right (And.right (And.right (And.right q))))) 'hsz))
   (list 'have 'har (list 'And '(LE.le mm k) (list 'And '(LT.lt mm n) (list 'LE.le (list 'cnodes v1) 'n)))
      (list 'refl_arith 'mm (list 'cnodes v1) 'k1 'k2 'k 'n 'hmv 'vr 'hkk 'hk))
   (list 'have 'hc (list 'Eq 'Bool (list 'Bool.and (list 'Nat.ble (list 'cnodes v1) 'n) (list 'Bool.and (list 'riPf 'ri v1) (list 'chkf pv1 '(encTy X)))) 'Bool.true)
      (list 'bool_and3_true (list 'Nat.ble (list 'cnodes v1) 'n) (list 'riPf 'ri v1) (list 'chkf pv1 '(encTy X))
            (list 'Nat.ble_eq_true_of_le '(And.right (And.right har))) 'hpf 'hchk))
   '(rw [(den_refl_some_ri chkf dec encTy ri n X r e (skels D) (skel X) en mm tt AA hc (And.left q))])
   '(rw [(coe_self (skel X) (denPrev_ri chkf dec encTy ri n mm tt (thetaSk mm) (skel X) (tokenEnv mm)))])
   '(rw [(congrArg (fn [f :- DenBody] (f (thetaSk mm) (skel X) (tokenEnv mm))) (denPrev_stable_ri chkf dec encTy ri n mm tt (And.left (And.right har))))])
   '(rw [(tok_transfer mm (den_ri chkf dec encTy ri mm tt) (skel X))])
   (list 'have 'vo (list 'V_ri 'chkf 'dec 'encTy 'ri 'mm 'X '(skels (thetaD mm)) '(tokEnvD mm) 'mm '(skel X) run)
      '(hout mm (And.left (And.right har)) tt X hRtX))
   (list 'exact (list 'Lemma_3_4_ri 'chkf 'dec 'encTy 'ri 'X 'mm 'n 'k '(skels (thetaD mm)) '(skels D) '(tokEnvD mm) 'en '(skel X) run
                      '(And.left hbase) '(And.left har) 'vo))]))
;; The branch with a phantom: ⟦reflect⟧ is the default, in V(X) for X ≠ 0;
;; X = 0 would make the print of ⟦r⟧ an accepted refutation, against PhCons.
(eval (list 'lcert.formal.base/thm 'refl_ph_ri
  (into P6 (into '[X :- Exp, cd :- Exp, r :- Exp, e :- Exp,
                   hb :- (Eq (Option Exp) (baseCode X) (Option.some Exp cd)),
                   hrl :- (RLaws ri), hph :- (PhCons chkf encTy ri)]
                 (into ENV ['hchk :- (list 'Eq 'Bool (list 'chkf pv1 '(encTy X)) 'Bool.true)
                            'hpf :- (list 'Eq 'Bool (list 'riPf 'ri v1) 'Bool.false)])))
  (concl 'X '(Exp.refl X r e))
  '(rw [(den_refl_none_ri chkf dec encTy ri n X r e (skels D) (skel X) en hpf)])
  (list 'exact (list 'V_dflt_ri 'chkf 'dec 'encTy 'ri 'hrl 'n '(skels D) 'en 'k 'X 'cd 'hb
                     (list 'fn '[hX :- (Eq Exp X Exp.tEmpty)]
                           (list '(And.left hph) v1 'hpf
                                 (list 'Eq.mp (list 'congrArg (list 'fn '[Z :- Exp] (list 'Eq 'Bool (list 'chkf pv1 '(encTy Z)) 'Bool.true)) 'hX) 'hchk)))))))
(eval (concat (list 'lcert.formal.base/thm 'F_refl_ri
  (into P6 (into '[us1 :- (List U), us2 :- (List U), X :- Exp, cd :- Exp, r :- Exp, e :- Exp,
                   hb :- (Eq (Option Exp) (baseCode X) (Option.some Exp cd)),
                   hcs :- (CheckSpec chkf dec encTy), hout :- (OuterIH_ri chkf dec encTy ri n),
                   hrl :- (RLaws ri), hph :- (PhCons chkf encTy ri)]
                 (into ['ihr :- (SND 'us1 'r 'Exp.tR) 'ihe :- (SND 'us2 'e '(chkT r cd))]
                       (conj ENV 'hs :- (ES '(vadd us1 us2) 'k)))))
  (concl 'X '(Exp.refl X r e)))
  (concat
    (split-steps 'hs 'us1 'us2 'k 'k1 'k2 'p)
    ['(have hkn (Nat.le (+ k1 k2) n) (Nat.le_trans (And.left p) hk))
     '(have hk1 (Nat.le k1 n) (Nat.le_trans (Nat.le_add_right k1 k2) hkn))
     '(have hk2 (Nat.le k2 n) (Nat.le_trans (Nat.le_add_left k2 k1) hkn))
     (list 'have 'vr (list 'LE.le (list 'cnodes v1) 'k1) '(And.left (ihr en k1 hk1 (And.left (And.right p)))))
     '(have ve (V_ri chkf dec encTy ri n (chkT r cd) (skels D) en k2 Sk.unit (den_ri chkf dec encTy ri n e (skels D) Sk.unit en))
        (ihe en k2 hk2 (And.right (And.right p))))
     (list 'have 'hchk0 (list 'Eq 'Bool (list 'chkf pv1 '(den_ri chkf dec encTy ri n cd (skels D) Sk.syn en)) 'Bool.true)
        '(chk_true_ri chkf dec encTy ri n (skels D) en k2 r cd (den_ri chkf dec encTy ri n e (skels D) Sk.unit en) ve))
     '(have hcdv (Eq Code (den_ri chkf dec encTy ri n cd (skels D) Sk.syn en) (encTy X))
        (base_den_ri chkf dec encTy ri n (And.left (And.right hcs)) X cd hb (skels D) en))
     (list 'have 'hchk (list 'Eq 'Bool (list 'chkf pv1 '(encTy X)) 'Bool.true)
        (list 'Eq.mp (list 'congrArg (list 'fn '[q :- Code] (list 'Eq 'Bool (list 'chkf pv1 'q) 'Bool.true)) 'hcdv) 'hchk0))
     (list 'exact (list 'bool_case (list 'fn '[b :- Bool] (concl 'X '(Exp.refl X r e))) (list 'riPf 'ri v1)
                        (list 'fn ['hpf :- (list 'Eq 'Bool (list 'riPf 'ri v1) 'Bool.true)]
                              '(refl_pf_ri chkf dec encTy ri n D X cd r e hb hcs hout hrl en k hk k1 k2 (And.left p) vr hchk hpf))
                        (list 'fn ['hpf :- (list 'Eq 'Bool (list 'riPf 'ri v1) 'Bool.false)]
                              '(refl_ph_ri chkf dec encTy ri n D X cd r e hb hrl hph en k hk hchk hpf))))])))

;; --- H₁ ------------------------------------------------------------------------------

;; H₁ (the paper's case): the two IHs force chk′ (print ⟦r⟧) ⌜c⌝ and
;; chk′ (print ⟦s⟧) (neg ⌜c⌝); CheckSpec decodes them to Θₘ₁ ⊢ t₁ : A and
;; Θₘ₂ ⊢ t₂ : B with ⌜B⌝ = neg ⌜A⌝ = ⌜A ⊸ 0⌝ (E5), so B = A ⊸ 0 (E1);
;; Lemma 2.4 composes them into Θₘ₁₊ₘ₂ ⊢ t₂ t₁ : 0 with m₁ + m₂ < n; the
;; outer hypothesis puts its value in V(0) = ∅.  So no environment
;; satisfies the premises: the case is vacuous.

(thm den_negT_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                 c :- Exp, G :- (List Sk), en :- (HEnv G)]
  (Eq Code (den_ri chkf dec encTy ri n (negT c) G Sk.syn en) (Code.sn 25 (den_ri chkf dec encTy ri n c G Sk.syn en) (Code.sl 15)))
  (change (Eq Code (den_ri chkf dec encTy ri n (Exp.snode (Exp.lbl 25) c (Exp.sleaf (Exp.lbl 15))) G Sk.syn en) (Code.sn 25 (den_ri chkf dec encTy ri n c G Sk.syn en) (Code.sl 15))))
  (rw [(den_snode_at_ri chkf dec encTy ri n (Exp.lbl 25) c (Exp.sleaf (Exp.lbl 15)) G Sk.syn en)])
  (rw [(den_lbl_eq_ri chkf dec encTy ri n 25) (den_sleaf_eq_ri chkf dec encTy ri n (Exp.lbl 15)) (den_lbl_eq_ri chkf dec encTy ri n 15)]))
;; (le_chain1: the standard constant is used)
;; (le_chain2: the standard constant is used)
;; (le_chain4: the standard constant is used)
;; (le_chain5: the standard constant is used)
;; (le_assoc: the standard constant is used)
;; (h1_arith: the standard constant is used)
(def ^:private vv '(den_ri chkf dec encTy ri n r (skels D) Sk.cert en))
(def ^:private ww '(den_ri chkf dec encTy ri n s (skels D) Sk.cert en))
(def ^:private dc '(den_ri chkf dec encTy ri n c (skels D) Sk.syn en))
(defn- Cb [cv dv mm tt AA] (list 'And (list 'Eq '(Option (Prod Nat (Prod Exp Exp))) (list 'dec cv) (list 'Option.some '(Prod Nat (Prod Exp Exp)) (list 'Prod.mk mm (list 'Prod.mk tt AA))))
                     (list 'And (list 'Rt 'chkf (list 'thetaD mm) (list 'thetaU mm) tt AA)
                     (list 'And (list 'Tl 'chkf 'Bool.true '(List.nil Exp) AA 'Exp.tUnit)
                     (list 'And (list 'Eq 'Bool (list 'closedTy AA) 'Bool.true)
                     (list 'And (list 'Eq 'Code (list 'encTy AA) dv) (list 'Nat.lt mm (list 'cnodes cv))))))))
(defn- Cex [cv dv] (list 'Exists (list 'fn '[mm :- Nat] (list 'Exists (list 'fn '[tt :- Exp] (list 'Exists (list 'fn '[AA :- Exp] (Cb cv dv 'mm 'tt 'AA))))))))
(def ^:private ndc (list 'Code.sn 25 dc '(Code.sl 15)))
(defn- gets [q i] ;; i-th conjunct of Cb (0-based, 5 = last)
  (let [f (fn f [x j] (if (zero? j) (list 'And.left x) (f (list 'And.right x) (dec j))))]
    (if (= i 5) (list 'And.right (list 'And.right (list 'And.right (list 'And.right (list 'And.right q))))) (f q i))))
;; RI: H₁ over ri.  The IHs force the check on the prints of ⟦r⟧ and ⟦s⟧, at
;; ⌜c⌝ and neg ⌜c⌝.  If both trees are phantom-free, their prints have their
;; node counts (L3), and h1_core_ri is §3.5's argument: decode both, compose
;; by Lemma 2.4 at m₁ + m₂ < k₁ + k₂ ≤ n, and the outer hypothesis puts a
;; value in V(0) = ∅.  If one has a phantom, PhCons excludes the pair.
(thm h1_split_arith [k1 :- Nat, m1 :- Nat, k2 :- Nat, m2 :- Nat, k :- Nat, n :- Nat,
                     o1 :- (LE.le (+ k1 m1) k), o2 :- (LE.le (+ k2 m2) m1), hk :- (LE.le k n)]
  (LE.le (+ k1 k2) n) (omega))
(thm h1_lt_arith [ma :- Nat, c1 :- Nat, k1 :- Nat, mb :- Nat, c2 :- Nat, k2 :- Nat, n :- Nat,
                  a1 :- (LT.lt ma c1), a2 :- (LE.le c1 k1), b1 :- (LT.lt mb c2), b2 :- (LE.le c2 k2), hb :- (LE.le (+ k1 k2) n)]
  (LT.lt (+ ma mb) n) (omega))
(thm band_false_or [a :- Bool, b :- Bool] (=> (Eq Bool (Bool.and a b) Bool.false) (Or (Eq Bool a Bool.false) (Eq Bool b Bool.false)))
  (cases a)
  (intro h) (exact (Or.inl (Eq.refl$1 Bool.false)))
  (intro h) (exact (Or.inr h)))
(eval (list 'lcert.formal.base/thm 'h1_core_ri
  '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
    hcs :- (CheckSpec chkf dec encTy), hout :- (OuterIH_ri chkf dec encTy ri n),
    c1 :- Code, c2 :- Code, dc :- Code, k1 :- Nat, k2 :- Nat,
    hc1 :- (Eq Bool (chkf c1 dc) Bool.true), hc2 :- (Eq Bool (chkf c2 (Code.sn 25 dc (Code.sl 15))) Bool.true),
    b1 :- (LE.le (cnodes c1) k1), b2 :- (LE.le (cnodes c2) k2), hb :- (LE.le (+ k1 k2) n)]
  'False
  (list 'have 'X1 (Cex 'c1 'dc) '((And.left hcs) c1 dc hc1))
  '(refine' (exT Nat _ _ X1 _)) '(intro ma hma) '(refine' (exT Exp _ _ hma _)) '(intro ta hta) '(refine' (exT Exp _ _ hta _)) '(intro Aa hAa)
  (list 'have 'qa (Cb 'c1 'dc 'ma 'ta 'Aa) 'hAa)
  (list 'have 'X2 (Cex 'c2 '(Code.sn 25 dc (Code.sl 15))) '((And.left hcs) c2 (Code.sn 25 dc (Code.sl 15)) hc2))
  '(refine' (exT Nat _ _ X2 _)) '(intro mb hmb) '(refine' (exT Exp _ _ hmb _)) '(intro tb htb) '(refine' (exT Exp _ _ htb _)) '(intro Ab hAb)
  (list 'have 'qb (Cb 'c2 '(Code.sn 25 dc (Code.sl 15)) 'mb 'tb 'Ab) 'hAb)
  (list 'have 'hcl (list 'Eq 'Bool '(closedTy (Exp.tPi U.u1 Aa Exp.tEmpty)) 'Bool.true) (list 'andb_intro '(closedTy Aa) 'true (gets 'qa 3) '(Eq.refl$1 Bool.true)))
  (list 'have 'henc (list 'Eq 'Code '(encTy (Exp.tPi U.u1 Aa Exp.tEmpty)) '(encTy Ab))
     (list 'Eq.trans (list '(And.left (And.right (And.right hcs))) 'Aa (gets 'qa 3))
           (list 'Eq.trans (list 'congrArg '(fn [q :- Code] (Code.sn 25 q (Code.sl 15))) (gets 'qa 4)) (list 'Eq.symm (gets 'qb 4)))))
  (list 'have 'eB '(Eq Exp (Exp.tPi U.u1 Aa Exp.tEmpty) Ab) (list '(And.right (And.right (And.right hcs))) '(Exp.tPi U.u1 Aa Exp.tEmpty) 'Ab 'hcl (gets 'qb 3) 'henc))
  (list 'have 'hRtb '(Rt chkf (thetaD mb) (thetaU mb) tb (Exp.tPi U.u1 Aa Exp.tEmpty))
     (list 'Eq.mpr (list 'congrArg '(fn [Z :- Exp] (Rt chkf (thetaD mb) (thetaU mb) tb Z)) 'eB) (gets 'qb 1)))
  (list 'have 'hcomp '(Rt chkf (thetaD (+ ma mb)) (thetaU (+ ma mb)) (Exp.app (lift ma 0 tb) (lift mb ma ta)) Exp.tEmpty)
     (list 'lemma24 'chkf 'ma 'mb 'ta 'tb 'Aa (gets 'qa 3) (gets 'qa 2) (gets 'qa 1) 'hRtb))
  (list 'have 'hlt '(LT.lt (+ ma mb) n) (list 'h1_lt_arith 'ma '(cnodes c1) 'k1 'mb '(cnodes c2) 'k2 'n (gets 'qa 5) 'b1 (gets 'qb 5) 'b2 'hb))
  '(exact (hout (+ ma mb) hlt (Exp.app (lift ma 0 tb) (lift mb ma ta)) Exp.tEmpty hcomp))))
(def ^:private pvv (list 'riPr 'ri vv))
(def ^:private pww (list 'riPr 'ri ww))
(eval (concat (list 'lcert.formal.base/thm 'F_h1_ri
  (into P6 (into '[us1 :- (List U), us2 :- (List U), us3 :- (List U), us4 :- (List U), us5 :- (List U),
                   r :- Exp, s :- Exp, c :- Exp, e1 :- Exp, e2 :- Exp,
                   hcs :- (CheckSpec chkf dec encTy), hout :- (OuterIH_ri chkf dec encTy ri n),
                   hrl :- (RLaws ri), hph :- (PhCons chkf encTy ri)]
                 (into ['ihr :- (SND 'us1 'r 'Exp.tR) 'ihs :- (SND 'us2 's 'Exp.tR)
                        'ih1 :- (SND 'us4 'e1 '(chkT r c)) 'ih2 :- (SND 'us5 'e2 '(chkT s (negT c)))]
                       (conj ENV 'hs :- (ES '(vadd us1 (vadd us2 (vadd (vscale U.uw us3) (vadd us4 us5)))) 'k)))))
  (concl 'Exp.tEmpty '(Exp.h1 r s c e1 e2)))
  (concat
    (split-steps 'hs 'us1 '(vadd us2 (vadd (vscale U.uw us3) (vadd us4 us5))) 'k 'k1 'm1 'p1)
    (split-steps '(And.right (And.right p1)) 'us2 '(vadd (vscale U.uw us3) (vadd us4 us5)) 'm1 'k2 'm2 'p2)
    (split-steps '(And.right (And.right p2)) '(vscale U.uw us3) '(vadd us4 us5) 'm2 'k3 'm3 'p3)
    (split-steps '(And.right (And.right p3)) 'us4 'us5 'm3 'k4 'k5 'p4)
    ['(have o1 (LE.le (+ k1 m1) k) (And.left p1)) '(have o2 (LE.le (+ k2 m2) m1) (And.left p2))
     '(have o3 (LE.le (+ k3 m3) m2) (And.left p3)) '(have o4 (LE.le (+ k4 k5) m3) (And.left p4))
     '(have hk1 (Nat.le k1 n) (le_chain1 k1 m1 k n o1 hk))
     '(have hk2 (Nat.le k2 n) (le_chain2 k1 m1 k2 m2 k n o1 o2 hk))
     '(have hk4 (Nat.le k4 n) (le_chain4 k1 m1 k2 m2 k3 m3 k4 k5 k n o1 o2 o3 o4 hk))
     '(have hk5 (Nat.le k5 n) (le_chain5 k1 m1 k2 m2 k3 m3 k4 k5 k n o1 o2 o3 o4 hk))
     (list 'have 'vr (list 'LE.le (list 'cnodes vv) 'k1) '(And.left (ihr en k1 hk1 (And.left (And.right p1)))))
     (list 'have 'vs (list 'LE.le (list 'cnodes ww) 'k2) '(And.left (ihs en k2 hk2 (And.left (And.right p2)))))
     (list 'have 'hc1 (list 'Eq 'Bool (list 'chkf pvv dc) 'Bool.true)
        '(chk_true_ri chkf dec encTy ri n (skels D) en k4 r c (den_ri chkf dec encTy ri n e1 (skels D) Sk.unit en) (ih1 en k4 hk4 (And.left (And.right p4)))))
     (list 'have 'hc2a (list 'Eq 'Bool (list 'chkf pww '(den_ri chkf dec encTy ri n (negT c) (skels D) Sk.syn en)) 'Bool.true)
        '(chk_true_ri chkf dec encTy ri n (skels D) en k5 s (negT c) (den_ri chkf dec encTy ri n e2 (skels D) Sk.unit en) (ih2 en k5 hk5 (And.right (And.right p4)))))
     (list 'have 'hc2 (list 'Eq 'Bool (list 'chkf pww ndc) 'Bool.true)
        (list 'Eq.mp (list 'congrArg (list 'fn '[q :- Code] (list 'Eq 'Bool (list 'chkf pww 'q) 'Bool.true)) '(den_negT_ri chkf dec encTy ri n c (skels D) en)) 'hc2a))
     (list 'refine' (list 'bool_case (list 'fn '[b :- Bool] (concl 'Exp.tEmpty '(Exp.h1 r s c e1 e2)))
                          (list 'Bool.and (list 'riPf 'ri vv) (list 'riPf 'ri ww)) '_ '_))
     ;; both phantom-free: the budget descends (§3.5)
     '(intro hpf)
     (list 'have 'hv (list 'Eq 'Bool (list 'riPf 'ri vv) 'Bool.true) (list 'band_left (list 'riPf 'ri vv) (list 'riPf 'ri ww) 'hpf))
     (list 'have 'hw (list 'Eq 'Bool (list 'riPf 'ri ww) 'Bool.true) (list 'band_right (list 'riPf 'ri vv) (list 'riPf 'ri ww) 'hpf))
     (list 'have 'bv (list 'LE.le (list 'cnodes pvv) 'k1)
        (list 'Eq.mpr (list 'congrArg '(fn [z :- Nat] (LE.le z k1)) (list 'rl_nodes 'ri 'hrl vv 'hv)) 'vr))
     (list 'have 'bw (list 'LE.le (list 'cnodes pww) 'k2)
        (list 'Eq.mpr (list 'congrArg '(fn [z :- Nat] (LE.le z k2)) (list 'rl_nodes 'ri 'hrl ww 'hw)) 'vs))
     (list 'exact (list 'False.elim (list 'h1_core_ri 'chkf 'dec 'encTy 'ri 'n 'hcs 'hout pvv pww dc 'k1 'k2 'hc1 'hc2 'bv 'bw
                                         '(h1_split_arith k1 m1 k2 m2 k n o1 o2 hk))))
     ;; a phantom: PhCons
     '(intro hpf)
     (list 'exact (list 'False.elim (list '(And.right hph) vv ww dc (list 'band_false_or (list 'riPf 'ri vv) (list 'riPf 'ri ww) 'hpf) 'hc1 'hc2)))])))

;; --- Inspect ---------------------------------------------------------------------------

;; Inspect: ⟦insp X r c t₁ t₂⟧ runs t₁ or t₂, as chk′ (print ⟦r⟧) ⟦c⟧ is tt or
;; ff, at (⋆, (⟦r⟧, η)).  The chosen branch's context adds the certificate
;; (usage 1, footprint k₁, from r's IH) and a proof of the check or of its
;; negation (usage 1, footprint 0: T(b) is {⋆} exactly when b holds, which
;; the case split provides; insp_chk reads ⟦lift 1 0 c⟧ through den_weaken).
;; The branch's IH at lift 2 0 X is read as V(X) by V_lift2_fam.
;; (bool_case: the standard constant is used)

;; ⟦chk′ (print x) (lift c)⟧ at (v, η) is the check on v and ⟦c⟧η
(thm insp_chk_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                 G :- (List Sk), c :- Exp, hcS :- (SkJ Bool.false G c Sk.syn), v :- Code, en :- (HEnv G)]
  (Eq Bool (den_ri chkf dec encTy ri n (Exp.chk (Exp.prn (Exp.var 0)) (lift 1 0 c)) (List.cons Sk Sk.cert G) Sk.bool (Prod.mk v en))
           (chkf (riPr ri v) (den_ri chkf dec encTy ri n c G Sk.syn en))) ;; RI: inspect checks the print
  (rw [(den_chk_val_ri chkf dec encTy ri n (Exp.prn (Exp.var 0)) (lift 1 0 c) (List.cons Sk Sk.cert G) (Prod.mk v en))])
  (rw [(den_prn_val_ri chkf dec encTy ri n (Exp.var 0) (List.cons Sk Sk.cert G) (Prod.mk v en))])
  (rw [(den_var_at_ri chkf dec encTy ri n 0 (List.cons Sk Sk.cert G) Sk.cert (Prod.mk v en))])
  (rw [(den_weaken_ri chkf dec encTy ri n Bool.false G c Sk.syn hcS 0 Sk.cert en v)]))

(thm insp_not_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                 G :- (List Sk), c :- Exp, hcS :- (SkJ Bool.false G c Sk.syn), v :- Code, en :- (HEnv G),
                 hb :- (Eq Bool (chkf (riPr ri v) (den_ri chkf dec encTy ri n c G Sk.syn en)) Bool.false)] ;; RI
  (Eq Bool (den_ri chkf dec encTy ri n (notE (Exp.chk (Exp.prn (Exp.var 0)) (lift 1 0 c))) (List.cons Sk Sk.cert G) Sk.bool (Prod.mk v en)) Bool.true)
  (change (Eq Bool (den_ri chkf dec encTy ri n (Exp.ite (Exp.chk (Exp.prn (Exp.var 0)) (lift 1 0 c)) Exp.ff Exp.tt) (List.cons Sk Sk.cert G) Sk.bool (Prod.mk v en)) Bool.true))
  (rw [(den_ite_at_ri chkf dec encTy ri n (Exp.chk (Exp.prn (Exp.var 0)) (lift 1 0 c)) Exp.ff Exp.tt (List.cons Sk Sk.cert G) Sk.bool (Prod.mk v en))])
  (change (Eq Bool (Bool.rec$1 (fn [_ :- Bool] Bool) (den_ri chkf dec encTy ri n Exp.tt (List.cons Sk Sk.cert G) Sk.bool (Prod.mk v en))
                                (den_ri chkf dec encTy ri n Exp.ff (List.cons Sk Sk.cert G) Sk.bool (Prod.mk v en))
                                (den_ri chkf dec encTy ri n (Exp.chk (Exp.prn (Exp.var 0)) (lift 1 0 c)) (List.cons Sk Sk.cert G) Sk.bool (Prod.mk v en))) Bool.true))
  (rw [(insp_chk_ri chkf dec encTy ri n G c hcS v en) hb (den_tt_bool_ri chkf dec encTy ri n (List.cons Sk Sk.cert G) (Prod.mk v en))]))
(thm den_insp_val_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                     X :- Exp, r :- Exp, c :- Exp, t1 :- Exp, t2 :- Exp, G :- (List Sk), sk :- Sk, en :- (HEnv G)]
  (Eq (Car sk) (den_ri chkf dec encTy ri n (Exp.insp X r c t1 t2) G sk en)
     (Bool.rec$1 (fn [_ :- Bool] (Car sk))
        (den_ri chkf dec encTy ri n t2 (List.cons Sk Sk.unit (List.cons Sk Sk.cert G)) sk (Prod.mk Unit.unit (Prod.mk (den_ri chkf dec encTy ri n r G Sk.cert en) en)))
        (den_ri chkf dec encTy ri n t1 (List.cons Sk Sk.unit (List.cons Sk Sk.cert G)) sk (Prod.mk Unit.unit (Prod.mk (den_ri chkf dec encTy ri n r G Sk.cert en) en)))
        (chkf (riPr ri (den_ri chkf dec encTy ri n r G Sk.cert en)) (den_ri chkf dec encTy ri n c G Sk.syn en)))) ;; RI
  (rw [(den_insp_at_ri chkf dec encTy ri n X r c t1 t2 G sk en)]))

;; (insp_arith: the standard constant is used)
(def ^:private F1 '(chkT (Exp.var 0) (lift 1 0 c)))
(def ^:private F2 '(Exp.tT (notE (Exp.chk (Exp.prn (Exp.var 0)) (lift 1 0 c)))))
(def ^:private rvv '(den_ri chkf dec encTy ri n r (skels D) Sk.cert en))
(def ^:private dcv '(den_ri chkf dec encTy ri n c (skels D) Sk.syn en))
(def ^:private Ei (list 'Prod.mk 'Unit.unit (list 'Prod.mk rvv 'en)))
(def ^:private G3i '(List.cons Sk Sk.unit (List.cons Sk Sk.cert (skels D))))
(defn- tv [t s] (list 'den_ri 'chkf 'dec 'encTy 'ri 'n t G3i s Ei))
(def ^:private Ki '(+ 0 (+ k1 k2)))
(defn- branch-tac [ih F hEntry t]
  [(list 'have 'hsat (list 'EnvSat_ri 'chkf 'dec 'encTy 'ri 'n (list 'List.cons 'Exp F '(List.cons Exp Exp.tR D)) '(List.cons U U.u1 (List.cons U U.u1 us2)) Ei Ki)
         (list 'EnvSat_cons_ri 'chkf 'dec 'encTy 'ri 'n F '(List.cons Exp Exp.tR D) 'U.u1 '(List.cons U U.u1 us2) 'Unit.unit (list 'Prod.mk rvv 'en) 0 '(+ k1 k2)
               (list 'EnvSat_cons_ri 'chkf 'dec 'encTy 'ri 'n 'Exp.tR 'D 'U.u1 'us2 rvv 'en 'k1 'k2 'hs2 'vr) hEntry))
   (list 'have 'vt (list 'V_ri 'chkf 'dec 'encTy 'ri 'n '(lift 2 0 X) G3i Ei Ki '(skel (lift 2 0 X)) (tv t '(skel (lift 2 0 X))))
         (list ih Ei Ki '(And.left (And.right har)) 'hsat))
   (list 'have 'vt2 (list 'V_ri 'chkf 'dec 'encTy 'ri 'n 'X '(skels D) 'en Ki '(skel X) (tv t '(skel X)))
         (list 'V_lift2_fam_ri 'chkf 'dec 'encTy 'ri 'n '(skels D) 'X 'hXS 'Sk.cert 'Sk.unit 'en rvv 'Unit.unit Ki (list 'fn '[s :- Sk] (tv t 's)) 'vt))
   (list 'exact (list 'V_mono_ri 'chkf 'dec 'encTy 'ri 'n 'X '(skels D) 'en Ki 'k '(skel X) (tv t '(skel X)) '(And.left har) 'hk 'vt2))])
(eval (concat (list 'lcert.formal.base/thm 'F_insp_ri
  (into P6 (into '[us1 :- (List U), us0 :- (List U), us2 :- (List U), X :- Exp, r :- Exp, c :- Exp, t1 :- Exp, t2 :- Exp,
                   hc :- (Rt chkf D (vscale U.uw us0) c Exp.tSyn), hX :- (Tl chkf Bool.true D X Exp.tUnit)]
                 (into ['ihr :- (SND 'us1 'r 'Exp.tR)
                        'ih1 :- (list 'Sound_ri 'chkf 'dec 'encTy 'ri 'n (list 'List.cons 'Exp F1 '(List.cons Exp Exp.tR D)) '(List.cons U U.u1 (List.cons U U.u1 us2)) 't1 '(lift 2 0 X))
                        'ih2 :- (list 'Sound_ri 'chkf 'dec 'encTy 'ri 'n (list 'List.cons 'Exp F2 '(List.cons Exp Exp.tR D)) '(List.cons U U.u1 (List.cons U U.u1 us2)) 't2 '(lift 2 0 X))]
                       (conj ENV 'hs :- (ES '(vadd us1 (vadd (vscale U.uw us0) us2)) 'k)))))
  (concl 'X '(Exp.insp X r c t1 t2)))
  (concat
    ['(have hXS (SkJ Bool.true (skels D) X Sk.unit) (lemma25_tl_type chkf D X hX))
     '(have hcS (SkJ Bool.false (skels D) c Sk.syn) (lemma25_rt chkf D (vscale U.uw us0) c Exp.tSyn hc))
     '(rw [(den_insp_val_ri chkf dec encTy ri n X r c t1 t2 (skels D) (skel X) en)])]
    (split-steps 'hs 'us1 '(vadd (vscale U.uw us0) us2) 'k 'k1 'm1 'p1)
    (split-steps '(And.right (And.right p1)) '(vscale U.uw us0) 'us2 'm1 'k0 'k2 'p2)
    ['(have har (And (LE.le (+ 0 (+ k1 k2)) k) (And (LE.le (+ 0 (+ k1 k2)) n) (LE.le k1 n))) (insp_arith k1 m1 k0 k2 k n (And.left p1) (And.left p2) hk))
     '(have hs2 (EnvSat_ri chkf dec encTy ri n D us2 en k2) (And.right (And.right p2)))
     (list 'have 'vr (list 'And (list 'LE.le (list 'cnodes rvv) 'k1) (list 'Eq 'Bool (list 'lblOk (list 'riPr 'ri rvv)) 'Bool.true)) '(ihr en k1 (And.right (And.right har)) (And.left (And.right p1))))
     (list 'refine' (list 'bool_case (list 'fn '[b :- Bool] (list 'V_ri 'chkf 'dec 'encTy 'ri 'n 'X '(skels D) 'en 'k '(skel X)
                                             (list 'Bool.rec$1 '(fn [_ :- Bool] (Car (skel X))) (tv 't2 '(skel X)) (tv 't1 '(skel X)) 'b)))
                          (list 'chkf (list 'riPr 'ri rvv) dcv) '_ '_)) ;; RI: inspect checks the print
     '(intro hb)]
    (branch-tac 'ih1 F1 '(Eq.trans (insp_chk_ri chkf dec encTy ri n (skels D) c hcS (den_ri chkf dec encTy ri n r (skels D) Sk.cert en) en) hb) 't1)
    ['(intro hb)]
    (branch-tac 'ih2 F2 '(insp_not_ri chkf dec encTy ri n (skels D) c hcS (den_ri chkf dec encTy ri n r (skels D) Sk.cert en) en hb) 't2))))
