(ns lcert.formal.ri-subst
  "Generic copy of lcert.formal.subst over an R-interpretation ri : RInt (rint.clj;
  Theorem 4.6 design note §3), generated by formal/tools/gen_ri.py: the
  constants that depend on the model carry the suffix _ri and take ri after
  encTy.  Hand edits at the R-specific steps are marked `;; RI:`.  The
  standard namespace's documentation follows, with the same renaming.

  F3f — substitution into the model (R4-metatheory.md Lemmas 3.1 and 3.3).

  coe s s is the identity in both directions (coe_self, coe_rev): the
  denotation's variable clause is lookup followed by coe, and a typed
  variable's skeleton already matches, so the coercion disappears.

  envOf_ri n σ Gp G η is the environment Lemma 3.1 reads the source term in: the
  value of variable i is ⟦σ i⟧ⁿη.  Reflect's recursive call does not use it,
  since it runs a closed decoded program in tokenEnv.

  Written by the Grok agent (review F3s, 2026-09-27).  That run also found
  that Lemmas 3.1 and 3.3 failed for skeleton typing as it then stood, which
  admitted reflect at an open type; SkJ now requires a base data type, as the
  rule table does, and the counterexample no longer applies."
  (:require [lcert.formal.rint] [lcert.formal.ri-den] [lcert.formal.ri-sem]
            [ansatz.core :as a]
            [lcert.formal.base :refer [thm kdef]]
            [lcert.formal.usage :refer :all]
            [lcert.formal.syntax :refer :all]
            [lcert.formal.skel :refer :all]
            [lcert.formal.conv :refer :all]
            [lcert.formal.carrier :refer :all]
            [lcert.formal.den :refer :all]
            [lcert.formal.sem :refer :all]))

;; ---------------------------------------------------------------------------
;; coe s s = id, both directions (carrier.clj's coe / coePair).
;; One induction: the arrow case needs the domain's reverse map and the
;; codomain's forward map, and the product case needs both components.
;; ---------------------------------------------------------------------------

;; (coe_both: the standard constant is used)

;; Lemma used by every variable case of denotation: coe s s v = v.
;; (coe_self: the standard constant is used)

;; The reverse half of coePair s s, needed wherever a domain is precomposed
;; (the arrow clause of coeFrom_arr).
;; (coe_rev: the standard constant is used)

;; ---------------------------------------------------------------------------
;; envOf n σ Gp G η : HEnv Gp.
;; nil ↦ ⋆; (s :: rest) ↦ (⟦σ 0⟧ⁿ_G,s η, envOf n (i ↦ σ (i+1)) rest G η).
;; The list recursor is the structural recursion; σ and η stay in the
;; returned function, as with liftF / substF.
;; ---------------------------------------------------------------------------

(kdef envOf_ri
  (forall [chkf (=> Code Code Bool)]
    (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))]
      (forall [encTy (=> Exp Code) ri RInt]
        (forall [n Nat]
          (forall [Gp (List Sk)]
            (=> (=> Nat Exp) (forall [G (List Sk)] (=> (HEnv G) (HEnv Gp)))))))))
  (fn [chkf :- (=> Code Code Bool),
       dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))),
       encTy :- (=> Exp Code), ri :- RInt,
       n :- Nat,
       Gp :- (List Sk)]
    (List.rec$1$0 Sk
      (fn [Gp :- (List Sk)] (=> (=> Nat Exp) (forall [G (List Sk)] (=> (HEnv G) (HEnv Gp)))))
      (fn [sg :- (=> Nat Exp), G :- (List Sk), eta :- (HEnv G)] Unit.unit)
      (fn [s :- Sk, rest :- (List Sk),
           ih :- (=> (=> Nat Exp) (forall [G (List Sk)] (=> (HEnv G) (HEnv rest))))]
        (fn [sg :- (=> Nat Exp), G :- (List Sk), eta :- (HEnv G)]
          (Prod.mk (den_ri chkf dec encTy ri n (sg 0) G s eta)
                   (ih (fn [i :- Nat] (sg (+ i 1))) G eta))))
      Gp)))

(thm envOf_nil_ri [chkf :- (=> Code Code Bool),
                dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))),
                encTy :- (=> Exp Code), ri :- RInt,
                n :- Nat, sg :- (=> Nat Exp), G :- (List Sk), eta :- (HEnv G)]
  (= (envOf_ri chkf dec encTy ri n (List.nil Sk) sg G eta) Unit.unit)
  (rfl))

