(ns lcert.formal.ri-substitution
  "Generic copy of lcert.formal.substitution over an R-interpretation ri : RInt (rint.clj;
  Theorem 4.6 design note §3), generated by formal/tools/gen_ri.py: the
  constants that depend on the model carry the suffix _ri and take ri after
  encTy.  Hand edits at the R-specific steps are marked `;; RI:`.  The
  standard namespace's documentation follows, with the same renaming.

  F3h — weakening and substitution for the denotation
  (R4-metatheory.md §3.2 Lemma 3.1, §3.3 Lemma 3.3 substitution clause).

  Every statement is about the denotation of lcert.formal.den, for arbitrary
  parameters chkf (the checker), dec (the decoder of certificate trees) and
  encTy (the type encoding), at every budget n (den_ri n := denT_ri n n).  Most
  theorems are first proved for one level of the table, `denAt_ri chkf dec
  encTy ri pv cp` with an arbitrary lower table pv : DenFn and cap cp, and then
  transferred to `den_ri n` by `den_eq_denAt_ri` (den_ri n is denAt_ri at its own lower
  table, denPrev_ri n).  This is possible because renaming and substitution
  never reach the lower table: reflect runs a CLOSED decoded program in
  tokenEnv (den_gen.clj, den_refl_ri), and reflect's type D is a base type,
  hence closed (SkJ's sRefl premise isBaseTy D).

  Contents.
  §1  Insertion into a skeleton context and an environment: insS c x G
      inserts skeleton x at position c of G; insE c x G η v inserts the
      value v at the same position of η.  Both are definitional on cons:
      insE (c+1) x (s :: G) (a, η) v ≡ (a, insE c x G η v).
  §2  Lookup (and nthS) in an extended context: below c unchanged, at or
      above c shifted by one (lookup_ins_below, lookup_ins_above,
      nthS_ins_below, nthS_ins_above).
  §3  Skeleton inference commutes with lifting (skOf_lift), and on a
      skeleton-typed term returns either none or the typed skeleton
      (skOf_typed).  Application and let read skOf of a subterm, so these
      two facts are what the app and letp cases need.
  §4  Item 1, weakening (the renaming half of Lemma 3.1): for any SkJ
      derivation G ⊢ u : s,
        ⟦lift 1 c u⟧ (insS c x G) (insE c x G η v) = ⟦u⟧ G η,
      `denAt_weaken_ri` (one level) and `den_weaken_ri` (every budget n).  One
      case lemma per SkJ rule (wk_<rule>), dispatched by induction over the
      derivation.
  §5  Lemma 3.1 as stated over skeleton typing is FALSE for this
      denotation: `lemma31_skj_counterexample_ri` (kernel-checked).  A branch
      list (bnil / bcons) is skeleton-typed at Lbl → s, but skOf returns
      none on it, so the application clause of ⟦·⟧ defaults when a branch
      list is substituted for a variable in argument position:
        t = (λ(y : Π(l:Lbl).Nat). y) x   in x : Lbl → Nat,
        u = bcons (succ zero) bnil        (the branch list 0 ↦ 1),
        ⟦t[u/x]⟧ 0 = 0  but  ⟦t⟧(x ↦ ⟦u⟧) 0 = 1.
      The real typing judgment never places a branch list in argument
      position (its type is the pseudo-type tBrs, which no binder has), so
      the substitution lemma holds with the additional hypothesis that
      skOf of every substituted term is its skeleton (SubOK, §7).
  §6  Skeleton typing is closed under weakening (skj_weaken), so the
      substitution shifted under a binder is again typed.
  §7  The environment of a substitution (envAt, = envOf_ri at den_ri n), the
      hypotheses SubOK on a substitution, and their behaviour under a
      binder (subOK_up, envAt_up_ri), skOf under substitution (skOf_subst).
  §8  Item 2, Lemma 3.1: for Gp ⊢ t : s and SubOK Gp σ G,
        ⟦subst σ t⟧ G s η = ⟦t⟧ Gp s (envOf_ri n Gp σ G η)
      (denAt_subst_ri at one level, lemma31_ri at every budget n).
  §9  Item 3, Lemma 3.3's substitution clause: for Gp ⊢ A type and
      SubOK Gp σ G, V_ri n (subst σ A) G η k (skel A) v ↔
      V_ri n A Gp (envOf_ri n Gp σ G η) k (skel A) v (V_subst_ri, lemma33_subst_ri).
  §10 Item 4, corollaries at the natural environments, for den_ri and V:
      subst1 u (β, B[u/x]):  den_subst1_ri, V_subst1_ri — the environment is
      (⟦u⟧ⁿη, η);  substL us (let, recN, recSyn):  den_substL_ri, V_substL_ri —
      the environment is the values of us in front of η (envL_ri), with the
      let instance den_substL2_ri.  Each substituted term u : s must satisfy
      skOf G u = some s (not a branch list), as §5 requires.

  Deviations from the paper, all forced (see §5):
  - Lemma 3.1's substitutions carry skOf-faithfulness (SubOK).
  - Lemma 3.3's substitution clause is stated at the skeleton skel A (the
    skeleton the model uses V_ri at), not at every skeleton.

  Proof technique.  Each case lemma is one explicit proof term: a chain of
  Eq.trans/congrArg steps (`cong`), one step per recursive call of the
  denotation clause, with funext under the clause's own binders.  The
  terms are generated from short templates (`expand`); the generator is not
  trusted, since every term is checked by the kernel against the goal,
  which the kernel unfolds (denAt_ri, the den_<ctor> clause, liftF, insS,
  insE) by definitional reduction."
  (:require [lcert.formal.rint] [lcert.formal.ri-den] [lcert.formal.ri-sem] [lcert.formal.ri-subst] [lcert.formal.ri-unfold]
            [ansatz.core :as a]
            [clojure.walk :as walk]
            [lcert.formal.base :refer [thm kdef lv]]
            [lcert.formal.usage :refer :all]
            [lcert.formal.syntax :refer :all]
            [lcert.formal.skel :refer :all]
            [lcert.formal.conv :refer :all]
            [lcert.formal.carrier :refer :all]
            [lcert.formal.den :refer :all]
            [lcert.formal.sem :refer :all]
            [lcert.formal.subst :refer :all]
            [lcert.formal.skeletons :refer :all]
            [lcert.formal.unfold]))

;; The constructor table of lcert.formal.syntactic ([ctor [[field type
;; binder-depth] ...]], in Exp's constructor order), for inductions over Exp.
(def ^:private exp-fields @#'lcert.formal.syntactic/exp-fields)

;; SkJ's rules in constructor order: `induction` over a derivation leaves
;; one goal per rule, in this order (checked with peek).
(def ^:private skj-rules
  '[wEmpty wUnit wBool wNat wLbl wSyn wDia wR wT wPi wSig sVar sStar sAbort sTT sFF sIte sElimB sZero sSucc
    sRecN sLbl sCaseL sBnil sBcons sSleaf sSnode sRecS sLeaf sNode sItR sPrn sLam sApp sPair sLetp sChk sH1 sRefl sInsp])

;; ===========================================================================
;; §1  Insertion into skeleton contexts and environments
;; ===========================================================================

;; insS c x G: G with x inserted at position c (innermost first), i.e. the
;; context of `lift 1 c`.  Recursion on c, returning a function of G (so the
;; kernel sees a plain Nat.rec); past the end of G nothing is inserted, which
;; keeps lookups beyond the context equal (both are defaults / none).
;; (insSF: the standard constant is used)

;; (insS: the standard constant is used)

;; (insS_zero: the standard constant is used)
;; (insS_succ_cons: the standard constant is used)
;; (insS_succ_nil: the standard constant is used)

;; insE c x G η v : HEnv (insS c x G): η with v inserted at position c.
;; Nat.rec on c, then List.rec on G, so that on a cons the equation
;; insE (c+1) x (s :: G) (a, η) v = (a, insE c x G η v) is definitional.
;; (InsET: the standard constant is used)

;; (insEF: the standard constant is used)

;; (insE: the standard constant is used)

;; (insE_zero: the standard constant is used)
;; (insE_succ_cons: the standard constant is used)

;; ===========================================================================
;; §2  Lookup in an extended context
;; ===========================================================================

;; The core statements are by induction with the index written so that it
;; reduces against insS: above the insertion point, index j + c + 1 of the
;; extended context is index j + c of the original; below it, index i of a
;; context extended at d + i + 1 is unchanged.
;; (lookup_ins_above_core: the standard constant is used)

;; (lookup_ins_below_core: the standard constant is used)

;; The forms the variable case uses (lift_var_above / lift_var_below): the
;; index is rewritten into the core form with Nat.sub_add_cancel.
;; (lookup_ins_above: the standard constant is used)

;; (lookup_ins_below: the standard constant is used)

;; The same for nthS.  nthS recurses on two arguments, so Ansatz defines it
;; by well-founded recursion; it is unfolded through its equation lemmas
;; nthS.eq_1 (nil), nthS.eq_2 (cons, 0), nthS.eq_3 (cons, i+1).
;; (nthS_ins_above_core: the standard constant is used)

;; (nthS_ins_below_core: the standard constant is used)

;; (nthS_ins_above: the standard constant is used)

;; (nthS_ins_below: the standard constant is used)

;; ===========================================================================
;; §3  Skeleton inference: lifting, and typed terms
;; ===========================================================================

;; skOf's λ and application clauses, as named functions of the recursive
;; result (both sides of each equation are the same match, so rfl).
;; (lamSk: the standard constant is used)
;; (appSk: the standard constant is used)

;; (skOf_lam_eq: the standard constant is used)
;; (skOf_app_eq: the standard constant is used)

;; (skOf_lift_var: the standard constant is used)

;; Constructors whose skOf is `some (skel F)` for the field F, lifted under
;; k binders; skel commutes with lifting (skel_lift, lcert.formal.syntactic).
(def ^:private skel-field '{abort [A 0] elimB [P 1] recN [P 1] caseL [P 1] recS [P 1] itR [X 0]
                            pair [S 0] letp [C 0] refl [D 0] insp [X 0]})

(defn- skof-lift-case [ctor]
  (cond
    (= ctor 'var) '[(exact (skOf_lift_var xs cu G i))]
    (= ctor 'ite) '[(exact (ih_t cu xs G))]
    (= ctor 'lam)
    '[(exact (Eq.trans (skOf_lam_eq (insS cu xs G) r (lift 1 cu A) (lift 1 (+ cu 1) t))
               (Eq.trans (congrArg (fn [q :- Sk] (lamSk q (skOf (List.cons Sk q (insS cu xs G)) (lift 1 (+ cu 1) t)))) (skel_lift A 1 cu))
                 (Eq.trans (congrArg (fn [o :- (Option Sk)] (lamSk (skel A) o)) (ih_t (+ cu 1) xs (List.cons Sk (skel A) G)))
                   (Eq.symm (skOf_lam_eq G r A t))))))]
    (= ctor 'app)
    '[(exact (Eq.trans (skOf_app_eq (insS cu xs G) (lift 1 cu f) (lift 1 cu u))
               (Eq.trans (congrArg appSk (ih_f cu xs G)) (Eq.symm (skOf_app_eq G f u)))))]
    (skel-field ctor)
    (let [[F k] (skel-field ctor)]
      [(list 'exact (list 'congrArg '(fn [q :- Sk] (Option.some Sk q))
                          (list 'skel_lift F 1 (if (zero? k) 'cu (list '+ 'cu k)))))])
    ;; every other clause is a constant
    :else '[(rfl)]))

;; skOf commutes with weakening, for every expression (no typing needed).
;; (skOf_lift: the standard constant is used)

;; (skOK_lam: the standard constant is used)

;; (skOK_app: the standard constant is used)

;; On a skeleton-typed expression skOf never returns a WRONG skeleton: it is
;; none (types, branch lists, and terms whose skOf-spine ends in one) or the
;; typed skeleton.  So the app and letp clauses of ⟦·⟧ either default on
;; both sides of an equation or use the typed skeleton on both.
(defn- skok-case [rule]
  (case rule
    (wEmpty wUnit wBool wNat wLbl wSyn wDia wR wT wPi wSig sBnil sBcons) '[(apply Or.inl) (rfl)]
    sVar '[(exact (Or.inr h))]
    sIte '[(exact ih_ht)]
    sLam '[(exact (skOK_lam G r A t s ih_ht))]
    sApp '[(exact (skOK_app G f u s t ih_hf))]
    '[(apply Or.inr) (rfl)]))

;; (skOf_typed: the standard constant is used)

;; Congruence for the Option.rec of the app and letp clauses: equal
;; scrutinees that are none or some s, and equal branches at s.
;; (optrec_congr: the standard constant is used)

;; reflect's type is a base type, which lifting (and substitution) fixes.
(def ^:private base-ctors '#{tEmpty tUnit tBool tNat tLbl tSyn tR})

;; (lift_base: the standard constant is used)

;; ===========================================================================
;; §4  Item 1: weakening (renaming by one insertion)
;; ===========================================================================

;; --- proof-term generation ---------------------------------------------------
;; Names used in every case lemma: the denotation parameters chkf dec encTy ri,
;; the lower table pv and cap cp; the cut cu, the inserted skeleton xs, the
;; environment en and the inserted value vx.  (Rule fields named c, x, s, h,
;; v exist, so the motive's own names avoid them.)

(def ^:private dparams
  '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, pv :- DenFn, cp :- Nat])

(defn- D [e G s en] (list 'denAt_ri 'chkf 'dec 'encTy 'ri 'pv 'cp e G s en))
(defn- cut [k] (if (= k 0) 'cu (list '+ 'cu k)))

;; The motive of item 1 for G ⊢ e : s.
(defn- WK [G e s]
  (list 'forall '[cu Nat] (list 'forall '[xs Sk] (list 'forall ['en (list 'HEnv G)] (list 'forall '[vx (Car xs)]
    (list '= (D (list 'lift 1 'cu e) (list 'insS 'cu 'xs G) s (list 'insE 'cu 'xs G 'en 'vx)) (D e G s 'en)))))))

(defn- cong
  "A chain of congrArg steps rewriting, left to right, each hole of `tmpl`
  (the symbols q1, q2, …) from its left to its right value.  A hole is
  [type left right proof-of-left=right]."
  [tmpl holes]
  (let [holes (vec holes) n (count holes) lhs (mapv second holes) rhs (mapv #(nth % 2) holes)
        qs (mapv #(symbol (str "q" (inc %))) (range n))
        inst (fn [vals] (walk/postwalk-replace (zipmap qs vals) tmpl))
        steps (for [i (range n)]
                (let [[ty _ _ pf] (holes i)]
                  (list 'congrArg (list 'fn ['qq ':- ty] (inst (vec (concat (take i rhs) ['qq] (drop (inc i) lhs))))) pf)))]
    (reduce (fn [acc st] (list 'Eq.trans acc st)) steps)))

(defn- expand
  "Expand the abbreviations of the case terms:
    (%WK G e s)     the motive;           (%D e G s en)  denAt_ri at one level;
    (%H f G s ih)   hole: subterm f in the same context and environment;
    (%HB [binders] f k G2 s en2 ih)
                    hole: subterm f under the clause's binders, at cut cu+k,
                    in context G2 with environment en2 (funext per binder);
    (%CONG tmpl hole…)  the congruence chain."
  [form]
  (walk/postwalk
   (fn [x]
     (if (seq? x)
       (case (first x)
         %WK (apply WK (rest x))
         %D (apply D (rest x))
         %H (let [[_ f G s ih] x]
              [(list 'Car s) (D (list 'lift 1 'cu f) (list 'insS 'cu 'xs G) s (list 'insE 'cu 'xs G 'en 'vx)) (D f G s 'en)
               (list ih 'cu 'xs 'en 'vx)])
         %HB (let [[_ binders f k G2 s en2 ih] x
                   vars (take-nth 3 binders)
                   types (take-nth 3 (drop 2 binders))
                   ty (concat ['=>] types [(list 'Car s)])
                   body-l (D (list 'lift 1 (cut k) f) (list 'insS (cut k) 'xs G2) s (list 'insE (cut k) 'xs G2 en2 'vx))
                   body-r (D f G2 s en2)
                   pf (reduce (fn [acc [v t]] (list 'funext (list 'fn [v ':- t] acc)))
                              (list ih (cut k) 'xs en2 'vx)
                              (reverse (map vector vars types)))]
               (if (empty? binders)
                 [(list 'Car s) body-l body-r pf]
                 [ty (list 'fn binders body-l) (list 'fn binders body-r) pf]))
         %CONG (cong (second x) (drop 2 x))
         x)
       x))
   form))

(defn- case-thm! [nm params prop tactics]
  (a/prove-theorem nm (lv (expand (into dparams params))) (lv (expand prop)) (lv (expand tactics))))

;; A case whose clause is `tmpl` over the recursive calls `holes`.
(defn- simple-case! [nm params concl-e concl-s tmpl holes]
  (case-thm! nm params (list '%WK 'G concl-e concl-s)
             ['(intro cu xs en vx) (list 'exact (list* '%CONG tmpl holes))]))

;; --- the cases, one per SkJ rule with recursive calls ---------------------------
;; (Rules whose clause is a constant or a default — types, ⋆, tt, ff, zero,
;; labels, bnil, abort, H₁ — are closed by rfl in the induction below.)

;; sVar: lookup at the lifted index; the stored skeleton is read by lookup on
;; both sides, so no typing is used.
(case-thm! 'wk_var_ri '[G :- (List Sk), i :- Nat, s :- Sk]
  '(%WK G (Exp.var i) s)
  '[(intro cu xs en vx)
    (have hc (Decidable (Nat.lt i cu)) (Nat.decLt i cu))
    (cases hc)
    (rw [(lift_var_above 1 cu i (Nat.le_of_not_lt h))])
    (rw [(lift_var_below 1 cu i h)])
    (exact (lookup_ins_above xs vx cu i G s en (Nat.le_of_not_lt h)))
    (exact (lookup_ins_below xs vx cu i G s en h))])

;; sIte, sElimB: Bool.rec over the scrutinee (elimB's motive P is unused).
(simple-case! 'wk_ite_ri '[G :- (List Sk), b :- Exp, t :- Exp, e :- Exp, s :- Sk,
                        ih_hb :- (%WK G b Sk.bool), ih_ht :- (%WK G t s), ih_he :- (%WK G e s)]
  '(Exp.ite b t e) 's
  '(Bool.rec$1 (fn [_ :- Bool] (Car s)) q1 q2 q3)
  '[(%H e G s ih_he) (%H t G s ih_ht) (%H b G Sk.bool ih_hb)])

(simple-case! 'wk_elimB_ri '[G :- (List Sk), P :- Exp, b :- Exp, t :- Exp, e :- Exp,
                          ih_hb :- (%WK G b Sk.bool), ih_ht :- (%WK G t (skel P)), ih_he :- (%WK G e (skel P))]
  '(Exp.elimB P b t e) '(skel P)
  '(Bool.rec$1 (fn [_ :- Bool] (Car (skel P))) q1 q2 q3)
  '[(%H e G (skel P) ih_he) (%H t G (skel P) ih_ht) (%H b G Sk.bool ih_hb)])

(simple-case! 'wk_succ_ri '[G :- (List Sk), n :- Exp, ih_h :- (%WK G n Sk.nat)]
  '(Exp.succ n) 'Sk.nat
  '(coe Sk.nat Sk.nat (Nat.succ q1)) '[(%H n G Sk.nat ih_h)])

;; sRecN: Nat.rec; the step is under two binders (y, x), at cut cu+2.
(simple-case! 'wk_recN_ri '[G :- (List Sk), P :- Exp, z :- Exp, st :- Exp, n :- Exp,
                         ih_hz :- (%WK G z (skel P)), ih_hs :- (%WK (sk2 (skel P) Sk.nat G) st (skel P)), ih_hn :- (%WK G n Sk.nat)]
  '(Exp.recN P z st n) '(skel P)
  '(Nat.rec$1 (fn [_ :- Nat] (Car (skel P))) q1 q2 q3)
  '[(%H z G (skel P) ih_hz)
    (%HB [k :- Nat, acc :- (Car (skel P))] st 2 (sk2 (skel P) Sk.nat G) (skel P) (Prod.mk acc (Prod.mk k en)) ih_hs)
    (%H n G Sk.nat ih_hn)])

(simple-case! 'wk_caseL_ri '[G :- (List Sk), P :- Exp, x :- Exp, bs :- Exp,
                          ih_hx :- (%WK G x Sk.lbl), ih_hb :- (%WK G bs (Sk.arr Sk.lbl (skel P)))]
  '(Exp.caseL P x bs) '(skel P)
  '(q1 q2) '[(%H bs G (Sk.arr Sk.lbl (skel P)) ih_hb) (%H x G Sk.lbl ih_hx)])

(simple-case! 'wk_bcons_ri '[G :- (List Sk), h :- Exp, t :- Exp, s :- Sk,
                          ih_hh :- (%WK G h s), ih_ht :- (%WK G t (Sk.arr Sk.lbl s))]
  '(Exp.bcons h t) '(Sk.arr Sk.lbl s)
  '(fn [v :- Nat] (Nat.rec$1 (fn [_ :- Nat] (Car s)) q1 (fn [k :- Nat, w :- (Car s)] (q2 (coe Sk.lbl Sk.lbl k))) (coe Sk.lbl Sk.lbl v)))
  '[(%H h G s ih_hh) (%H t G (Sk.arr Sk.lbl s) ih_ht)])

(simple-case! 'wk_sleaf_ri '[G :- (List Sk), x :- Exp, ih_h :- (%WK G x Sk.lbl)]
  '(Exp.sleaf x) 'Sk.syn
  '(coe Sk.syn Sk.syn (Code.sl q1)) '[(%H x G Sk.lbl ih_h)])

(simple-case! 'wk_snode_ri '[G :- (List Sk), x :- Exp, c1 :- Exp, c2 :- Exp,
                          ih_hx :- (%WK G x Sk.lbl), ih_h1 :- (%WK G c1 Sk.syn), ih_h2 :- (%WK G c2 Sk.syn)]
  '(Exp.snode x c1 c2) 'Sk.syn
  '(coe Sk.syn Sk.syn (Code.sn q1 q2 q3)) '[(%H x G Sk.lbl ih_hx) (%H c1 G Sk.syn ih_h1) (%H c2 G Sk.syn ih_h2)])

;; sRecS: Code.rec; the leaf step under one binder (a), the node step under
;; five (a, c₁, c₂, y₁, y₂), at cuts cu+1 and cu+5.
(simple-case! 'wk_recS_ri '[G :- (List Sk), P :- Exp, tl :- Exp, tn :- Exp, c :- Exp,
                         ih_hl :- (%WK (List.cons Sk Sk.lbl G) tl (skel P)),
                         ih_hn :- (%WK (sk2 (skel P) (skel P) (sk2 Sk.syn Sk.syn (List.cons Sk Sk.lbl G))) tn (skel P)),
                         ih_hc :- (%WK G c Sk.syn)]
  '(Exp.recS P tl tn c) '(skel P)
  '(Code.rec$1 (fn [_ :- Code] (Car (skel P))) q1 q2 q3)
  '[(%HB [l :- Nat] tl 1 (List.cons Sk Sk.lbl G) (skel P) (Prod.mk l en) ih_hl)
    (%HB [l :- Nat, a0 :- Code, b0 :- Code, ya :- (Car (skel P)), yb :- (Car (skel P))] tn 5
         (sk2 (skel P) (skel P) (sk2 Sk.syn Sk.syn (List.cons Sk Sk.lbl G))) (skel P)
         (Prod.mk yb (Prod.mk ya (Prod.mk b0 (Prod.mk a0 (Prod.mk l en))))) ih_hn)
    (%H c G Sk.syn ih_hc)])

(simple-case! 'wk_leaf_ri '[G :- (List Sk), x :- Exp, ih_h :- (%WK G x Sk.lbl)]
  '(Exp.leaf x) 'Sk.cert
  '(coe Sk.cert Sk.cert (Code.sl (riLf ri q1))) ;; RI: leaf '[(%H x G Sk.lbl ih_h)])

(simple-case! 'wk_node_ri '[G :- (List Sk), d :- Exp, x :- Exp, r1 :- Exp, r2 :- Exp,
                         ih_hx :- (%WK G x Sk.lbl), ih_h1 :- (%WK G r1 Sk.cert), ih_h2 :- (%WK G r2 Sk.cert)]
  '(Exp.node d x r1 r2) 'Sk.cert
  '(coe Sk.cert Sk.cert (Code.sn q1 q2 q3)) '[(%H x G Sk.lbl ih_hx) (%H r1 G Sk.cert ih_h1) (%H r2 G Sk.cert ih_h2)])

(simple-case! 'wk_itR_ri '[G :- (List Sk), X :- Exp, g :- Exp, h :- Exp, r :- Exp,
                        ih_hg :- (%WK G g (Sk.arr Sk.lbl (skel X))),
                        ih_hh :- (%WK G h (Sk.arr Sk.dia (Sk.arr Sk.lbl (Sk.arr (skel X) (Sk.arr (skel X) (skel X)))))),
                        ih_hr :- (%WK G r Sk.cert)]
  '(Exp.itR X g h r) '(skel X)
  '(Code.rec$1 (fn [_ :- Code] (Car (skel X))) (fn [l :- Nat] (q1 (riIt ri l))) ;; RI: itR on a leaf
     
      (fn [l :- Nat, a0 :- Code, b0 :- Code, ya :- (Car (skel X)), yb :- (Car (skel X))] (q2 Unit.unit l ya yb)) q3)
  '[(%H g G (Sk.arr Sk.lbl (skel X)) ih_hg)
    (%H h G (Sk.arr Sk.dia (Sk.arr Sk.lbl (Sk.arr (skel X) (Sk.arr (skel X) (skel X))))) ih_hh)
    (%H r G Sk.cert ih_hr)])

(simple-case! 'wk_prn_ri '[G :- (List Sk), r :- Exp, ih_h :- (%WK G r Sk.cert)]
  '(Exp.prn r) 'Sk.syn
  '(coe Sk.syn Sk.syn (riPr ri q1)) ;; RI: print '[(%H r G Sk.cert ih_h)])

;; sLam: arrCase at the arrow skeleton reduces to the body under one binder.
(simple-case! 'wk_lam_ri '[G :- (List Sk), r :- U, A :- Exp, t :- Exp, s :- Sk,
                        ih_ht :- (%WK (List.cons Sk (skel A) G) t s)]
  '(Exp.lam r A t) '(Sk.arr (skel A) s)
  'q1 '[(%HB [a0 :- (Car (skel A))] t 1 (List.cons Sk (skel A) G) s (Prod.mk a0 en) ih_ht)])

;; sApp: the clause is Option.rec over skOf of the argument; skOf_lift makes
;; the scrutinees equal, and skOf_typed leaves only none (default on both
;; sides) or the typed skeleton s (the two recursive calls).
(case-thm! 'wk_app_ri '[G :- (List Sk), f :- Exp, u :- Exp, s :- Sk, t :- Sk,
                     ih_hf :- (%WK G f (Sk.arr s t)), ih_hu :- (%WK G u s), hu :- (SkJ Bool.false G u s)]
  '(%WK G (Exp.app f u) t)
  '[(intro cu xs en vx)
    (exact (optrec_congr (Car t) (dflt t)
             (fn [su :- Sk] ((%D (lift 1 cu f) (insS cu xs G) (Sk.arr su t) (insE cu xs G en vx))
                             (%D (lift 1 cu u) (insS cu xs G) su (insE cu xs G en vx))))
             (fn [su :- Sk] ((%D f G (Sk.arr su t) en) (%D u G su en)))
             (skOf (insS cu xs G) (lift 1 cu u)) (skOf G u) s
             (skOf_lift u cu xs G) (skOf_typed Bool.false G u s hu)
             (%CONG (q1 q2) (%H f G (Sk.arr s t) ih_hf) (%H u G s ih_hu))))])

(simple-case! 'wk_pair_ri '[G :- (List Sk), r :- U, A :- Exp, B :- Exp, x :- Exp, y :- Exp,
                         ih_hx :- (%WK G x (skel A)), ih_hy :- (%WK G y (skel B))]
  '(Exp.pair (Exp.tSig r A B) x y) '(Sk.prod (skel A) (skel B))
  '(Prod.mk q1 q2) '[(%H x G (skel A) ih_hx) (%H y G (skel B) ih_hy)])

;; sLetp: as application, over skOf of the pair; at the product skeleton
;; splitProd reduces to the body under two binders (cut cu+2), whose
;; environment holds the pair's components: first the pair's value is
;; rewritten, then the body's induction hypothesis applies.
(case-thm! 'wk_letp_ri '[G :- (List Sk), C :- Exp, p :- Exp, t :- Exp, s1 :- Sk, s2 :- Sk,
                      ih_hp :- (%WK G p (Sk.prod s1 s2)), ih_ht :- (%WK (sk2 s2 s1 G) t (skel C)),
                      hp :- (SkJ Bool.false G p (Sk.prod s1 s2))]
  '(%WK G (Exp.letp C p t) (skel C))
  '[(intro cu xs en vx)
    (exact (optrec_congr (Car (skel C)) (dflt (skel C))
             (fn [sp :- Sk] (splitProd (skel C) sp (%D (lift 1 cu p) (insS cu xs G) sp (insE cu xs G en vx))
                              (fn [a0 :- Sk, b0 :- Sk, va :- (Car a0), vb :- (Car b0)]
                                (%D (lift 1 (+ cu 2) t) (sk2 b0 a0 (insS cu xs G)) (skel C) (Prod.mk vb (Prod.mk va (insE cu xs G en vx)))))))
             (fn [sp :- Sk] (splitProd (skel C) sp (%D p G sp en)
                              (fn [a0 :- Sk, b0 :- Sk, va :- (Car a0), vb :- (Car b0)]
                                (%D t (sk2 b0 a0 G) (skel C) (Prod.mk vb (Prod.mk va en))))))
             (skOf (insS cu xs G) (lift 1 cu p)) (skOf G p) (Sk.prod s1 s2)
             (skOf_lift p cu xs G) (skOf_typed Bool.false G p (Sk.prod s1 s2) hp)
             (Eq.trans
               (%CONG (%D (lift 1 (+ cu 2) t) (insS (+ cu 2) xs (sk2 s2 s1 G)) (skel C)
                          (insE (+ cu 2) xs (sk2 s2 s1 G) (Prod.mk (Prod.snd q1) (Prod.mk (Prod.fst q1) en)) vx))
                      (%H p G (Sk.prod s1 s2) ih_hp))
               (ih_ht (+ cu 2) xs (Prod.mk (Prod.snd (%D p G (Sk.prod s1 s2) en)) (Prod.mk (Prod.fst (%D p G (Sk.prod s1 s2) en)) en)) vx))))])

(simple-case! 'wk_chk_ri '[G :- (List Sk), c :- Exp, d :- Exp, ih_hc :- (%WK G c Sk.syn), ih_hd :- (%WK G d Sk.syn)]
  '(Exp.chk c d) 'Sk.bool
  '(coe Sk.bool Sk.bool (chkf q1 q2)) '[(%H c G Sk.syn ih_hc) (%H d G Sk.syn ih_hd)])

;; sRefl: the base type D is closed (lift_base), so the check against
;; encTy D and the decoded program's run at the lower table pv are the same
;; on both sides; only the certificate r's value is rewritten.
(def ^:private refl-tmpl
  '(Bool.rec$1 (fn [_ :- Bool] (Car (skel D))) (dflt (skel D))
     (Option.rec$1$0 (Prod Nat (Prod Exp Exp)) (fn [_ :- (Option (Prod Nat (Prod Exp Exp)))] (Car (skel D))) (dflt (skel D))
       (fn [tr :- (Prod Nat (Prod Exp Exp))]
         (coe (skel D) (skel D) (pv (Prod.fst tr) (Prod.fst (Prod.snd tr)) (thetaSk (Prod.fst tr)) (skel D) (tokenEnv (Prod.fst tr)))))
       (dec (riPr ri q1)))
     ;; RI: reflect decodes the printed tree, only when it is phantom-free
     (Bool.and (Nat.ble (cnodes q1) cp) (Bool.and (riPf ri q1) (chkf (riPr ri q1) (encTy D))))))

(case-thm! 'wk_refl_ri '[G :- (List Sk), D :- Exp, r :- Exp, e :- Exp, hb :- (= (isBaseTy D) true), ih_hr :- (%WK G r Sk.cert)]
  '(%WK G (Exp.refl D r e) (skel D))
  ['(intro cu xs en vx)
   '(have hD (= (lift 1 cu D) D) (lift_base D hb 1 cu))
   '(change (= (%D (Exp.refl (lift 1 cu D) (lift 1 cu r) (lift 1 cu e)) (insS cu xs G) (skel D) (insE cu xs G en vx))
               (%D (Exp.refl D r e) G (skel D) en)))
   '(rw [hD])
   (list 'exact (list '%CONG refl-tmpl '(%H r G Sk.cert ih_hr)))])

;; sInsp: the branches are under two binders (x ↦ ⟦r⟧, e ↦ ⋆): first the
;; branches' hypotheses at the lifted r's value, then r and c themselves.
(case-thm! 'wk_insp_ri '[G :- (List Sk), X :- Exp, r :- Exp, c :- Exp, t1 :- Exp, t2 :- Exp,
                      ih_hr :- (%WK G r Sk.cert), ih_hc :- (%WK G c Sk.syn),
                      ih_h1 :- (%WK (sk2 Sk.unit Sk.cert G) t1 (skel X)), ih_h2 :- (%WK (sk2 Sk.unit Sk.cert G) t2 (skel X))]
  '(%WK G (Exp.insp X r c t1 t2) (skel X))
  '[(intro cu xs en vx)
    (exact (Eq.trans
      (%CONG (Bool.rec$1 (fn [_ :- Bool] (Car (skel X))) q1 q2
               (chkf (riPr ri (%D (lift 1 cu r) (insS cu xs G) Sk.cert (insE cu xs G en vx))) (%D (lift 1 cu c) (insS cu xs G) Sk.syn (insE cu xs G en vx)))) ;; RI: inspect
        (%HB [] t2 2 (sk2 Sk.unit Sk.cert G) (skel X) (Prod.mk Unit.unit (Prod.mk (%D (lift 1 cu r) (insS cu xs G) Sk.cert (insE cu xs G en vx)) en)) ih_h2)
        (%HB [] t1 2 (sk2 Sk.unit Sk.cert G) (skel X) (Prod.mk Unit.unit (Prod.mk (%D (lift 1 cu r) (insS cu xs G) Sk.cert (insE cu xs G en vx)) en)) ih_h1))
      (%CONG (Bool.rec$1 (fn [_ :- Bool] (Car (skel X)))
               (%D t2 (sk2 Sk.unit Sk.cert G) (skel X) (Prod.mk Unit.unit (Prod.mk q1 en)))
               (%D t1 (sk2 Sk.unit Sk.cert G) (skel X) (Prod.mk Unit.unit (Prod.mk q1 en)))
               (chkf (riPr ri q1) q2)) ;; RI: inspect
        (%H r G Sk.cert ih_hr) (%H c G Sk.syn ih_hc))))])

;; --- the induction ----------------------------------------------------------------

(def ^:private wk-args
  '{sVar [wk_var_ri G i s]
    sIte [wk_ite_ri G b t e s ih_hb ih_ht ih_he]
    sElimB [wk_elimB_ri G P b t e ih_hb ih_ht ih_he]
    sSucc [wk_succ_ri G n ih_h]
    sRecN [wk_recN_ri G P z st n ih_hz ih_hs ih_hn]
    sCaseL [wk_caseL_ri G P x bs ih_hx ih_hb]
    sBcons [wk_bcons_ri G h t s ih_hh ih_ht]
    sSleaf [wk_sleaf_ri G x ih_h]
    sSnode [wk_snode_ri G x c1 c2 ih_hx ih_h1 ih_h2]
    sRecS [wk_recS_ri G P tl tn c ih_hl ih_hn ih_hc]
    sLeaf [wk_leaf_ri G x ih_h]
    sNode [wk_node_ri G d x r1 r2 ih_hx ih_h1 ih_h2]
    sItR [wk_itR_ri G X g h r ih_hg ih_hh ih_hr]
    sPrn [wk_prn_ri G r ih_h]
    sLam [wk_lam_ri G r A t s ih_ht]
    sApp [wk_app_ri G f u s t ih_hf ih_hu hu]
    sPair [wk_pair_ri G r A B x y ih_hx ih_hy]
    sLetp [wk_letp_ri G C p t s1 s2 ih_hp ih_ht hp]
    sChk [wk_chk_ri G c d ih_hc ih_hd]
    sRefl [wk_refl_ri G D r e hb ih_hr]
    sInsp [wk_insp_ri G X r c t1 t2 ih_hr ih_hc ih_h1 ih_h2]})

(defn- wk-case [rule]
  (if-let [[lem & args] (wk-args rule)]
    [(list 'exact (list* lem 'chkf 'dec 'encTy 'ri 'pv 'cp args))]
    '[(intro cu xs en vx) (rfl)]))

;; Item 1 at one level of the table: for every derivation G ⊢ e : s (types
;; included; their denotation is a default), inserting a variable of any
;; skeleton at any position c leaves the denotation unchanged.
(a/prove-theorem 'denAt_weaken_ri
  (lv (into dparams '[w0 :- Bool, G0 :- (List Sk), e0 :- Exp, s0 :- Sk, der :- (SkJ w0 G0 e0 s0)]))
  (lv (WK 'G0 'e0 's0))
  (into ['(induction der)] (mapcat wk-case skj-rules)))

;; den n is denAt at its own lower table: den0 at n = 0, denT k at n = k+1
;; (denT_top).
;; denPrev and den_eq_denAt (den n = denAt (denPrev n) n) come from unfold.clj.
;; Item 1 (weakening), at every budget n.
(thm den_weaken_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                 w0 :- Bool, G0 :- (List Sk), e0 :- Exp, s0 :- Sk, der :- (SkJ w0 G0 e0 s0)]
  (forall [cu Nat] (forall [xs Sk] (forall [en (HEnv G0)] (forall [vx (Car xs)]
    (= (den_ri chkf dec encTy ri n (lift 1 cu e0) (insS cu xs G0) s0 (insE cu xs G0 en vx)) (den_ri chkf dec encTy ri n e0 G0 s0 en))))))
  (intro cu xs en vx)
  (rw [(den_eq_denAt_ri chkf dec encTy ri n (lift 1 cu e0)) (den_eq_denAt_ri chkf dec encTy ri n e0)])
  (exact (denAt_weaken_ri chkf dec encTy ri (denPrev_ri chkf dec encTy ri n) n w0 G0 e0 s0 der cu xs en vx)))

;; ===========================================================================
;; §5  Lemma 3.1 over skeleton typing alone is false (kernel-checked)
;; ===========================================================================

;; t = (λ(y : Π(l:Lbl).Nat). y) x in the context x : Lbl → Nat, and the
;; branch list u = bcons (succ zero) bnil : Lbl → Nat (label 0 ↦ 1).
;; (cex31_t_typed: the standard constant is used)

;; (cex31_u_typed: the standard constant is used)

;; none ≠ some, for skeletons.
;; (none_ne_someS: the standard constant is used)

;; The substitution u/x is skeleton-typed (the only variable of the context
;; is sent to u, typed at its skeleton).
;; (cex31_sigma_typed: the standard constant is used)

;; The two sides at label 0, computed by the kernel (any checker and
;; decoder; budget 0).
(thm cex31_lhs_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt]
  (= (den_ri chkf dec encTy ri 0
          (subst (fn [i :- Nat] (inst1 (Exp.bcons (Exp.succ Exp.zero) Exp.bnil) i))
                 (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tNat) (Exp.var 0)) (Exp.var 0)))
          (List.nil Sk) (Sk.arr Sk.lbl Sk.nat) Unit.unit 0)
     0)
  (rfl))

(thm cex31_rhs_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt]
  (= (den_ri chkf dec encTy ri 0
          (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tNat) (Exp.var 0)) (Exp.var 0))
          (List.cons Sk (Sk.arr Sk.lbl Sk.nat) (List.nil Sk)) (Sk.arr Sk.lbl Sk.nat)
          (envOf_ri chkf dec encTy ri 0 (List.cons Sk (Sk.arr Sk.lbl Sk.nat) (List.nil Sk))
                 (fn [i :- Nat] (inst1 (Exp.bcons (Exp.succ Exp.zero) Exp.bnil) i)) (List.nil Sk) Unit.unit)
          0)
     1)
  (rfl))

;; Lemma 3.1 with only skeleton typing of t and of the substitution fails.
(thm lemma31_skj_counterexample_ri []
  (Not (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code) ri RInt]
        (forall [n Nat] (forall [Gp (List Sk)] (forall [t Exp] (forall [s Sk] (forall [G (List Sk)] (forall [sg (=> Nat Exp)] (forall [eta (HEnv G)]
          (=> (SkJ Bool.false Gp t s)
              (forall [i Nat] (forall [s2 Sk] (=> (= (nthS Gp i) (Option.some Sk s2)) (SkJ Bool.false G (sg i) s2))))
              (= (den_ri chkf dec encTy ri n (subst sg t) G s eta)
                 (den_ri chkf dec encTy ri n t Gp s (envOf_ri chkf dec encTy ri n Gp sg G eta)))))))))))))))
  (intro h)
  (have heq (= (den_ri (fn [a :- Code, b :- Code] Bool.true) (fn [c :- Code] (Option.none (Prod Nat (Prod Exp Exp)))) (fn [e :- Exp] (Code.sl 0)) stdRI 0
                    (subst (fn [i :- Nat] (inst1 (Exp.bcons (Exp.succ Exp.zero) Exp.bnil) i))
                           (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tNat) (Exp.var 0)) (Exp.var 0)))
                    (List.nil Sk) (Sk.arr Sk.lbl Sk.nat) Unit.unit)
               (den_ri (fn [a :- Code, b :- Code] Bool.true) (fn [c :- Code] (Option.none (Prod Nat (Prod Exp Exp)))) (fn [e :- Exp] (Code.sl 0)) stdRI 0
                    (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tNat) (Exp.var 0)) (Exp.var 0))
                    (List.cons Sk (Sk.arr Sk.lbl Sk.nat) (List.nil Sk)) (Sk.arr Sk.lbl Sk.nat)
                    (envOf_ri (fn [a :- Code, b :- Code] Bool.true) (fn [c :- Code] (Option.none (Prod Nat (Prod Exp Exp)))) (fn [e :- Exp] (Code.sl 0)) stdRI 0
                           (List.cons Sk (Sk.arr Sk.lbl Sk.nat) (List.nil Sk))
                           (fn [i :- Nat] (inst1 (Exp.bcons (Exp.succ Exp.zero) Exp.bnil) i)) (List.nil Sk) Unit.unit)))
    (h (fn [a :- Code, b :- Code] Bool.true) (fn [c :- Code] (Option.none (Prod Nat (Prod Exp Exp)))) (fn [e :- Exp] (Code.sl 0)) stdRI 0
       (List.cons Sk (Sk.arr Sk.lbl Sk.nat) (List.nil Sk))
       (Exp.app (Exp.lam U.uw (Exp.tPi U.uw Exp.tLbl Exp.tNat) (Exp.var 0)) (Exp.var 0))
       (Sk.arr Sk.lbl Sk.nat) (List.nil Sk)
       (fn [i :- Nat] (inst1 (Exp.bcons (Exp.succ Exp.zero) Exp.bnil) i)) Unit.unit
       cex31_t_typed cex31_sigma_typed))
  (have h01 (= 0 1)
    (Eq.trans (Eq.symm (cex31_lhs_ri (fn [a :- Code, b :- Code] Bool.true) (fn [c :- Code] (Option.none (Prod Nat (Prod Exp Exp)))) (fn [e :- Exp] (Code.sl 0)) stdRI))
      (Eq.trans (congrArg (fn [fv :- (Car (Sk.arr Sk.lbl Sk.nat))] (fv 0)) heq)
        (cex31_rhs_ri (fn [a :- Code, b :- Code] Bool.true) (fn [c :- Code] (Option.none (Prod Nat (Prod Exp Exp)))) (fn [e :- Exp] (Code.sl 0)) stdRI))))
  (exact (absurd (Eq.symm h01) (Nat.succ_ne_zero 0))))

;; ===========================================================================
;; §6  Skeleton typing is closed under weakening (syntactic, for item 2)
;; ===========================================================================
;; SkJ w G e s → SkJ w (insS c x G) (lift 1 c e) s.  Needed so that the
;; substitution shifted under a binder (up σ: variable 0, then σ lifted) is
;; again skeleton-typed.  One explicit term per rule; the casts along
;; skel (lift F) = skel F (skel_lift) are the only non-structural steps.

;; A cast of the innermost context entry along a skeleton equation.

;; (skj_ctx1: the standard constant is used)

;; (skj_weaken_var: the standard constant is used)

(defn- sw-expand [form]
  (let [ct (fn [k] (if (zero? k) 'cc (list '+ 'cc k)))]
    (walk/postwalk
     (fn [x]
       (cond
         (= x 'GI) '(insS cc xx G)
         (and (seq? x) (= (first x) 'L)) (let [[_ k F] x] (list 'lift 1 (ct k) F))
         (and (seq? x) (= (first x) 'SL)) (let [[_ k F] x] (list 'skel_lift F 1 (ct k)))
         (and (seq? x) (= (first x) 'SLs)) (let [[_ k F] x] (list 'Eq.symm (list 'skel_lift F 1 (ct k))))
         (and (seq? x) (= (first x) 'IH)) (let [[_ ih k] x] (list ih (ct k) 'xx))
         (and (seq? x) (= (first x) 'CS)) (let [[_ ctx t s1 s2 h e] x] (list 'skj_cast 'Bool.false ctx t s1 s2 h e))
         :else x))
     form)))

(defn- HT [q] (list 'Sk.arr 'Sk.dia (list 'Sk.arr 'Sk.lbl (list 'Sk.arr q (list 'Sk.arr q q)))))

(def ^:private sw-cases
  {'wEmpty '(SkJ.wEmpty GI) 'wUnit '(SkJ.wUnit GI) 'wBool '(SkJ.wBool GI) 'wNat '(SkJ.wNat GI)
   'wLbl '(SkJ.wLbl GI) 'wSyn '(SkJ.wSyn GI) 'wDia '(SkJ.wDia GI) 'wR '(SkJ.wR GI)
   'wT '(SkJ.wT GI (L 0 b) (IH ih_hb 0))
   'wPi '(SkJ.wPi GI r (L 0 A) (L 1 B) (IH ih_hA 0)
           (skj_ctx1 Bool.true (skel A) (skel (L 0 A)) GI (L 1 B) Sk.unit (IH ih_hB 1) (SLs 0 A)))
   'wSig '(SkJ.wSig GI r (L 0 A) (L 1 B) (IH ih_hA 0)
            (skj_ctx1 Bool.true (skel A) (skel (L 0 A)) GI (L 1 B) Sk.unit (IH ih_hB 1) (SLs 0 A)))
   'sVar '(skj_weaken_var G i s h cc xx)
   'sStar '(SkJ.sStar GI) 'sTT '(SkJ.sTT GI) 'sFF '(SkJ.sFF GI) 'sZero '(SkJ.sZero GI)
   'sLbl '(SkJ.sLbl GI l) 'sBnil '(SkJ.sBnil GI s)
   'sAbort '(CS GI (Exp.abort (L 0 A) (L 0 t)) (skel (L 0 A)) (skel A)
              (SkJ.sAbort GI (L 0 A) (L 0 t) (IH ih_hA 0) (IH ih_ht 0)) (SL 0 A))
   'sIte '(SkJ.sIte GI (L 0 b) (L 0 t) (L 0 e) s (IH ih_hb 0) (IH ih_ht 0) (IH ih_he 0))
   'sElimB '(CS GI (Exp.elimB (L 1 P) (L 0 b) (L 0 t) (L 0 e)) (skel (L 1 P)) (skel P)
              (SkJ.sElimB GI (L 1 P) (L 0 b) (L 0 t) (L 0 e) (IH ih_hP 1) (IH ih_hb 0)
                (CS GI (L 0 t) (skel P) (skel (L 1 P)) (IH ih_ht 0) (SLs 1 P))
                (CS GI (L 0 e) (skel P) (skel (L 1 P)) (IH ih_he 0) (SLs 1 P)))
              (SL 1 P))
   'sSucc '(SkJ.sSucc GI (L 0 n) (IH ih_h 0))
   'sRecN '(CS GI (Exp.recN (L 1 P) (L 0 z) (L 2 st) (L 0 n)) (skel (L 1 P)) (skel P)
             (SkJ.sRecN GI (L 1 P) (L 0 z) (L 2 st) (L 0 n) (IH ih_hP 1)
               (CS GI (L 0 z) (skel P) (skel (L 1 P)) (IH ih_hz 0) (SLs 1 P))
               (CS (sk2 (skel (L 1 P)) Sk.nat GI) (L 2 st) (skel P) (skel (L 1 P))
                 (skj_cast2 Bool.false (skel P) Sk.nat (skel (L 1 P)) Sk.nat GI (L 2 st) (skel P) (IH ih_hs 2) (SLs 1 P) (Eq.refl$1 Sk.nat))
                 (SLs 1 P))
               (IH ih_hn 0))
             (SL 1 P))
   'sCaseL '(CS GI (Exp.caseL (L 1 P) (L 0 x) (L 0 bs)) (skel (L 1 P)) (skel P)
              (SkJ.sCaseL GI (L 1 P) (L 0 x) (L 0 bs) (IH ih_hP 1) (IH ih_hx 0)
                (CS GI (L 0 bs) (Sk.arr Sk.lbl (skel P)) (Sk.arr Sk.lbl (skel (L 1 P))) (IH ih_hb 0)
                  (congrArg (fn [q :- Sk] (Sk.arr Sk.lbl q)) (SLs 1 P))))
              (SL 1 P))
   'sBcons '(SkJ.sBcons GI (L 0 h) (L 0 t) s (IH ih_hh 0) (IH ih_ht 0))
   'sSleaf '(SkJ.sSleaf GI (L 0 x) (IH ih_h 0))
   'sSnode '(SkJ.sSnode GI (L 0 x) (L 0 c1) (L 0 c2) (IH ih_hx 0) (IH ih_h1 0) (IH ih_h2 0))
   'sRecS '(CS GI (Exp.recS (L 1 P) (L 1 tl) (L 5 tn) (L 0 c)) (skel (L 1 P)) (skel P)
             (SkJ.sRecS GI (L 1 P) (L 1 tl) (L 5 tn) (L 0 c) (IH ih_hP 1)
               (CS (List.cons Sk Sk.lbl GI) (L 1 tl) (skel P) (skel (L 1 P)) (IH ih_hl 1) (SLs 1 P))
               (CS (sk2 (skel (L 1 P)) (skel (L 1 P)) (sk2 Sk.syn Sk.syn (List.cons Sk Sk.lbl GI))) (L 5 tn) (skel P) (skel (L 1 P))
                 (skj_cast2 Bool.false (skel P) (skel P) (skel (L 1 P)) (skel (L 1 P)) (sk2 Sk.syn Sk.syn (List.cons Sk Sk.lbl GI))
                   (L 5 tn) (skel P) (IH ih_hn 5) (SLs 1 P) (SLs 1 P))
                 (SLs 1 P))
               (IH ih_hc 0))
             (SL 1 P))
   'sLeaf '(SkJ.sLeaf GI (L 0 x) (IH ih_h 0))
   'sNode '(SkJ.sNode GI (L 0 d) (L 0 x) (L 0 r1) (L 0 r2) (IH ih_hd 0) (IH ih_hx 0) (IH ih_h1 0) (IH ih_h2 0))
   'sItR (list 'CS 'GI '(Exp.itR (L 0 X) (L 0 g) (L 0 h) (L 0 r)) '(skel (L 0 X)) '(skel X)
               (list 'SkJ.sItR 'GI '(L 0 X) '(L 0 g) '(L 0 h) '(L 0 r) '(IH ih_hX 0)
                     '(CS GI (L 0 g) (Sk.arr Sk.lbl (skel X)) (Sk.arr Sk.lbl (skel (L 0 X))) (IH ih_hg 0)
                        (congrArg (fn [q :- Sk] (Sk.arr Sk.lbl q)) (SLs 0 X)))
                     (list 'CS 'GI '(L 0 h) (HT '(skel X)) (HT '(skel (L 0 X))) '(IH ih_hh 0)
                           (list 'congrArg (list 'fn '[q :- Sk] (HT 'q)) '(SLs 0 X)))
                     '(IH ih_hr 0))
               '(SL 0 X))
   'sPrn '(SkJ.sPrn GI (L 0 r) (IH ih_h 0))
   'sLam '(CS GI (Exp.lam r (L 0 A) (L 1 t)) (Sk.arr (skel (L 0 A)) s) (Sk.arr (skel A) s)
            (SkJ.sLam GI r (L 0 A) (L 1 t) s (IH ih_hA 0)
              (skj_ctx1 Bool.false (skel A) (skel (L 0 A)) GI (L 1 t) s (IH ih_ht 1) (SLs 0 A)))
            (congrArg (fn [q :- Sk] (Sk.arr q s)) (SL 0 A)))
   'sApp '(SkJ.sApp GI (L 0 f) (L 0 u) s t (IH ih_hf 0) (IH ih_hu 0))
   'sPair '(CS GI (Exp.pair (Exp.tSig r (L 0 A) (L 1 B)) (L 0 x) (L 0 y)) (Sk.prod (skel (L 0 A)) (skel (L 1 B))) (Sk.prod (skel A) (skel B))
             (SkJ.sPair GI r (L 0 A) (L 1 B) (L 0 x) (L 0 y) (IH ih_hS 0)
               (CS GI (L 0 x) (skel A) (skel (L 0 A)) (IH ih_hx 0) (SLs 0 A))
               (CS GI (L 0 y) (skel B) (skel (L 1 B)) (IH ih_hy 0) (SLs 1 B)))
             (Eq.trans (congrArg (fn [q :- Sk] (Sk.prod q (skel (L 1 B)))) (SL 0 A))
                       (congrArg (fn [q :- Sk] (Sk.prod (skel A) q)) (SL 1 B))))
   'sLetp '(CS GI (Exp.letp (L 0 C) (L 0 p) (L 2 t)) (skel (L 0 C)) (skel C)
             (SkJ.sLetp GI (L 0 C) (L 0 p) (L 2 t) s1 s2 (IH ih_hC 0) (IH ih_hp 0)
               (CS (sk2 s2 s1 GI) (L 2 t) (skel C) (skel (L 0 C)) (IH ih_ht 2) (SLs 0 C)))
             (SL 0 C))
   'sChk '(SkJ.sChk GI (L 0 c) (L 0 d) (IH ih_hc 0) (IH ih_hd 0))
   'sH1 '(SkJ.sH1 GI (L 0 r) (L 0 s) (L 0 c) (L 0 e1) (L 0 e2) (IH ih_hr 0) (IH ih_hs 0) (IH ih_hc 0) (IH ih_h1 0) (IH ih_h2 0))
   'sRefl '(CS GI (Exp.refl (L 0 D) (L 0 r) (L 0 e)) (skel (L 0 D)) (skel D)
             (SkJ.sRefl GI (L 0 D) (L 0 r) (L 0 e) (IH ih_hD 0) (Eq.trans (congrArg isBaseTy (lift_base D hb 1 cc)) hb)
               (IH ih_hr 0) (IH ih_he 0))
             (SL 0 D))
   'sInsp '(CS GI (Exp.insp (L 0 X) (L 0 r) (L 0 c) (L 2 t1) (L 2 t2)) (skel (L 0 X)) (skel X)
             (SkJ.sInsp GI (L 0 X) (L 0 r) (L 0 c) (L 2 t1) (L 2 t2) (IH ih_hX 0) (IH ih_hr 0) (IH ih_hc 0)
               (CS (sk2 Sk.unit Sk.cert GI) (L 2 t1) (skel X) (skel (L 0 X)) (IH ih_h1 2) (SLs 0 X))
               (CS (sk2 Sk.unit Sk.cert GI) (L 2 t2) (skel X) (skel (L 0 X)) (IH ih_h2 2) (SLs 0 X)))
             (SL 0 X))})

;; Weakening for skeleton typing (the abbreviations: GI the extended context,
;; (L k F) F lifted under k binders, (SL k F) / (SLs k F) skel_lift and its
;; symmetric, (IH ih k) the hypothesis at cut cc+k, (CS …) skj_cast).
;; (skj_weaken: the standard constant is used)

;; ===========================================================================
;; §7  Environments of a substitution
;; ===========================================================================

;; envAt dn Gp σ G η : HEnv Gp — the environment in which Lemma 3.1 reads
;; the source term: variable i has the value dn (σ i) G sᵢ η.  It is envOf
;; (lcert.formal.subst) with the denotation dn as a parameter, so that the
;; lemma can be proved for one level of the table (dn = denAt … pv cp) and
;; transferred to den n (envOf_envAt: envOf n = envAt (den n), by rfl).

;; (envAt: the standard constant is used)

(thm envOf_envAt_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt,
                  n :- Nat, Gp :- (List Sk), sg :- (=> Nat Exp), G :- (List Sk), eta :- (HEnv G)]
  (= (envOf_ri chkf dec encTy ri n Gp sg G eta) (envAt (den_ri chkf dec encTy ri n) Gp sg G eta))
  (rfl))

;; The hypotheses on a substitution σ from source context Gp to target
;; context G (SubOK), in three parts:
;;   SubTy  every variable of Gp is sent to a term simply typed at its
;;          skeleton in G (the paper's hypothesis);
;;   skOf-faithful  skOf G (σ i) = nthS Gp i for every i: σ i is not a
;;          branch list or a term ending in one (§5 shows this cannot be
;;          dropped); past the end of Gp, σ i must also have no skeleton;
;;   skeleton Unit  skel (σ i) = Unit for every i: σ substitutes terms, not
;;          types (as in skel_subst, lcert.formal.skeletons).
;; Every substitution the typing rules perform satisfies all three when the
;; substituted terms are typed and are not branch lists (§9 for inst1).
;; (SubTy: the standard constant is used)

;; (SubOK: the standard constant is used)

;; (subOK_ty: the standard constant is used)
;; (subOK_sko: the standard constant is used)
;; (subOK_skel: the standard constant is used)
;; (subOK_mk: the standard constant is used)

;; (someS_inj: the standard constant is used)

;; (subTy_up: the standard constant is used)

;; (sko_up: the standard constant is used)

;; (subOK_up: the standard constant is used)

;; --- lookup in, and shifting of, the substitution's environment -------------
;; envAt_lookup: the variable clause (lookup, then coe s s = id).
;; envAt_lift / envAt_up: under a binder the substitution is up σ; its
;; environment at the extended context is the extended environment (item 1
;; for the lifted values, coe_self for variable 0).

;; (envAt_lookup: the standard constant is used)

;; (subTy_tail: the standard constant is used)

(thm envAt_lift_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, pv :- DenFn, cp :- Nat,
                 a :- Sk, G :- (List Sk), eta :- (HEnv G), v :- (Car a), Gp :- (List Sk)]
  (forall [sg (=> Nat Exp)]
    (=> (SubTy Gp sg G)
        (= (envAt (denAt_ri chkf dec encTy ri pv cp) Gp (fn [i :- Nat] (lift 1 0 (sg i))) (List.cons Sk a G) (Prod.mk v eta))
           (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G eta))))
  (induction Gp)
  (intro sg h)
  (rfl)
  (intro sg h)
  (have h2 (forall [i Nat] (forall [s Sk] (=> (= (nthS (List.cons Sk head tail) i) (Option.some Sk s)) (SkJ Bool.false G (sg i) s)))) h)
  (have e1 (= (denAt_ri chkf dec encTy ri pv cp (lift 1 0 (sg 0)) (List.cons Sk a G) head (Prod.mk v eta))
              (denAt_ri chkf dec encTy ri pv cp (sg 0) G head eta))
    (denAt_weaken_ri chkf dec encTy ri pv cp Bool.false G (sg 0) head (h2 0 head (nthS.eq_2 head tail)) 0 a eta v))
  (have e2 (= (envAt (denAt_ri chkf dec encTy ri pv cp) tail (fn [i :- Nat] (lift 1 0 (sg (+ i 1)))) (List.cons Sk a G) (Prod.mk v eta))
              (envAt (denAt_ri chkf dec encTy ri pv cp) tail (fn [i :- Nat] (sg (+ i 1))) G eta))
    (ih_tail (fn [i :- Nat] (sg (+ i 1))) (subTy_tail head tail sg G h)))
  (exact (Eq.trans
    (congrArg (fn [q :- (Car head)] (Prod.mk q (envAt (denAt_ri chkf dec encTy ri pv cp) tail (fn [i :- Nat] (lift 1 0 (sg (+ i 1)))) (List.cons Sk a G) (Prod.mk v eta)))) e1)
    (congrArg (fn [q :- (HEnv tail)] (Prod.mk (denAt_ri chkf dec encTy ri pv cp (sg 0) G head eta) q)) e2))))

(thm envAt_up_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, pv :- DenFn, cp :- Nat,
               a :- Sk, Gp :- (List Sk), sg :- (=> Nat Exp), G :- (List Sk), eta :- (HEnv G), v :- (Car a), h :- (SubOK Gp sg G)]
  (= (envAt (denAt_ri chkf dec encTy ri pv cp) (List.cons Sk a Gp) (fn [i :- Nat] (up sg i)) (List.cons Sk a G) (Prod.mk v eta))
     (Prod.mk v (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G eta)))
  (exact (Eq.trans
    (congrArg (fn [q :- (Car a)] (Prod.mk q (envAt (denAt_ri chkf dec encTy ri pv cp) Gp (fn [i :- Nat] (lift 1 0 (sg i))) (List.cons Sk a G) (Prod.mk v eta))))
              (coe_self a v))
    (congrArg (fn [q :- (HEnv Gp)] (Prod.mk v q))
              (envAt_lift_ri chkf dec encTy ri pv cp a G eta v Gp sg (subOK_ty Gp sg G h))))))

;; --- skOf and base types under substitution ---------------------------------
;; skOf_subst: skOf commutes with a substitution that is skOf-faithful
;; (skOf G (σ i) = nthS Gp i) and sends variables to terms (skeleton Unit,
;; so that skel of a substituted type is unchanged: skel_subst).

(defn- skof-subst-case [ctor]
  (cond
    (= ctor 'var) '[(exact (hk i))]
    (= ctor 'ite) '[(exact (ih_t Gp sg G hk hu))]
    (= ctor 'lam)
    '[(exact (Eq.trans (skOf_lam_eq G r (subst sg A) (subst (upn 1 sg) t))
               (Eq.trans (congrArg (fn [q :- Sk] (lamSk q (skOf (List.cons Sk q G) (subst (upn 1 sg) t)))) (skel_subst A sg hu))
                 (Eq.trans (congrArg (fn [o :- (Option Sk)] (lamSk (skel A) o))
                             (ih_t (List.cons Sk (skel A) Gp) (upn 1 sg) (List.cons Sk (skel A) G)
                                   (sko_up (skel A) Gp sg G hk) (upn_unit 1 sg hu)))
                   (Eq.symm (skOf_lam_eq Gp r A t))))))]
    (= ctor 'app)
    '[(exact (Eq.trans (skOf_app_eq G (subst sg f) (subst sg u))
               (Eq.trans (congrArg appSk (ih_f Gp sg G hk hu)) (Eq.symm (skOf_app_eq Gp f u)))))]
    (skel-field ctor)
    (let [[F k] (skel-field ctor)]
      [(list 'exact (list 'congrArg '(fn [q :- Sk] (Option.some Sk q))
                          (if (zero? k)
                            (list 'skel_subst F 'sg 'hu)
                            (list 'skel_subst F (list 'upn k 'sg) (list 'upn_unit k 'sg 'hu)))))])
    :else '[(rfl)]))

;; (skOf_subst: the standard constant is used)

;; (subst_base: the standard constant is used)

;; ===========================================================================
;; §8  Lemma 3.1 (substitution), for substitutions satisfying SubOK
;; ===========================================================================
;; Motive, for a derivation Gp ⊢ t : s:  for every target context G,
;; substitution σ with SubOK Gp σ G, and environment η : HEnv G,
;;   ⟦subst σ t⟧ G s η = ⟦t⟧ Gp s (envAt ⟦·⟧ Gp σ G η).
;; The case terms use the abbreviations of §4 with these holes:
;;   (%H2 f s ih)                  subterm f, same contexts;
;;   (%HB2 [binders] vals f bs s ih)  subterm f under the clause's binders
;;       of skeletons bs (innermost first), holding the values vals: the
;;       hypothesis at upn k σ (SubOK by subOK_up k times), then the
;;       environment rewritten by envAt_up k times (binder-eq);
;;   (%EQB vals f bs s ih)         the same equation without funext.

(def ^:private DD '(denAt_ri chkf dec encTy ri pv cp))
(def ^:private ER '(envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G en))

(defn- SB [Gp t s]
  (list 'forall '[G (List Sk)] (list 'forall '[sg (=> Nat Exp)] (list 'forall '[en (HEnv G)]
    (list '=> (list 'SubOK Gp 'sg 'G)
          (list '= (D (list 'subst 'sg t) 'G s 'en) (D t Gp s (list 'envAt DD Gp 'sg 'G 'en))))))))

(defn- upn-sg [k] (if (zero? k) 'sg (list 'upn k 'sg)))
(defn- cons-all [bs base] (reduce (fn [acc b] (list 'List.cons 'Sk b acc)) base (reverse bs)))
(defn- pair-all [vs base] (reduce (fn [acc v] (list 'Prod.mk v acc)) base (reverse vs)))

(defn- binder-eq
  "Proof of D (subst (upn k sg) f) ctxL s envL_ri = D f ctxR s envR, for binder
  skeletons bs = [b1 … bk] (innermost first) and values vs = [v1 … vk]."
  [vs f bs s ih]
  (let [k (count bs)
        ;; level j (1..k): binders b_{k-j+1} … b_k
        suffix (fn [j] (drop (- k j) bs))
        vsuffix (fn [j] (drop (- k j) vs))
        GpJ (fn [j] (cons-all (suffix j) 'Gp))
        GJ (fn [j] (cons-all (suffix j) 'G))
        ELJ (fn [j] (pair-all (vsuffix j) 'en))
        ERJ (fn [j] (pair-all (vsuffix j) ER))
        S (reduce (fn [acc j] (list 'subOK_up (nth bs (- k j)) (GpJ (dec j)) (upn-sg (dec j)) (GJ (dec j)) acc))
                  'hs (range 1 (inc k)))
        E (reduce (fn [acc j]
                    (let [b (nth bs (- k j)) v (nth vs (- k j))
                          step (list 'envAt_up_ri 'chkf 'dec 'encTy 'ri 'pv 'cp b (GpJ (dec j)) (upn-sg (dec j)) (GJ (dec j)) (ELJ (dec j)) v
                                     (reduce (fn [acc2 jj] (list 'subOK_up (nth bs (- k jj)) (GpJ (dec jj)) (upn-sg (dec jj)) (GJ (dec jj)) acc2))
                                             'hs (range 1 j)))]
                      (if (= j 1)
                        step
                        (list 'Eq.trans step (list 'congrArg (list 'fn ['qe ':- (list 'HEnv (GpJ (dec j)))] (list 'Prod.mk v 'qe)) acc)))))
                  nil (range 1 (inc k)))]
    (list 'Eq.trans (list ih (GJ k) (upn-sg k) (ELJ k) S)
          (list 'congrArg (list 'fn ['qe ':- (list 'HEnv (GpJ k))] (D f (GpJ k) s 'qe)) E))))

(defn- expand2 [form]
  (walk/postwalk
   (fn [x]
     (if (seq? x)
       (case (first x)
         %SB (apply SB (rest x))
         %D (apply D (rest x))
         %H2 (let [[_ f s ih] x]
               [(list 'Car s) (D (list 'subst 'sg f) 'G s 'en) (D f 'Gp s ER) (list ih 'G 'sg 'en 'hs)])
         %EQB (let [[_ vs f bs s ih] x] (binder-eq vs f bs s ih))
         %HB2 (let [[_ binders vs f bs s ih] x
                    k (count bs)
                    vars (take-nth 3 binders)
                    types (take-nth 3 (drop 2 binders))
                    body-l (D (list 'subst (upn-sg k) f) (cons-all bs 'G) s (pair-all vs 'en))
                    body-r (D f (cons-all bs 'Gp) s (pair-all vs ER))
                    eqn (binder-eq vs f bs s ih)
                    pf (reduce (fn [acc [v t]] (list 'funext (list 'fn [v ':- t] acc))) eqn (reverse (map vector vars types)))]
                (if (empty? binders)
                  [(list 'Car s) body-l body-r pf]
                  [(concat ['=>] types [(list 'Car s)]) (list 'fn binders body-l) (list 'fn binders body-r) pf]))
         %CONG (cong (second x) (drop 2 x))
         x)
       x))
   form))

(defn- sb-thm! [nm params prop tactics]
  (a/prove-theorem nm (lv (expand2 (into dparams params))) (lv (expand2 prop)) (lv (expand2 tactics))))
(defn- sb-simple! [nm params concl-e concl-s tmpl holes]
  (sb-thm! nm params (list '%SB 'Gp concl-e concl-s)
           ['(intro G sg en hs) (list 'exact (list* '%CONG tmpl holes))]))

(sb-thm! 'sb_var_ri '[Gp :- (List Sk), i :- Nat, s :- Sk, h :- (= (nthS Gp i) (Option.some Sk s))]
  '(%SB Gp (Exp.var i) s)
  '[(intro G sg en hs)
    (exact (Eq.symm (envAt_lookup (denAt_ri chkf dec encTy ri pv cp) G en Gp sg i s h)))])

(sb-simple! 'sb_ite_ri '[Gp :- (List Sk), b :- Exp, t :- Exp, e :- Exp, s :- Sk,
                      ih_hb :- (%SB Gp b Sk.bool), ih_ht :- (%SB Gp t s), ih_he :- (%SB Gp e s)]
  '(Exp.ite b t e) 's
  '(Bool.rec$1 (fn [_ :- Bool] (Car s)) q1 q2 q3)
  '[(%H2 e s ih_he) (%H2 t s ih_ht) (%H2 b Sk.bool ih_hb)])

(sb-simple! 'sb_lam_ri '[Gp :- (List Sk), r :- U, A :- Exp, t :- Exp, s :- Sk,
                      ih_ht :- (%SB (List.cons Sk (skel A) Gp) t s)]
  '(Exp.lam r A t) '(Sk.arr (skel A) s)
  'q1 '[(%HB2 [a0 :- (Car (skel A))] [a0] t [(skel A)] s ih_ht)])

(sb-simple! 'sb_recN_ri '[Gp :- (List Sk), P :- Exp, z :- Exp, st :- Exp, n :- Exp,
                       ih_hz :- (%SB Gp z (skel P)), ih_hs :- (%SB (sk2 (skel P) Sk.nat Gp) st (skel P)), ih_hn :- (%SB Gp n Sk.nat)]
  '(Exp.recN P z st n) '(skel P)
  '(Nat.rec$1 (fn [_ :- Nat] (Car (skel P))) q1 q2 q3)
  '[(%H2 z (skel P) ih_hz)
    (%HB2 [k :- Nat, acc :- (Car (skel P))] [acc k] st [(skel P) Sk.nat] (skel P) ih_hs)
    (%H2 n Sk.nat ih_hn)])

;; --- the remaining cases -----------------------------------------------------------

(sb-simple! 'sb_elimB_ri '[Gp :- (List Sk), P :- Exp, b :- Exp, t :- Exp, e :- Exp,
                        ih_hb :- (%SB Gp b Sk.bool), ih_ht :- (%SB Gp t (skel P)), ih_he :- (%SB Gp e (skel P))]
  '(Exp.elimB P b t e) '(skel P)
  '(Bool.rec$1 (fn [_ :- Bool] (Car (skel P))) q1 q2 q3)
  '[(%H2 e (skel P) ih_he) (%H2 t (skel P) ih_ht) (%H2 b Sk.bool ih_hb)])
(sb-simple! 'sb_succ_ri '[Gp :- (List Sk), n :- Exp, ih_h :- (%SB Gp n Sk.nat)]
  '(Exp.succ n) 'Sk.nat
  '(coe Sk.nat Sk.nat (Nat.succ q1)) '[(%H2 n Sk.nat ih_h)])
(sb-simple! 'sb_caseL_ri '[Gp :- (List Sk), P :- Exp, x :- Exp, bs :- Exp,
                        ih_hx :- (%SB Gp x Sk.lbl), ih_hb :- (%SB Gp bs (Sk.arr Sk.lbl (skel P)))]
  '(Exp.caseL P x bs) '(skel P)
  '(q1 q2) '[(%H2 bs (Sk.arr Sk.lbl (skel P)) ih_hb) (%H2 x Sk.lbl ih_hx)])
(sb-simple! 'sb_bcons_ri '[Gp :- (List Sk), h :- Exp, t :- Exp, s :- Sk,
                        ih_hh :- (%SB Gp h s), ih_ht :- (%SB Gp t (Sk.arr Sk.lbl s))]
  '(Exp.bcons h t) '(Sk.arr Sk.lbl s)
  '(fn [v :- Nat] (Nat.rec$1 (fn [_ :- Nat] (Car s)) q1 (fn [k :- Nat, w :- (Car s)] (q2 (coe Sk.lbl Sk.lbl k))) (coe Sk.lbl Sk.lbl v)))
  '[(%H2 h s ih_hh) (%H2 t (Sk.arr Sk.lbl s) ih_ht)])
(sb-simple! 'sb_sleaf_ri '[Gp :- (List Sk), x :- Exp, ih_h :- (%SB Gp x Sk.lbl)]
  '(Exp.sleaf x) 'Sk.syn
  '(coe Sk.syn Sk.syn (Code.sl q1)) '[(%H2 x Sk.lbl ih_h)])
(sb-simple! 'sb_snode_ri '[Gp :- (List Sk), x :- Exp, c1 :- Exp, c2 :- Exp,
                        ih_hx :- (%SB Gp x Sk.lbl), ih_h1 :- (%SB Gp c1 Sk.syn), ih_h2 :- (%SB Gp c2 Sk.syn)]
  '(Exp.snode x c1 c2) 'Sk.syn
  '(coe Sk.syn Sk.syn (Code.sn q1 q2 q3)) '[(%H2 x Sk.lbl ih_hx) (%H2 c1 Sk.syn ih_h1) (%H2 c2 Sk.syn ih_h2)])
(sb-simple! 'sb_recS_ri '[Gp :- (List Sk), P :- Exp, tl :- Exp, tn :- Exp, c :- Exp,
                       ih_hl :- (%SB (List.cons Sk Sk.lbl Gp) tl (skel P)),
                       ih_hn :- (%SB (sk2 (skel P) (skel P) (sk2 Sk.syn Sk.syn (List.cons Sk Sk.lbl Gp))) tn (skel P)),
                       ih_hc :- (%SB Gp c Sk.syn)]
  '(Exp.recS P tl tn c) '(skel P)
  '(Code.rec$1 (fn [_ :- Code] (Car (skel P))) q1 q2 q3)
  '[(%HB2 [l :- Nat] [l] tl [Sk.lbl] (skel P) ih_hl)
    (%HB2 [l :- Nat, a0 :- Code, b0 :- Code, ya :- (Car (skel P)), yb :- (Car (skel P))] [yb ya b0 a0 l] tn
          [(skel P) (skel P) Sk.syn Sk.syn Sk.lbl] (skel P) ih_hn)
    (%H2 c Sk.syn ih_hc)])
(sb-simple! 'sb_leaf_ri '[Gp :- (List Sk), x :- Exp, ih_h :- (%SB Gp x Sk.lbl)]
  '(Exp.leaf x) 'Sk.cert
  '(coe Sk.cert Sk.cert (Code.sl (riLf ri q1))) ;; RI: leaf '[(%H2 x Sk.lbl ih_h)])
(sb-simple! 'sb_node_ri '[Gp :- (List Sk), d :- Exp, x :- Exp, r1 :- Exp, r2 :- Exp,
                       ih_hx :- (%SB Gp x Sk.lbl), ih_h1 :- (%SB Gp r1 Sk.cert), ih_h2 :- (%SB Gp r2 Sk.cert)]
  '(Exp.node d x r1 r2) 'Sk.cert
  '(coe Sk.cert Sk.cert (Code.sn q1 q2 q3)) '[(%H2 x Sk.lbl ih_hx) (%H2 r1 Sk.cert ih_h1) (%H2 r2 Sk.cert ih_h2)])
(sb-simple! 'sb_itR_ri '[Gp :- (List Sk), X :- Exp, g :- Exp, h :- Exp, r :- Exp,
                      ih_hg :- (%SB Gp g (Sk.arr Sk.lbl (skel X))),
                      ih_hh :- (%SB Gp h (Sk.arr Sk.dia (Sk.arr Sk.lbl (Sk.arr (skel X) (Sk.arr (skel X) (skel X)))))),
                      ih_hr :- (%SB Gp r Sk.cert)]
  '(Exp.itR X g h r) '(skel X)
  '(Code.rec$1 (fn [_ :- Code] (Car (skel X))) (fn [l :- Nat] (q1 (riIt ri l))) ;; RI: itR on a leaf
     
      (fn [l :- Nat, a0 :- Code, b0 :- Code, ya :- (Car (skel X)), yb :- (Car (skel X))] (q2 Unit.unit l ya yb)) q3)
  '[(%H2 g (Sk.arr Sk.lbl (skel X)) ih_hg)
    (%H2 h (Sk.arr Sk.dia (Sk.arr Sk.lbl (Sk.arr (skel X) (Sk.arr (skel X) (skel X))))) ih_hh)
    (%H2 r Sk.cert ih_hr)])
(sb-simple! 'sb_prn_ri '[Gp :- (List Sk), r :- Exp, ih_h :- (%SB Gp r Sk.cert)]
  '(Exp.prn r) 'Sk.syn
  '(coe Sk.syn Sk.syn (riPr ri q1)) ;; RI: print '[(%H2 r Sk.cert ih_h)])
(sb-simple! 'sb_pair_ri '[Gp :- (List Sk), r :- U, A :- Exp, B :- Exp, x :- Exp, y :- Exp,
                       ih_hx :- (%SB Gp x (skel A)), ih_hy :- (%SB Gp y (skel B))]
  '(Exp.pair (Exp.tSig r A B) x y) '(Sk.prod (skel A) (skel B))
  '(Prod.mk q1 q2) '[(%H2 x (skel A) ih_hx) (%H2 y (skel B) ih_hy)])
(sb-simple! 'sb_chk_ri '[Gp :- (List Sk), c :- Exp, d :- Exp, ih_hc :- (%SB Gp c Sk.syn), ih_hd :- (%SB Gp d Sk.syn)]
  '(Exp.chk c d) 'Sk.bool
  '(coe Sk.bool Sk.bool (chkf q1 q2)) '[(%H2 c Sk.syn ih_hc) (%H2 d Sk.syn ih_hd)])

(sb-thm! 'sb_app_ri '[Gp :- (List Sk), f :- Exp, u :- Exp, s :- Sk, t :- Sk,
                   ih_hf :- (%SB Gp f (Sk.arr s t)), ih_hu :- (%SB Gp u s), hu :- (SkJ Bool.false Gp u s)]
  '(%SB Gp (Exp.app f u) t)
  '[(intro G sg en hs)
    (exact (optrec_congr (Car t) (dflt t)
             (fn [su :- Sk] ((%D (subst sg f) G (Sk.arr su t) en) (%D (subst sg u) G su en)))
             (fn [su :- Sk] ((%D f Gp (Sk.arr su t) (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G en))
                             (%D u Gp su (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G en))))
             (skOf G (subst sg u)) (skOf Gp u) s
             (skOf_subst u Gp sg G (subOK_sko Gp sg G hs) (subOK_skel Gp sg G hs)) (skOf_typed Bool.false Gp u s hu)
             (%CONG (q1 q2) (%H2 f (Sk.arr s t) ih_hf) (%H2 u s ih_hu))))])

(sb-thm! 'sb_letp_ri '[Gp :- (List Sk), C :- Exp, p :- Exp, t :- Exp, s1 :- Sk, s2 :- Sk,
                    ih_hp :- (%SB Gp p (Sk.prod s1 s2)), ih_ht :- (%SB (sk2 s2 s1 Gp) t (skel C)),
                    hp :- (SkJ Bool.false Gp p (Sk.prod s1 s2))]
  '(%SB Gp (Exp.letp C p t) (skel C))
  '[(intro G sg en hs)
    (exact (optrec_congr (Car (skel C)) (dflt (skel C))
             (fn [sp :- Sk] (splitProd (skel C) sp (%D (subst sg p) G sp en)
                              (fn [a0 :- Sk, b0 :- Sk, va :- (Car a0), vb :- (Car b0)]
                                (%D (subst (upn 2 sg) t) (sk2 b0 a0 G) (skel C) (Prod.mk vb (Prod.mk va en))))))
             (fn [sp :- Sk] (splitProd (skel C) sp (%D p Gp sp (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G en))
                              (fn [a0 :- Sk, b0 :- Sk, va :- (Car a0), vb :- (Car b0)]
                                (%D t (sk2 b0 a0 Gp) (skel C) (Prod.mk vb (Prod.mk va (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G en)))))))
             (skOf G (subst sg p)) (skOf Gp p) (Sk.prod s1 s2)
             (skOf_subst p Gp sg G (subOK_sko Gp sg G hs) (subOK_skel Gp sg G hs)) (skOf_typed Bool.false Gp p (Sk.prod s1 s2) hp)
             (Eq.trans
               (%CONG (%D (subst (upn 2 sg) t) (sk2 s2 s1 G) (skel C) (Prod.mk (Prod.snd q1) (Prod.mk (Prod.fst q1) en)))
                      (%H2 p (Sk.prod s1 s2) ih_hp))
               (%EQB [(Prod.snd (%D p Gp (Sk.prod s1 s2) (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G en)))
                      (Prod.fst (%D p Gp (Sk.prod s1 s2) (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G en)))]
                     t [s2 s1] (skel C) ih_ht))))])

(sb-thm! 'sb_refl_ri '[Gp :- (List Sk), D :- Exp, r :- Exp, e :- Exp, hb :- (= (isBaseTy D) true), ih_hr :- (%SB Gp r Sk.cert)]
  '(%SB Gp (Exp.refl D r e) (skel D))
  ['(intro G sg en hs)
   '(have hD (= (subst sg D) D) (subst_base D hb sg))
   '(change (= (%D (Exp.refl (subst sg D) (subst sg r) (subst sg e)) G (skel D) en)
               (%D (Exp.refl D r e) Gp (skel D) (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G en))))
   '(rw [hD])
   (list 'exact (list '%CONG refl-tmpl '(%H2 r Sk.cert ih_hr)))])

(sb-thm! 'sb_insp_ri '[Gp :- (List Sk), X :- Exp, r :- Exp, c :- Exp, t1 :- Exp, t2 :- Exp,
                    ih_hr :- (%SB Gp r Sk.cert), ih_hc :- (%SB Gp c Sk.syn),
                    ih_h1 :- (%SB (sk2 Sk.unit Sk.cert Gp) t1 (skel X)), ih_h2 :- (%SB (sk2 Sk.unit Sk.cert Gp) t2 (skel X))]
  '(%SB Gp (Exp.insp X r c t1 t2) (skel X))
  '[(intro G sg en hs)
    (exact (Eq.trans
      (%CONG (Bool.rec$1 (fn [_ :- Bool] (Car (skel X))) q1 q2
               (chkf (riPr ri (%D (subst sg r) G Sk.cert en)) (%D (subst sg c) G Sk.syn en))) ;; RI: inspect
        (%HB2 [] [Unit.unit (%D (subst sg r) G Sk.cert en)] t2 [Sk.unit Sk.cert] (skel X) ih_h2)
        (%HB2 [] [Unit.unit (%D (subst sg r) G Sk.cert en)] t1 [Sk.unit Sk.cert] (skel X) ih_h1))
      (%CONG (Bool.rec$1 (fn [_ :- Bool] (Car (skel X)))
               (%D t2 (sk2 Sk.unit Sk.cert Gp) (skel X) (Prod.mk Unit.unit (Prod.mk q1 (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G en))))
               (%D t1 (sk2 Sk.unit Sk.cert Gp) (skel X) (Prod.mk Unit.unit (Prod.mk q1 (envAt (denAt_ri chkf dec encTy ri pv cp) Gp sg G en))))
               (chkf (riPr ri q1) q2)) ;; RI: inspect
        (%H2 r Sk.cert ih_hr) (%H2 c Sk.syn ih_hc))))])

;; --- the induction, and Lemma 3.1 at every budget ------------------------------------

(def ^:private sb-args
  '{sVar [sb_var_ri G i s h]
    sIte [sb_ite_ri G b t e s ih_hb ih_ht ih_he]
    sElimB [sb_elimB_ri G P b t e ih_hb ih_ht ih_he]
    sSucc [sb_succ_ri G n ih_h]
    sRecN [sb_recN_ri G P z st n ih_hz ih_hs ih_hn]
    sCaseL [sb_caseL_ri G P x bs ih_hx ih_hb]
    sBcons [sb_bcons_ri G h t s ih_hh ih_ht]
    sSleaf [sb_sleaf_ri G x ih_h]
    sSnode [sb_snode_ri G x c1 c2 ih_hx ih_h1 ih_h2]
    sRecS [sb_recS_ri G P tl tn c ih_hl ih_hn ih_hc]
    sLeaf [sb_leaf_ri G x ih_h]
    sNode [sb_node_ri G d x r1 r2 ih_hx ih_h1 ih_h2]
    sItR [sb_itR_ri G X g h r ih_hg ih_hh ih_hr]
    sPrn [sb_prn_ri G r ih_h]
    sLam [sb_lam_ri G r A t s ih_ht]
    sApp [sb_app_ri G f u s t ih_hf ih_hu hu]
    sPair [sb_pair_ri G r A B x y ih_hx ih_hy]
    sLetp [sb_letp_ri G C p t s1 s2 ih_hp ih_ht hp]
    sChk [sb_chk_ri G c d ih_hc ih_hd]
    sRefl [sb_refl_ri G D r e hb ih_hr]
    sInsp [sb_insp_ri G X r c t1 t2 ih_hr ih_hc ih_h1 ih_h2]})

(defn- sb-case [rule]
  (if-let [[lem & args] (sb-args rule)]
    [(list 'exact (list* lem 'chkf 'dec 'encTy 'ri 'pv 'cp args))]
    '[(intro G2 sg en hs) (rfl)]))

(a/prove-theorem 'denAt_subst_ri
  (lv (into dparams '[w0 :- Bool, G0 :- (List Sk), e0 :- Exp, s0 :- Sk, der :- (SkJ w0 G0 e0 s0)]))
  (lv (SB 'G0 'e0 's0))
  (into ['(induction der)] (mapcat sb-case skj-rules)))

;; den n and denAt at its lower table are the same function of terms.
(thm den_fun_eq_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat]
  (= (den_ri chkf dec encTy ri n) (denAt_ri chkf dec encTy ri (denPrev_ri chkf dec encTy ri n) n))
  (funext t)
  (exact (den_eq_denAt_ri chkf dec encTy ri n t)))

;; Lemma 3.1 (R4-metatheory.md §3.2), at every budget n: for a derivation
;; Gp ⊢ t : s (a type or a term) and a substitution σ with SubOK Gp σ G,
;;   ⟦t[σ]⟧ⁿ_G η = ⟦t⟧ⁿ_Gp (x ↦ ⟦σ x⟧ⁿ_G η)      (envOf, lcert.formal.subst).
;; The skOf-faithfulness part of SubOK is an addition to the paper's
;; hypotheses, necessary by lemma31_skj_counterexample (§5).
(thm lemma31_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
              w0 :- Bool, Gp :- (List Sk), t :- Exp, s :- Sk, der :- (SkJ w0 Gp t s),
              G :- (List Sk), sg :- (=> Nat Exp), en :- (HEnv G), hs :- (SubOK Gp sg G)]
  (= (den_ri chkf dec encTy ri n (subst sg t) G s en) (den_ri chkf dec encTy ri n t Gp s (envOf_ri chkf dec encTy ri n Gp sg G en)))
  (rw [(envOf_envAt_ri chkf dec encTy ri n Gp sg G en)])
  (rw [(den_fun_eq_ri chkf dec encTy ri n)])
  (exact (denAt_subst_ri chkf dec encTy ri (denPrev_ri chkf dec encTy ri n) n w0 Gp t s der G sg en hs)))

;; ===========================================================================
;; §9  Item 3: the substitution clause of Lemma 3.3 for V
;; ===========================================================================
;; For a formation derivation Gp ⊢ A type and SubOK Gp σ G:
;;   Vⁿₖ(A[σ])η = Vⁿₖ(A)(x ↦ ⟦σ x⟧ⁿη)   at the skeleton skel A,
;; by induction on the derivation.  T(b) is Lemma 3.1 (lemma31) for b; Π and
;; Σ are congruences of their clauses (usage 0, 1, ω: U.rec's three minor
;; premises), with the hypothesis for B at up σ and the environment
;; rewritten by envOf_up.  The equation is between propositions (then an
;; Iff, lemma33_subst), so the same congrArg/funext chains apply.
;;
;; The statement is at the skeleton skel A, as V is used in the model
;; (model.clj): under a Π or Σ, V B is then read at skel B with the bound
;; variable at skel A, the context the formation derivation of B has.
;; (tBrs is not a formation rule of SkJ, so it does not arise.)

;; envOf of the shifted substitution at the extended environment (§7's
;; envAt_up, transferred to den n).
(thm envOf_up_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
               a :- Sk, Gp :- (List Sk), sg :- (=> Nat Exp), G :- (List Sk), eta :- (HEnv G), v :- (Car a), h :- (SubOK Gp sg G)]
  (= (envOf_ri chkf dec encTy ri n (List.cons Sk a Gp) (fn [i :- Nat] (up sg i)) (List.cons Sk a G) (Prod.mk v eta))
     (Prod.mk v (envOf_ri chkf dec encTy ri n Gp sg G eta)))
  (rw [(envOf_envAt_ri chkf dec encTy ri n (List.cons Sk a Gp) (fn [i :- Nat] (up sg i)) (List.cons Sk a G) (Prod.mk v eta))
       (envOf_envAt_ri chkf dec encTy ri n Gp sg G eta)])
  (rw [(den_fun_eq_ri chkf dec encTy ri n)])
  (exact (envAt_up_ri chkf dec encTy ri (denPrev_ri chkf dec encTy ri n) n a Gp sg G eta v h)))

;; --- proof-term generation for V ------------------------------------------------
;; VS is the motive; beq / aeq are the hypotheses for B (under the binder,
;; at value a) and for A; vB-l/-r and vA-l/-r the two sides they relate.
(def ^:private vparams '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat])
(defn- Vf [A G en k s v] (list 'V_ri 'chkf 'dec 'encTy 'ri 'n A G en k s v))
(defn- EO [Gp] (list 'envOf_ri 'chkf 'dec 'encTy 'ri 'n Gp 'sg 'G 'en))
;; The motive of item 3, for a formation derivation Gp ⊢ A type.
(defn- VS [Gp A]
  (list 'forall '[G (List Sk)] (list 'forall '[sg (=> Nat Exp)] (list 'forall '[en (HEnv G)] (list 'forall '[k Nat]
    (list 'forall ['v (list 'Car (list 'skel A))]
      (list '=> (list 'SubOK Gp 'sg 'G)
            (list '= (Vf (list 'subst 'sg A) 'G 'en 'k (list 'skel A) 'v) (Vf A Gp (EO Gp) 'k (list 'skel A) 'v)))))))))

;; V of B under the Π/Σ binder, at value a, footprint kk, element vv.
(defn- beq [a kk vv]
  (list 'Eq.trans
        (list 'ih_hB '(List.cons Sk (skel A) G) '(upn 1 sg) (list 'Prod.mk a 'en) kk vv '(subOK_up (skel A) Gp sg G hs))
        (list 'congrArg (list 'fn '[qe :- (HEnv (List.cons Sk (skel A) Gp))] (Vf 'B '(List.cons Sk (skel A) Gp) 'qe kk '(skel B) vv))
              (list 'envOf_up_ri 'chkf 'dec 'encTy 'ri 'n '(skel A) 'Gp 'sg 'G 'en a 'hs))))
(defn- aeq [kk vv] (list 'ih_hA 'G 'sg 'en kk vv 'hs))
(defn- vB-l [a kk vv] (Vf '(subst (upn 1 sg) B) '(List.cons Sk (skel A) G) (list 'Prod.mk a 'en) kk '(skel B) vv))
(defn- vB-r [a kk vv] (Vf 'B '(List.cons Sk (skel A) Gp) (list 'Prod.mk a (EO 'Gp)) kk '(skel B) vv))
(defn- vA-l [kk vv] (Vf '(subst sg A) 'G 'en kk '(skel A) vv))
(defn- vA-r [kk vv] (Vf 'A 'Gp (EO 'Gp) kk '(skel A) vv))

(defn- vs-thm! [nm params prop tactics]
  (a/prove-theorem nm (lv (expand2 (into vparams params))) (lv (expand2 prop)) (lv (expand2 tactics))))

(vs-thm! 'vs_T_ri '[Gp :- (List Sk), b :- Exp, hb :- (SkJ Bool.false Gp b Sk.bool)]
  (VS 'Gp '(Exp.tT b))
  ['(intro G sg en k v hs)
   (list 'exact (list 'congrArg '(fn [q :- Bool] (Eq Bool q Bool.true))
                      '(lemma31_ri chkf dec encTy ri n Bool.false Gp b Sk.bool hb G sg en hs)))])

(vs-thm! 'vs_Pi_ri (vec (concat '[Gp :- (List Sk), r :- U, A :- Exp, B :- Exp]
                             ['ih_hA :- (VS 'Gp 'A) 'ih_hB :- (VS '(List.cons Sk (skel A) Gp) 'B)]))
  (VS 'Gp '(Exp.tPi r A B))
  ['(intro G sg en k f hs)
   (list 'exact
     (cong '(U.rec$1 (fn [_ :- U] Prop) q1 q2 q3 r)
       [;; usage 0: every argument
        ['Prop
         (list 'forall '[a (Car (skel A))] (vB-l 'a 'k '(f a)))
         (list 'forall '[a (Car (skel A))] (vB-r 'a 'k '(f a)))
         (list 'congrArg (list 'fn '[P :- (=> (Car (skel A)) Prop)] '(forall [a (Car (skel A))] (P a)))
               (list 'funext (list 'fn '[a :- (Car (skel A))] (beq 'a 'k '(f a)))))]
        ;; usage 1: footprints j with k + j ≤ n
        ['Prop
         (list 'forall '[j Nat] (list '=> '(Nat.le (+ k j) n) (list 'forall '[a (Car (skel A))] (list '=> (vA-l 'j 'a) (vB-l 'a '(+ k j) '(f a))))))
         (list 'forall '[j Nat] (list '=> '(Nat.le (+ k j) n) (list 'forall '[a (Car (skel A))] (list '=> (vA-r 'j 'a) (vB-r 'a '(+ k j) '(f a))))))
         (cong '(forall [j Nat] (=> (Nat.le (+ k j) n) (forall [a (Car (skel A))] (=> (q1 j a) (q2 j a)))))
               [['(=> Nat (Car (skel A)) Prop)
                 (list 'fn '[j :- Nat, a :- (Car (skel A))] (vA-l 'j 'a))
                 (list 'fn '[j :- Nat, a :- (Car (skel A))] (vA-r 'j 'a))
                 (list 'funext (list 'fn '[j :- Nat] (list 'funext (list 'fn '[a :- (Car (skel A))] (aeq 'j 'a)))))]
                ['(=> Nat (Car (skel A)) Prop)
                 (list 'fn '[j :- Nat, a :- (Car (skel A))] (vB-l 'a '(+ k j) '(f a)))
                 (list 'fn '[j :- Nat, a :- (Car (skel A))] (vB-r 'a '(+ k j) '(f a)))
                 (list 'funext (list 'fn '[j :- Nat] (list 'funext (list 'fn '[a :- (Car (skel A))] (beq 'a '(+ k j) '(f a))))))]])]
        ;; usage ω: arguments in V₀
        ['Prop
         (list 'forall '[a (Car (skel A))] (list '=> (vA-l 0 'a) (vB-l 'a 'k '(f a))))
         (list 'forall '[a (Car (skel A))] (list '=> (vA-r 0 'a) (vB-r 'a 'k '(f a))))
         (cong '(forall [a (Car (skel A))] (=> (q1 a) (q2 a)))
               [['(=> (Car (skel A)) Prop)
                 (list 'fn '[a :- (Car (skel A))] (vA-l 0 'a))
                 (list 'fn '[a :- (Car (skel A))] (vA-r 0 'a))
                 (list 'funext (list 'fn '[a :- (Car (skel A))] (aeq 0 'a)))]
                ['(=> (Car (skel A)) Prop)
                 (list 'fn '[a :- (Car (skel A))] (vB-l 'a 'k '(f a)))
                 (list 'fn '[a :- (Car (skel A))] (vB-r 'a 'k '(f a)))
                 (list 'funext (list 'fn '[a :- (Car (skel A))] (beq 'a 'k '(f a))))]])]]))])

(vs-thm! 'vs_Sig_ri (vec (concat '[Gp :- (List Sk), r :- U, A :- Exp, B :- Exp]
                              ['ih_hA :- (VS 'Gp 'A) 'ih_hB :- (VS '(List.cons Sk (skel A) Gp) 'B)]))
  (VS 'Gp '(Exp.tSig r A B))
  ['(intro G sg en k p hs)
   (list 'exact
     (cong '(U.rec$1 (fn [_ :- U] Prop) q1 q2 q3 r)
       [;; usage 0: the second component
        ['Prop (vB-l '(Prod.fst p) 'k '(Prod.snd p)) (vB-r '(Prod.fst p) 'k '(Prod.snd p)) (beq '(Prod.fst p) 'k '(Prod.snd p))]
        ;; usage 1: a split j + (k − j) of the footprint
        ['Prop
         (list 'Exists (list 'fn '[j :- Nat] (list 'And '(Nat.le j k) (list 'And (vA-l 'j '(Prod.fst p)) (vB-l '(Prod.fst p) '(- k j) '(Prod.snd p))))))
         (list 'Exists (list 'fn '[j :- Nat] (list 'And '(Nat.le j k) (list 'And (vA-r 'j '(Prod.fst p)) (vB-r '(Prod.fst p) '(- k j) '(Prod.snd p))))))
         (list 'congrArg '(fn [P :- (=> Nat Prop)] (Exists P))
               (list 'funext (list 'fn '[j :- Nat]
                 (cong '(And (Nat.le j k) (And q1 q2))
                       [['Prop (vA-l 'j '(Prod.fst p)) (vA-r 'j '(Prod.fst p)) (aeq 'j '(Prod.fst p))]
                        ['Prop (vB-l '(Prod.fst p) '(- k j) '(Prod.snd p)) (vB-r '(Prod.fst p) '(- k j) '(Prod.snd p))
                         (beq '(Prod.fst p) '(- k j) '(Prod.snd p))]]))))]
        ;; usage ω: the first component in V₀
        ['Prop
         (list 'And (vA-l 0 '(Prod.fst p)) (vB-l '(Prod.fst p) 'k '(Prod.snd p)))
         (list 'And (vA-r 0 '(Prod.fst p)) (vB-r '(Prod.fst p) 'k '(Prod.snd p)))
         (cong '(And q1 q2)
               [['Prop (vA-l 0 '(Prod.fst p)) (vA-r 0 '(Prod.fst p)) (aeq 0 '(Prod.fst p))]
                ['Prop (vB-l '(Prod.fst p) 'k '(Prod.snd p)) (vB-r '(Prod.fst p) 'k '(Prod.snd p)) (beq '(Prod.fst p) 'k '(Prod.snd p))]])]]))])

(defn- vs-case [rule]
  (case rule
    (wEmpty wUnit wBool wNat wLbl wSyn wDia wR) '[(intro hw G sg en k v hs) (rfl)]
    wT '[(intro hw) (exact (vs_T_ri chkf dec encTy ri n G b hb))]
    wPi '[(intro hw) (exact (vs_Pi_ri chkf dec encTy ri n G r A B (ih_hA (Eq.refl$1 Bool.true)) (ih_hB (Eq.refl$1 Bool.true))))]
    wSig '[(intro hw) (exact (vs_Sig_ri chkf dec encTy ri n G r A B (ih_hA (Eq.refl$1 Bool.true)) (ih_hB (Eq.refl$1 Bool.true))))]
    '[(intro hw) (cases hw)]))

(a/prove-theorem 'V_subst_gen_ri
  (lv (into vparams '[w0 :- Bool, G0 :- (List Sk), e0 :- Exp, s0 :- Sk, der :- (SkJ w0 G0 e0 s0)]))
  (lv (list '=> '(= w0 Bool.true) (VS 'G0 'e0)))
  (lv (into ['(induction der)] (mapcat vs-case skj-rules))))

;; Item 3 (Lemma 3.3, substitution clause), as an equation of propositions
;; and as an Iff.
(thm V_subst_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
              Gp :- (List Sk), A :- Exp, der :- (SkJ Bool.true Gp A Sk.unit),
              G :- (List Sk), sg :- (=> Nat Exp), en :- (HEnv G), hs :- (SubOK Gp sg G), k :- Nat, v :- (Car (skel A))]
  (= (V_ri chkf dec encTy ri n (subst sg A) G en k (skel A) v)
     (V_ri chkf dec encTy ri n A Gp (envOf_ri chkf dec encTy ri n Gp sg G en) k (skel A) v))
  (exact (V_subst_gen_ri chkf dec encTy ri n Bool.true Gp A Sk.unit der (Eq.refl$1 Bool.true) G sg en k v hs)))

(thm lemma33_subst_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                    Gp :- (List Sk), A :- Exp, der :- (SkJ Bool.true Gp A Sk.unit),
                    G :- (List Sk), sg :- (=> Nat Exp), en :- (HEnv G), hs :- (SubOK Gp sg G), k :- Nat, v :- (Car (skel A))]
  (Iff (V_ri chkf dec encTy ri n (subst sg A) G en k (skel A) v)
       (V_ri chkf dec encTy ri n A Gp (envOf_ri chkf dec encTy ri n Gp sg G en) k (skel A) v))
  (exact (Iff.of_eq (V_subst_ri chkf dec encTy ri n Gp A der G sg en hs k v))))

;; ===========================================================================
;; §10  Item 4: corollaries for subst1 and substL, at their natural environments
;; ===========================================================================
;; The substitutions of the typing rules (App, ElimB, RecN, CaseL, RecS: B[u/x]
;; by subst1; Let and the ι-steps of recN / recSyn by substL) are built from
;; consSub u σ (variable 0 ↦ u, i+1 ↦ σ i) and the identity:
;;   subst1 u  = subst (consSub u var)            (subst1_consSub)
;;   substL us = subst (instLS us)                (substL_instLS; instLS is
;;               instL by structural recursion, so it reduces on cons)
;; SubOK is closed under consSub (subOK_cons) and holds for the identity
;; (subOK_id), and the environments compute: envOf of consSub is (⟦u⟧, …)
;; by definition, and envOf of the identity is η (envOf_id).  The
;; hypotheses on each substituted term u : s are its typing and
;; skOf G u = some s (u is not a branch list; §5).
;;
;; For lists: appS ss G is ss ++ G (by List.rec, so definitional on cons),
;; TyL G us ss says the terms us are typed at the skeletons ss (equal
;; lengths), and envL … en ss us is the environment (⟦u₀⟧, (⟦u₁⟧, …, η)).

;; consSub u σ: variable 0 ↦ u, variable i+1 ↦ σ i.
;; (consSub: the standard constant is used)

;; (subOK_id: the standard constant is used)

;; (subOK_cons: the standard constant is used)

(thm envAt_var_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, pv :- DenFn, cp :- Nat,
                G :- (List Sk)]
  (forall [en (HEnv G)] (= (envAt (denAt_ri chkf dec encTy ri pv cp) G (fn [i :- Nat] (Exp.var i)) G en) en))
  (induction G)
  (intro en)
  (cases en)
  (rfl)
  (intro en)
  (cases en)
  (exact (Eq.trans
    (congrArg (fn [q :- (Car head)] (Prod.mk q (envAt (denAt_ri chkf dec encTy ri pv cp) tail (fn [i :- Nat] (lift 1 0 (Exp.var i))) (List.cons Sk head tail) (Prod.mk fst snd))))
              (coe_self head fst))
    (congrArg (fn [q :- (HEnv tail)] (Prod.mk fst q))
      (Eq.trans (envAt_lift_ri chkf dec encTy ri pv cp head tail snd fst tail (fn [i :- Nat] (Exp.var i))
                  (subOK_ty tail (fn [i :- Nat] (Exp.var i)) tail (subOK_id tail)))
                (ih_tail snd))))))

(thm envOf_id_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
               G :- (List Sk), en :- (HEnv G)]
  (= (envOf_ri chkf dec encTy ri n G (fn [i :- Nat] (Exp.var i)) G en) en)
  (rw [(envOf_envAt_ri chkf dec encTy ri n G (fn [i :- Nat] (Exp.var i)) G en)])
  (rw [(den_fun_eq_ri chkf dec encTy ri n)])
  (exact (envAt_var_ri chkf dec encTy ri (denPrev_ri chkf dec encTy ri n) n G en)))

;; (inst1_consSub: the standard constant is used)

;; (subst1_consSub: the standard constant is used)

;; β / B[u/x]: the natural environment of subst1 u is (⟦u⟧, η).
(thm den_subst1_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                 w0 :- Bool, G :- (List Sk), s :- Sk, t :- Exp, s2 :- Sk, der :- (SkJ w0 (List.cons Sk s G) t s2),
                 u :- Exp, hu :- (SkJ Bool.false G u s), hk :- (= (skOf G u) (Option.some Sk s)), en :- (HEnv G)]
  (= (den_ri chkf dec encTy ri n (subst1 u t) G s2 en)
     (den_ri chkf dec encTy ri n t (List.cons Sk s G) s2 (Prod.mk (den_ri chkf dec encTy ri n u G s en) en)))
  (rw [(subst1_consSub u t)])
  (exact (Eq.trans
    (lemma31_ri chkf dec encTy ri n w0 (List.cons Sk s G) t s2 der G (consSub u (fn [j :- Nat] (Exp.var j))) en
             (subOK_cons u s G (fn [j :- Nat] (Exp.var j)) G hu hk (subOK_id G)))
    (congrArg (fn [q :- (HEnv G)] (den_ri chkf dec encTy ri n t (List.cons Sk s G) s2 (Prod.mk (den_ri chkf dec encTy ri n u G s en) q)))
              (envOf_id_ri chkf dec encTy ri n G en)))))

(thm V_subst1_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
               G :- (List Sk), s :- Sk, A :- Exp, der :- (SkJ Bool.true (List.cons Sk s G) A Sk.unit),
               u :- Exp, hu :- (SkJ Bool.false G u s), hk :- (= (skOf G u) (Option.some Sk s)), en :- (HEnv G),
               k :- Nat, v :- (Car (skel A))]
  (Iff (V_ri chkf dec encTy ri n (subst1 u A) G en k (skel A) v)
       (V_ri chkf dec encTy ri n A (List.cons Sk s G) (Prod.mk (den_ri chkf dec encTy ri n u G s en) en) k (skel A) v))
  (rw [(subst1_consSub u A)])
  (exact (Iff.of_eq (Eq.trans
    (V_subst_ri chkf dec encTy ri n (List.cons Sk s G) A der G (consSub u (fn [j :- Nat] (Exp.var j))) en
             (subOK_cons u s G (fn [j :- Nat] (Exp.var j)) G hu hk (subOK_id G)) k v)
    (congrArg (fn [q :- (HEnv G)] (V_ri chkf dec encTy ri n A (List.cons Sk s G) (Prod.mk (den_ri chkf dec encTy ri n u G s en) q) k (skel A) v))
              (envOf_id_ri chkf dec encTy ri n G en))))))

;; (instLS: the standard constant is used)

;; (instL_instLS: the standard constant is used)

;; (substL_instLS: the standard constant is used)

;; ss ++ G, by List.rec (definitional on cons).
;; (appS: the standard constant is used)

;; TyL G us ss: the list us of terms is typed at the skeletons ss in G, each
;; skOf-faithful; the lists have equal length.
;; (TyL: the standard constant is used)

;; (headE: the standard constant is used)
;; (tailE: the standard constant is used)

;; The natural environment of substL us: the values ⟦u⟧ in front of η.
(kdef envL_ri
  (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code) ri RInt]
    (forall [n Nat] (forall [G (List Sk)] (=> (HEnv G) (forall [ss (List Sk)] (=> (List Exp) (HEnv (appS ss G))))))))))
  (fn [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt,
       n :- Nat, G :- (List Sk), en :- (HEnv G), ss :- (List Sk)]
    (List.rec$1$0 Sk (fn [ss2 :- (List Sk)] (=> (List Exp) (HEnv (appS ss2 G))))
      (fn [us :- (List Exp)] en)
      (fn [s :- Sk, rest :- (List Sk), ih :- (=> (List Exp) (HEnv (appS rest G)))]
        (fn [us :- (List Exp)] (Prod.mk (den_ri chkf dec encTy ri n (headE us) G s en) (ih (tailE us)))))
      ss)))

;; (subOK_list_cons: the standard constant is used)

;; (subOK_list: the standard constant is used)

(thm envOf_list_cons_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                      G :- (List Sk), en :- (HEnv G), u :- Exp, rest :- (List Exp), s :- Sk, ss2 :- (List Sk),
                      ih :- (forall [ss (List Sk)] (=> (TyL G rest ss)
                              (= (envOf_ri chkf dec encTy ri n (appS ss G) (instLS rest) G en) (envL_ri chkf dec encTy ri n G en ss rest)))),
                      h :- (TyL G (List.cons Exp u rest) (List.cons Sk s ss2))]
  (= (envOf_ri chkf dec encTy ri n (appS (List.cons Sk s ss2) G) (instLS (List.cons Exp u rest)) G en)
     (envL_ri chkf dec encTy ri n G en (List.cons Sk s ss2) (List.cons Exp u rest)))
  (have h2 (And (SkJ Bool.false G u s) (And (Eq (Option Sk) (skOf G u) (Option.some Sk s)) (TyL G rest ss2))) h)
  (exact (congrArg (fn [q :- (HEnv (appS ss2 G))] (Prod.mk (den_ri chkf dec encTy ri n u G s en) q))
                   (ih ss2 (And.right (And.right h2))))))

(thm envOf_list_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                 G :- (List Sk), en :- (HEnv G), us :- (List Exp)]
  (forall [ss (List Sk)] (=> (TyL G us ss)
    (= (envOf_ri chkf dec encTy ri n (appS ss G) (instLS us) G en) (envL_ri chkf dec encTy ri n G en ss us))))
  (induction us)
  (intro ss h)
  (have h2 (= ss (List.nil Sk)) h)
  (subst h2)
  (exact (envOf_id_ri chkf dec encTy ri n G en))
  (intro ss)
  (exact (List.rec$0$0 Sk
    (fn [ss3 :- (List Sk)] (=> (TyL G (List.cons Exp head tail) ss3)
      (Eq (HEnv (appS ss3 G)) (envOf_ri chkf dec encTy ri n (appS ss3 G) (instLS (List.cons Exp head tail)) G en)
                              (envL_ri chkf dec encTy ri n G en ss3 (List.cons Exp head tail)))))
    (fn [h :- (TyL G (List.cons Exp head tail) (List.nil Sk))]
      (False.rec$0 (fn [_ :- False] (Eq (HEnv (appS (List.nil Sk) G)) (envOf_ri chkf dec encTy ri n (appS (List.nil Sk) G) (instLS (List.cons Exp head tail)) G en)
                                        (envL_ri chkf dec encTy ri n G en (List.nil Sk) (List.cons Exp head tail)))) h))
    (fn [s :- Sk, ss2 :- (List Sk),
         _ :- (=> (TyL G (List.cons Exp head tail) ss2)
                  (Eq (HEnv (appS ss2 G)) (envOf_ri chkf dec encTy ri n (appS ss2 G) (instLS (List.cons Exp head tail)) G en)
                                          (envL_ri chkf dec encTy ri n G en ss2 (List.cons Exp head tail)))),
         h :- (TyL G (List.cons Exp head tail) (List.cons Sk s ss2))]
      (envOf_list_cons_ri chkf dec encTy ri n G en head tail s ss2 ih_tail h))
    ss)))

;; β for let and the ι-steps of recN / recSyn: the natural environment of
;; substL us is the values of us in front of η (envL).
(thm den_substL_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                 G :- (List Sk), us :- (List Exp), ss :- (List Sk), hty :- (TyL G us ss),
                 w0 :- Bool, t :- Exp, s2 :- Sk, der :- (SkJ w0 (appS ss G) t s2), en :- (HEnv G)]
  (= (den_ri chkf dec encTy ri n (substL us t) G s2 en)
     (den_ri chkf dec encTy ri n t (appS ss G) s2 (envL_ri chkf dec encTy ri n G en ss us)))
  (rw [(substL_instLS us t)])
  (exact (Eq.trans
    (lemma31_ri chkf dec encTy ri n w0 (appS ss G) t s2 der G (instLS us) en (subOK_list G us ss hty))
    (congrArg (fn [q :- (HEnv (appS ss G))] (den_ri chkf dec encTy ri n t (appS ss G) s2 q))
              (envOf_list_ri chkf dec encTy ri n G en us ss hty)))))

(thm V_substL_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
               G :- (List Sk), us :- (List Exp), ss :- (List Sk), hty :- (TyL G us ss),
               A :- Exp, der :- (SkJ Bool.true (appS ss G) A Sk.unit), en :- (HEnv G), k :- Nat, v :- (Car (skel A))]
  (Iff (V_ri chkf dec encTy ri n (substL us A) G en k (skel A) v)
       (V_ri chkf dec encTy ri n A (appS ss G) (envL_ri chkf dec encTy ri n G en ss us) k (skel A) v))
  (rw [(substL_instLS us A)])
  (exact (Iff.of_eq (Eq.trans
    (V_subst_ri chkf dec encTy ri n (appS ss G) A der G (instLS us) en (subOK_list G us ss hty) k v)
    (congrArg (fn [q :- (HEnv (appS ss G))] (V_ri chkf dec encTy ri n A (appS ss G) q k (skel A) v))
              (envOf_list_ri chkf dec encTy ri n G en us ss hty))))))

;; The instance of the let rule (β for let: t[a/x, b/y], substL [b, a]):
;; t is read in the context y : s2, x : s1 at the environment (⟦b⟧, ⟦a⟧, η).
(thm den_substL2_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat,
                  G :- (List Sk), a0 :- Exp, s1 :- Sk, b0 :- Exp, s2 :- Sk,
                  ha :- (SkJ Bool.false G a0 s1), hka :- (= (skOf G a0) (Option.some Sk s1)),
                  hb :- (SkJ Bool.false G b0 s2), hkb :- (= (skOf G b0) (Option.some Sk s2)),
                  w0 :- Bool, t :- Exp, s3 :- Sk, der :- (SkJ w0 (sk2 s2 s1 G) t s3), en :- (HEnv G)]
  (= (den_ri chkf dec encTy ri n (substL (List.cons Exp b0 (List.cons Exp a0 (List.nil Exp))) t) G s3 en)
     (den_ri chkf dec encTy ri n t (sk2 s2 s1 G) s3
          (Prod.mk (den_ri chkf dec encTy ri n b0 G s2 en) (Prod.mk (den_ri chkf dec encTy ri n a0 G s1 en) en))))
  (exact (den_substL_ri chkf dec encTy ri n G (List.cons Exp b0 (List.cons Exp a0 (List.nil Exp))) (List.cons Sk s2 (List.cons Sk s1 (List.nil Sk)))
           (And.intro hb (And.intro hkb (And.intro ha (And.intro hka (Eq.refl$1 (List.nil Sk))))))
           w0 t s3 der en)))

