(ns lcert.formal.ri-unfold
  "Generic copy of lcert.formal.unfold over an R-interpretation ri : RInt (rint.clj;
  Theorem 4.6 design note §3), generated by formal/tools/gen_ri.py: the
  constants that depend on the model carry the suffix _ri and take ri after
  encTy.  Hand edits at the R-specific steps are marked `;; RI:`.  The
  standard namespace's documentation follows, with the same renaming.

  F3i — one-step unfolding of the denotation, for every constructor.

  ⟦t⟧ⁿ is `den_ri n t = denT_ri n n t`, a row of the table of levels (den_ri.clj).  For
  a symbolic n that table does not compute: `denT_ri n n` is stuck on Nat.rec at
  n.  Every case of the fundamental lemma (3.6) needs one step of it, e.g.
  ⟦succ m⟧ⁿ = succ ⟦m⟧ⁿ.  So:

  - denPrev_ri n: the level that decoded programs run through at cap n
    (den0 at n = 0, denT_ri k at n = k + 1);
  - den_eq_denAt: den_ri n t = denAt_ri (denPrev_ri n) n t, for every n (by cases on
    n: definitional at 0, denT_top_ri at k + 1);
  - den_<ctor>_eq, one per constructor of Exp (and den_<ctor>_at, the same
    applied to G s η, for rewriting inside goals):
      den_ri n (c x…) = den_c … (denPrev_ri n) n x… (den_ri n e…)
    with den_ri n applied to each Exp field e.  The right side is the clause of
    den_gen.clj, so each case lemma sees exactly the paper's equation.

  The per-constructor statements are generated from syntactic.clj's field
  table; each is proved by rewriting every den_ri with den_eq_denAt_ri, after which
  the two sides agree definitionally (denAt_ri is Exp.rec over the clauses)."
  (:require [lcert.formal.rint] [lcert.formal.ri-den]
            [ansatz.core :as a]
            [lcert.formal.base :refer [thm kdef lv]]
            [lcert.formal.usage :refer :all]
            [lcert.formal.syntax :refer :all]
            [lcert.formal.skel :refer :all]
            [lcert.formal.conv :refer :all]
            [lcert.formal.carrier :refer :all]
            [lcert.formal.den :refer :all]
            [lcert.formal.syntactic]))

(kdef denPrev_ri
  (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code) ri RInt]
    (=> Nat DenFn))))
  (fn [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, n :- Nat]
    (Nat.rec$1 (fn [_ :- Nat] DenFn) den0 (fn [k :- Nat, _ :- DenFn] (denT_ri chkf dec encTy ri k)) n)))

(thm den_eq_denAt_ri [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt,
                   n :- Nat, t :- Exp]
  (= (den_ri chkf dec encTy ri n t) (denAt_ri chkf dec encTy ri (denPrev_ri chkf dec encTy ri n) n t))
  (cases n) (rfl) (exact (denT_top_ri chkf dec encTy ri n t)))

;; Constructor fields [name type binder-depth], as in syntactic.clj.
(def ^:private exp-fields @#'lcert.formal.syntactic/exp-fields)

(def ^:private params
  '[chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), ri :- RInt, cap :- Nat])

(defn- unfold-eq!
  "State and prove den_<ctor>_eq.  The cap is named `cap`: succ and recN
  have a field named n."
  [ctor fields]
  (let [nm (symbol (str "den_" ctor "_eq_ri"))
        fs (map first fields)
        term (if (seq fs) (apply list (symbol (str "Exp." ctor)) fs) (symbol (str "Exp." ctor)))
        exps (for [[f ty] fields :when (= ty 'Exp)] f)
        rhs (concat (list (symbol (str "den_" ctor "_ri")) 'chkf 'dec 'encTy 'ri '(denPrev_ri chkf dec encTy ri cap) 'cap)
                    fs
                    (for [e exps] (list 'den_ri 'chkf 'dec 'encTy 'ri 'cap e)))
        rewrites (vec (cons (list 'den_eq_denAt_ri 'chkf 'dec 'encTy 'ri 'cap term)
                            (for [e exps] (list 'den_eq_denAt_ri 'chkf 'dec 'encTy 'ri 'cap e))))]
    (a/prove-theorem nm
      (lv (into params (mapcat (fn [[f ty]] [f :- ty]) fields)))
      (lv (list '= (list 'den_ri 'chkf 'dec 'encTy 'ri 'cap term) (apply list rhs)))
      (lv [(list 'rw rewrites)]))))

;; The pointwise forms, den_<ctor>_at: the same equation applied to G, s, η.
;; Ansatz's rewrite matches whole applications only, so a goal mentioning
;; den n (c x…) G s η needs this form.  (The skeleton is named sk: h1 has a
;; field named s.)  Proved by congrArg with the function
;; f ↦ f G s η (congrFun's implicit arguments are not inferred here).
(defn- unfold-at!
  "State and prove den_<ctor>_at."
  [ctor fields]
  (let [nm (symbol (str "den_" ctor "_at_ri"))
        fs (map first fields)
        term (if (seq fs) (apply list (symbol (str "Exp." ctor)) fs) (symbol (str "Exp." ctor)))
        exps (for [[f ty] fields :when (= ty 'Exp)] f)
        rhs (concat (list (symbol (str "den_" ctor "_ri")) 'chkf 'dec 'encTy 'ri '(denPrev_ri chkf dec encTy ri cap) 'cap)
                    fs
                    (for [e exps] (list 'den_ri 'chkf 'dec 'encTy 'ri 'cap e))
                    '[G sk en])]
    (a/prove-theorem nm
      (lv (into params (concat (mapcat (fn [[f ty]] [f :- ty]) fields) '[G :- (List Sk), sk :- Sk, en :- (HEnv G)])))
      (lv (list '= (list 'den_ri 'chkf 'dec 'encTy 'ri 'cap term 'G 'sk 'en) (apply list rhs)))
      (lv [(list 'exact (list 'congrArg '(fn [f :- DenBody] (f G sk en))
                              (apply list (symbol (str "den_" ctor "_eq_ri")) 'chkf 'dec 'encTy 'ri 'cap fs)))]))))

(doseq [[ctor fields] exp-fields] (unfold-eq! ctor fields) (unfold-at! ctor fields))
