import ALSJAS.Checker

/-!
# Explicit reflective proof programs

This module constructs the complete term tree behind the matched negative
control. Nothing here is a magic `boom` axiom. The contradiction is assembled
from the selected Goedel-Jeroslow fixed point, closed quotation, boxed
composition, positive introspection, the exact `self0`, and `copy-box`.

Every quotation embeds a complete certificate generated by `Checker`; the
end-to-end test reparses and checks the resulting nested tree.
-/

namespace ALSJAS.Reflection.Programs

open ALSJAS

/-- Native Level-0 consistency type for a particular exact system reference. -/
def self0Type (system : SystemRef) : Ty :=
  .lolli (.box system .zero) .zero

private def negGodel (system : SystemRef) : Ty :=
  .lolli (.godel system) .zero

private def boxedNegGodel (system : SystemRef) : Ty :=
  .box system (negGodel system)

private def foldType (system : SystemRef) : Ty :=
  .lolli (boxedNegGodel system) (.godel system)

/-- The selected fixed-point fold direction as a closed affine function. -/
private def foldFunction (system : SystemRef) : Term :=
  .lam (boxedNegGodel system) (.godelFold system (.var 0))

private def foldCertificate (system : System.Sealed) : SExpr :=
  Checker.certificateSExpr system (foldType system.reference)
    (foldFunction system.reference)

/-- Type of the central Jeroslow step `G -> box 0`. -/
def gToBoxZeroType (system : SystemRef) : Ty :=
  .lolli (.godel system) (.box system .zero)

/-- From `g : G`, unfold to `q : box (G -> 0)`. `copy-box` supplies two
linearly usable copies. One is introspected and composed with the quoted fold
map to obtain `box G`; the other refutes that boxed `G`, producing `box 0`. -/
def gToBoxZero (system : System.Sealed) : Term :=
  let reference := system.reference
  let negatedGodel := negGodel reference
  let unfolded := Term.godelUnfold reference (.var 0)
  let duplicated := Term.app (.copyBox reference negatedGodel) unfolded
  let quotedFold := Term.quote reference (foldType reference)
    (foldCertificate system)
  let boxedGodel := Term.boxComp quotedFold (.boxIntrosp (.var 1))
  let boxedZero := Term.boxComp (.var 0) boxedGodel
  .lam (.godel reference) (.letTensor duplicated boxedZero)

/-- Complete native certificate for `gToBoxZero`. -/
def gToBoxZeroCertificate (system : System.Sealed) : SExpr :=
  Checker.certificateSExpr system (gToBoxZeroType system.reference)
    (gToBoxZero system)

private def composeType (domain middle codomain : Ty) : Ty :=
  .lolli (.lolli middle codomain)
    (.lolli (.lolli domain middle) (.lolli domain codomain))

/-- Closed affine composition uses each function and argument exactly once. -/
private def compose (domain middle codomain : Ty) : Term :=
  .lam (.lolli middle codomain)
    (.lam (.lolli domain middle)
      (.lam domain (.app (.var 2) (.app (.var 1) (.var 0)))))

private def composeCertificate (system : System.Sealed)
    (domain middle codomain : Ty) : SExpr :=
  Checker.certificateSExpr system (composeType domain middle codomain)
    (compose domain middle codomain)

/-- Formalized G2 type: `box (box 0 -> 0) -> box 0`. -/
def formalizedG2Type (system : SystemRef) : Ty :=
  .lolli (.box system (self0Type system)) (.box system .zero)

/-- Full formalized-G2 proof program. A boxed `self0` is composed, under box,
with the quoted `G -> box 0` map to obtain `box (G -> 0)`. Folding yields `G`,
which the same explicit map sends to `box 0`. -/
def formalizedG2 (system : System.Sealed) : Term :=
  let reference := system.reference
  let godelType := Ty.godel reference
  let boxedZero := Ty.box reference .zero
  let consistencyType := self0Type reference
  let compositionType := composeType godelType boxedZero .zero
  let quotedComposition := Term.quote reference compositionType
    (composeCertificate system godelType boxedZero .zero)
  let quotedGToZero := Term.quote reference (gToBoxZeroType reference)
    (gToBoxZeroCertificate system)
  let boxedAfterSelf0 := Term.boxComp quotedComposition (.var 0)
  let boxedNegatedGodel := Term.boxComp boxedAfterSelf0 quotedGToZero
  let godelProof := Term.godelFold reference boxedNegatedGodel
  .lam (.box reference consistencyType)
    (.app (gToBoxZero system) godelProof)

/-- Complete native certificate for formalized G2. -/
def formalizedG2Certificate (system : System.Sealed) : SExpr :=
  Checker.certificateSExpr system (formalizedG2Type system.reference)
    (formalizedG2 system)

private def self0Certificate (system : System.Sealed) : SExpr :=
  Checker.certificateSExpr system (self0Type system.reference) system.self0

/-- Explicit contradiction for the matched copy system. Necessitate the exact
`self0`, feed it to formalized G2 to obtain `box 0`, then consume that box with
the same exact `self0`. -/
def boom (system : System.Sealed) : Term :=
  let reference := system.reference
  let quotedSelf0 := Term.quote reference (self0Type reference)
    (self0Certificate system)
  .app system.self0 (.app (formalizedG2 system) quotedSelf0)

/-- Complete native contradiction certificate. It is accepted only when the
system's structural profile includes `copy-box`. -/
def boomCertificate (system : System.Sealed) : SExpr :=
  Checker.certificateSExpr system .zero (boom system)

/-- Syntactic audit used by the negative control: it ignores serialized quote
payloads and finds the operational `copyBox` node in the executable term tree. -/
def containsCopyBox : Term → Bool
  | .copyBox _ _ => true
  | .pair left right | .letTensor left right | .app left right |
      .boxComp left right => containsCopyBox left || containsCopyBox right
  | .lam _ body => containsCopyBox body
  | .abort _ contradiction => containsCopyBox contradiction
  | .boxIntrosp proof | .godelFold _ proof | .godelUnfold _ proof =>
      containsCopyBox proof
  | _ => false

end ALSJAS.Reflection.Programs
