"""Generate lcert/formal/sem_gen.clj: the semantic types V of R4-metatheory.md
§3.3, V cap A G η k s v, by recursion on the type A, one definition per
constructor of Exp, assembled by Exp.rec.  The skeleton s is explicit, so that
substitution lemmas need no casts; each clause first checks that s has the
shape the type requires (otherwise False)."""
import re, sys
base = sys.argv[1] if len(sys.argv) > 1 else 'formal/lcert/formal'
syn = open(base + '/syntax.clj').read()
blk = syn[syn.index("(a/inductive Exp []"):syn.index(";; lift k c e")]
blk = re.sub(r";[^\n]*", "", blk)
spec = [(n, re.findall(r"\[(\w+) (\w+)\]", f)) for n, f in re.findall(r"\((\w+)((?: \[\w+ \w+\])*)\)", blk)]
VT = "(forall [G (List Sk)] (=> (HEnv G) Nat (forall [s Sk] (=> (Car s) Prop))))"
PARAMS = [("chkf", "(=> Code Code Bool)"), ("dec", "(=> Code (Option (Prod Nat (Prod Exp Exp))))"),
          ("encTy", "(=> Exp Code)"), ("cap", "Nat")]
def shape(sk_ctor, prop_of_v, arity=0):
    """Sk.rec on s with motive fun s => Car s → Prop: the given constructor gets
    prop_of_v (a fn of v, or of x y v for arr/prod), every other shape False."""
    cases = []
    for c in ["unit","bool","nat","lbl","syn","dia","cert"]:
        cases.append(prop_of_v if c == sk_ctor else "(fn [v :- (Car Sk.%s)] False)" % c)
    for c in ["arr","prod"]:
        if c == sk_ctor:
            cases.append(prop_of_v)
        else:
            cases.append("(fn [x :- Sk, y :- Sk, px :- (=> (Car x) Prop), py :- (=> (Car y) Prop)] (fn [v :- (Car (Sk.%s x y))] False))" % c)
    return "(Sk.rec$1 (fn [t :- Sk] (=> (Car t) Prop)) %s s)" % " ".join(cases)
ANY = "(fn [s :- Sk, v :- (Car s)] True)"
bodies = {
 'tEmpty': "False", 'tUnit': "True", 'tBool': "True", 'tNat': "True", 'tSyn': "True",
 'tLbl': "(%s v)" % shape("lbl", "(fn [v :- Nat] (Nat.lt v 100))"),
 'tDia': "(Nat.le 1 k)",
 'tR': "(%s v)" % shape("cert", "(fn [v :- Code] (Nat.le (cnodes v) k))"),
 'tT': "(Eq Bool (den chkf dec encTy cap b G Sk.bool en) Bool.true)",
 'tPi': "(%s v)" % shape("arr",
    "(fn [x :- Sk, y :- Sk, px :- (=> (Car x) Prop), py :- (=> (Car y) Prop)] (fn [f :- (Car (Sk.arr x y))] "
    "(U.rec$1 (fn [_ :- U] Prop) "
    "(forall [a (Car x)] (i_B (List.cons Sk x G) (Prod.mk a en) k y (f a))) "
    "(forall [j Nat] (=> (Nat.le (+ k j) cap) (forall [a (Car x)] (=> (i_A G en j x a) (i_B (List.cons Sk x G) (Prod.mk a en) (+ k j) y (f a)))))) "
    "(forall [a (Car x)] (=> (i_A G en 0 x a) (i_B (List.cons Sk x G) (Prod.mk a en) k y (f a)))) r)))"),
 'tSig': "(%s v)" % shape("prod",
    "(fn [x :- Sk, y :- Sk, px :- (=> (Car x) Prop), py :- (=> (Car y) Prop)] (fn [p :- (Car (Sk.prod x y))] "
    "(U.rec$1 (fn [_ :- U] Prop) "
    "(i_B (List.cons Sk x G) (Prod.mk (Prod.fst p) en) k y (Prod.snd p)) "
    "(Exists (fn [j :- Nat] (And (Nat.le j k) (And (i_A G en j x (Prod.fst p)) (i_B (List.cons Sk x G) (Prod.mk (Prod.fst p) en) (- k j) y (Prod.snd p)))))) "
    "(And (i_A G en 0 x (Prod.fst p)) (i_B (List.cons Sk x G) (Prod.mk (Prod.fst p) en) k y (Prod.snd p))) r)))"),
 # tBrs P k0: a branch list for labels k0, k0+1, …, read positionally: the
 # label l branch is the list's element l − k0 (bcons h t is h at 0 and t
 # at j + 1 ↦ t's j), in V(P) at label l.
 'tBrs': "(%s v)" % shape("arr",
    "(fn [x :- Sk, y :- Sk, px :- (=> (Car x) Prop), py :- (=> (Car y) Prop)] (fn [f :- (Car (Sk.arr x y))] "
    "(forall [l Nat] (=> (Nat.le k0 l) (Nat.lt l 100) (i_P (List.cons Sk x G) (Prod.mk (coe Sk.lbl x l) en) k y (f (coe Sk.lbl x (- l k0))))))))"),
}
out = [";; GENERATED by formal/tools/gen_sem.py — do not edit by hand.\n"]
names = []
for n, fs in spec:
    fs2 = [(("k0" if (n == 'tBrs' and f == 'k') else f), t) for f, t in fs]
    body = bodies.get(n, "False")
    binders = PARAMS + fs2 + [("i_" + f, VT) for f, t in fs2 if t == "Exp"]
    ty = VT
    for b, t in reversed(binders):
        ty = "(forall [%s %s] %s)" % (b, t, ty)
    lam = "(fn [%s] (fn [G :- (List Sk), en :- (HEnv G), k :- Nat, s :- Sk, v :- (Car s)] %s))" % (
        ", ".join("%s :- %s" % bt for bt in binders), body)
    out.append("(kdef sem_%s\n  %s\n  %s)\n" % (n, ty, lam))
    names.append(n)
minors = " ".join("(sem_%s chkf dec encTy cap)" % n for n in names)
out.append("""(kdef V
  (forall [chkf (=> Code Code Bool)] (forall [dec (=> Code (Option (Prod Nat (Prod Exp Exp))))] (forall [encTy (=> Exp Code)]
    (forall [cap Nat] (=> Exp %s)))))
  (fn [chkf :- (=> Code Code Bool), dec :- (=> Code (Option (Prod Nat (Prod Exp Exp)))), encTy :- (=> Exp Code), cap :- Nat, A :- Exp]
    (Exp.rec$1 (fn [_ :- Exp] %s)
      %s
      A)))
""" % (VT, VT, minors))
open(base + '/sem_gen.clj', 'w').write("\n".join(out))
print(len(names), "clauses")
