"""Generate the generic copy of a namespace of the fundamental-lemma chain:
the model over an R-interpretation ri : RInt (rint.clj; design note
nachlass/docs-theorem46-design.md §3).

    python3 tools/gen_ri.py RENAMES SRC.clj DST.clj

RENAMES is a file of kernel constant names, one per line: the constants of
the chain whose statement or value depends on the model.  The analysis that
produced it walks every constant the warm server recorded for the chain
namespaces and closes {den_<ctor>, denAt, sem_<ctor>, V} under reference.

The transformation, on the source text (comments are left as they are):
- every token naming a constant in RENAMES (also NAME.eq_i and NAME$levels)
  gets the suffix _ri — in code and in strings, since some proofs are built
  from strings;
- every `chkf dec encTy` (quoted or not) gets `ri` after encTy, except as
  CheckSpec's arguments: in the chain these three are passed only to
  model-dependent constants or to the generators that build their
  applications;
- every binder of encTy gains one of ri: `encTy :- (=> Exp Code)` becomes
  `encTy :- (=> Exp Code), ri :- RInt`, and `[encTy (=> Exp Code)]` becomes
  `[encTy (=> Exp Code) ri RInt]`;
- top-level forms declaring a constant NOT in RENAMES, but declared by this
  namespace (DECLARED, the second file argument's companion list), are
  dropped: the generic copy refers to the standard constant;
- the ns form is renamed lcert.formal.X -> lcert.formal.ri-X.
The result is then edited by hand at the R-specific steps (the design
note lists them); the edits are marked `;; RI:` in the generated files."""
import re, sys

# The namespaces of the chain that have a generic copy (the analysis found
# model-dependent constants in each).
CHAIN = set("den sem model unfold mono splitting subst substitution vweaken fundamental "
            "outer recsyn lemma36 conversion convcase".split())

TOK = re.compile(r"[^\s()\[\]{}\"',;@^`~\\]+")


def rename_token(t, R):
    if t in R:
        return t + "_ri"
    m = re.match(r"^([^.$]+)([.$].*)$", t)
    if m and m.group(1) in R:
        return m.group(1) + "_ri" + m.group(2)
    return t


def rename_text(s, R):
    return TOK.sub(lambda m: rename_token(m.group(0), R), s)


def transform(src, R, drop, ns_from, ns_to):
    out = []
    i, n = 0, len(src)
    # pass 1: rename tokens in code and strings, not in comments
    while i < n:
        c = src[i]
        if c == ';':
            j = src.find('\n', i)
            j = n if j < 0 else j
            out.append(src[i:j]); i = j
        elif c == '"':
            j = i + 1
            while j < n and src[j] != '"':
                j += 2 if src[j] == '\\' else 1
            out.append('"' + rename_text(src[i + 1:j], R) + '"'); i = j + 1
        elif c == '\\' and i + 1 < n:
            out.append(src[i:i + 2]); i += 2
        else:
            j = i
            while j < n and src[j] not in ';"\\':
                j += 1
            out.append(rename_text(src[i:j], R)); i = j
    s = ''.join(out)
    # pass 2: ri after every `chkf dec encTy` (quoted or not, in code or in a
    # string): in the chain these three are passed only to model-dependent
    # constants, or to generators building their applications — except
    # CheckSpec, which keeps its three arguments.
    s = re.sub(r"(?<![\w'])(')?chkf(\s+)(')?dec(\s+)(')?encTy(?![\w'])",
               lambda m: "%schkf%s%sdec%s%sencTy %sri" % (
                   m.group(1) or '', m.group(2), m.group(3) or '', m.group(4),
                   m.group(5) or '', m.group(5) or ''), s)
    s = re.sub(r"(CheckSpec\s+'?chkf\s+'?dec\s+'?encTy) '?ri\b", r"\1", s)
    # applications of a renamed constant to holes from its first argument
    # (`(f _ _ _ …)`, the arguments left to unification) need one more hole,
    # for ri
    s = re.sub(r"\(([A-Za-z_0-9]+_ri) _ _ _", r"(\1 _ _ _ _", s)
    # binders
    s = s.replace("encTy :- (=> Exp Code)", "encTy :- (=> Exp Code), ri :- RInt")
    s = s.replace("[encTy (=> Exp Code)]", "[encTy (=> Exp Code) ri RInt]")
    # ns: renamed; requires the R-interpretations and the generic copy of
    # every chain namespace it required (the standard ones stay, for the
    # constants that are not copied)
    s = s.replace("(ns " + ns_from, "(ns " + ns_to, 1)
    s = s.replace('(ns %s\n  "' % ns_to,
                  '(ns %s\n  "Generic copy of %s over an R-interpretation ri : RInt (rint.clj;\n'
                  '  Theorem 4.6 design note §3), generated by formal/tools/gen_ri.py: the\n'
                  '  constants that depend on the model carry the suffix _ri and take ri after\n'
                  '  encTy.  Hand edits at the R-specific steps are marked `;; RI:`.  The\n'
                  '  standard namespace\'s documentation follows, with the same renaming.\n\n  '
                  % (ns_to, ns_from), 1)
    a, b = top_forms(s)[0]
    req = [x for x in re.findall(r"\[lcert\.formal\.([\w-]+)", s[a:b]) if x in CHAIN]
    extra = "[lcert.formal.rint] " + " ".join("[lcert.formal.ri-%s]" % x for x in req)
    k = s.index("(:require", a) + len("(:require")
    s = s[:k] + " " + extra + "\n           " + s[k:]
    # drop top-level forms declaring dropped constants
    if drop:
        s = drop_forms(s, drop)
    return s


DECL = re.compile(r"^\(\s*(?:thm|kdef|a/defn|a/inductive)\s+'?([A-Za-z][A-Za-z0-9_']*)"
                  r"|^\(\s*(?:a/prove-theorem|lcert\.formal\.base/thm|case!)\s+'+([A-Za-z][A-Za-z0-9_']*)"
                  r"|^\(\s*eval\s+\((?:list\*?|concat\s+\(list)\s+'lcert\.formal\.base/thm\s+'([A-Za-z][A-Za-z0-9_']*)"
                  # (eval (concat '(thm NAME …) …)): splitting.clj's case-built proofs
                  r"|^\(\s*eval\s+\(\s*concat\s+'\(thm\s+([A-Za-z][A-Za-z0-9_']*)")


def top_forms(s):
    """Spans (start, end) of the top-level forms of s."""
    spans, depth, i, n, start = [], 0, 0, len(s), None
    while i < n:
        c = s[i]
        if c == ';':
            j = s.find('\n', i); i = n if j < 0 else j; continue
        if c == '"':
            j = i + 1
            while j < n and s[j] != '"':
                j += 2 if s[j] == '\\' else 1
            i = j + 1; continue
        if c == '\\':
            i += 2; continue
        if c in '([{':
            if depth == 0:
                start = i
            depth += 1
        elif c in ')]}':
            depth -= 1
            if depth == 0:
                spans.append((start, i + 1))
        i += 1
    return spans


def drop_forms(s, drop):
    keep, last = [], 0
    for a, b in top_forms(s):
        m = DECL.match(s[a:b])
        name = m and next(g for g in m.groups() if g)
        if name and name in drop:
            keep.append(s[last:a])
            keep.append(";; (%s: the standard constant is used)" % name)
            last = b
    keep.append(s[last:])
    return ''.join(keep)


if __name__ == '__main__':
    renames, declared, src, dst = sys.argv[1:5]
    R = set(l.strip() for l in open(renames) if l.strip())
    D = set(l.strip() for l in open(declared) if l.strip())
    text = open(src).read()
    m = re.search(r"\(ns (lcert\.formal\.[\w-]+)", text)
    ns_from = m.group(1)
    ns_to = "lcert.formal.ri-" + ns_from[len("lcert.formal."):]
    out = transform(text, R, D - R, ns_from, ns_to)
    open(dst, 'w').write(out)
    print(dst, "renamed tokens:", out.count("_ri"))
